open-telemetry/opentelemetry-ruby

CODEOWNERS
As per [the community membership guidelines](https://github.com/open-telemetry/community/blob/master/community-membership.md), I'm adding myself to CODEOWNERS.
My membership has been approved in this issue: 
[REQUEST: New membership as Ruby SIG approver for luvtechno · Issue \#121 · open\-telemetry/community](https://github.com/open-telemetry/community/issues/121)
=> Make myself a code owner

CODEOWNERS
Per [Nominating @mwear as Ruby maintainer by fbogsany · Pull Request \#142 · open\-telemetry/community](https://github.com/open-telemetry/community/pull/142), @mwear is now a maintainer. Adding him to CODEOWNERS.
=> Make @mwear CODEOWNER as maintainer

.gitignore, CODEOWNERS, api/.rubocop.yml, api/Gemfile, api/LICENSE, api/Rakefile, api/lib/opentelemetry.rb, api/lib/opentelemetry/context.rb, api/lib/opentelemetry/distributed_context.rb, api/lib/opentelemetry/metrics.rb, api/lib/opentelemetry/metrics/measure.rb, api/lib/opentelemetry/metrics/meter.rb, api/lib/opentelemetry/metrics/metric.rb, api/lib/opentelemetry/metrics/time_series.rb, api/lib/opentelemetry/resources.rb, api/lib/opentelemetry/resources/resource.rb, api/lib/opentelemetry/trace.rb, api/lib/opentelemetry/trace/span.rb, api/lib/opentelemetry/trace/span_context.rb, api/lib/opentelemetry/trace/span_data.rb, api/lib/opentelemetry/trace/span_kind.rb, api/lib/opentelemetry/trace/tracer.rb, api/lib/opentelemetry/version.rb, api/opentelemetry.gemspec
This is an early prototype of the OpenTelemetry Ruby API based on the API spec so far. Very much WIP, but feedback and discussion about any of this is strongly encouraged.
=> API prototype

.travis.yml, README.md, api/lib/opentelemetry.rb, api/lib/opentelemetry/distributed_context.rb, api/lib/opentelemetry/distributed_context/distributed_context.rb, api/lib/opentelemetry/distributed_context/entry.rb, api/lib/opentelemetry/distributed_context/propagation.rb, api/lib/opentelemetry/distributed_context/propagation/binary_format.rb, api/lib/opentelemetry/distributed_context/propagation/http_text_format.rb, api/lib/opentelemetry/internal.rb, api/lib/opentelemetry/metrics/meter.rb, api/lib/opentelemetry/trace/tracer.rb
This PR provides the [`DistributedContext` API](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/distributedcontext-api.md) and the [`BinaryFormat`](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/propagators-api.md#binary-format) part of the `Propagators` API.
Note: `DistributedContext::Manager` is part of https://github.com/open-telemetry/opentelemetry-ruby/pull/17
=> DistributedContext API

api/lib/opentelemetry/resources/resource.rb, api/test/resources/resource_test.rb
This PR makes some improvements to the `Resource` class. It implements `merge` according to the [specification](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/api-resources.md) and also adds tests and documentation. While working on this, I discovered that the original `merge` implementation wasn't working. This was because `initialize` expects labels as kwargs, but merge was passing them in as a `Hash<String, String>`. Since the labels are stored as a `Hash<String, String>` in resource, I updated `initialize` to expect a hash instead. See the comment and code in [this commit](https://github.com/open-telemetry/opentelemetry-ruby/commit/ecdc1e4897602fdb640abdacc1b8159536423b2b) for more context.
=> Improve Resource

api/lib/opentelemetry/trace/span.rb, api/lib/opentelemetry/trace/tracer.rb
This update the span creation API to reflect the [latest version of the spec](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/api-tracing.md#span-creation) and the [`SpanData` removal PR](https://github.com/open-telemetry/opentelemetry-specification/pull/215).
=> Update the span creation API

api/lib/opentelemetry/distributed_context/propagation/binary_format.rb, api/lib/opentelemetry/trace.rb, api/lib/opentelemetry/trace/span_context.rb, api/lib/opentelemetry/trace/trace_flags.rb, api/lib/opentelemetry/trace/tracer.rb, api/test/opentelemetry/trace/span_context_test.rb, api/test/opentelemetry/trace/trace_flags_test.rb
This implement `TraceFlags`. This used to be called `TraceOptions`, but https://github.com/open-telemetry/opentelemetry-specification/pull/234 proposes a rename to match the W3C spec.
This also implements `generate_span_id` and `generate_trace_id` in `SpanContext`.
=> Add TraceFlags class

api/test/opentelemetry/trace/link_test.rb, api/test/opentelemetry/trace/span_test.rb
There have a been a few PRs merged into master, and while all of them were passing tests individually, they are failing after integration. There were a couple of tests referring to `trace_flags` as `trace_options`. Recent updates to SpanContext makes creation easier, so I updated the affected tests to use `SpanContext.new` with default instead of explicit arguments.
=> Simplify SpanContext creation in tests

api/opentelemetry-api.gemspec
This PR addresses the following Rubocop offense about our dependency ordering.
```
Offenses:
opentelemetry-api.gemspec:35:3: C: Gemspec/OrderedDependencies: Dependencies should be sorted in an alphabetical order within their section of the gemspec. Dependency simplecov should appear before yard-doctest.
spec.add_development_dependency 'simplecov', '~> 0.17'
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
=> Sort dependencies alphabetically

api/lib/opentelemetry/trace/samplers/always_sample_sampler.rb, api/lib/opentelemetry/trace/samplers/never_sample_sampler.rb, api/lib/opentelemetry/trace/samplers/sampler.rb, api/test/opentelemetry/trace/samplers/always_sample_sampler_test.rb, api/test/opentelemetry/trace/samplers/never_sample_sampler_test.rb, api/test/opentelemetry/trace/samplers/sampler_test.rb, sdk/Rakefile, sdk/lib/opentelemetry/sdk/trace/samplers/probability_sampler.rb, sdk/test/opentelemetry/sdk/trace/samplers/probability_sampler_test.rb
This switches comparison in the ProbabilitySampler to be closer to the Java implementation, but compare in the ASCII codespace rather than in Integer space. May need some tweaks if we want an exact match, but I think this is more in the spirit of the "spec" than the `rand` approach.
=> Use string comparisons for ProbabilitySampler

.travis.yml, api/Rakefile, sdk/Rakefile
This adds support for TruffleRuby to CI. RuboCop is unhappy running on TruffleRuby, so I disabled that, along with Yard (since the builds are already kinda slow).
=> Add truffleruby

api/lib/opentelemetry/distributed_context/propagation/http_text_format.rb, api/lib/opentelemetry/distributed_context/propagation/trace_parent.rb, api/lib/opentelemetry/trace/span_context.rb, api/test/opentelemetry/distributed_context/propagation/http_text_format_test.rb, api/test/opentelemetry/trace/span_context_test.rb
Implements https://github.com/open-telemetry/opentelemetry-specification/pull/216.
Also adds tests for `HTTPTextFormat`, and fixes the bugs they exposed.
=> Add remote? to SpanContext

api/benchmarks/span_bench.rb, api/benchmarks/tracer_bench.rb, api/opentelemetry-api.gemspec
I was looking over #115 and thought it would be useful if we had some simple benchmarks as a point of comparison. This PR adds simple benchmarks for tracer and span. They can be run from the `/api` folder by typing: `bundle exec ruby benchmarks/tracer_bench.rb` or `bundle exec ruby benchmarks/span_bench.rb`. If we like these benchmarks, we can look into adding some niceties around running them.
=> Add basic benchmarks for tracer and span

Dockerfile, README.md, docker-compose.yml
Adds an initial Docker/Docker Compose configuration.
Adds an initial configuration for Docker and Docker Compose usage in development and testing. The `Dockerfile` has been added to give us a reliable and configurable Ruby environment. If we like this, we can eventually move the Docker image to another repo and make it available for use here.
A Docker Compose configuration is also provided to help with the development ergonimics. From the updated README:
* `app` - main container environment scoped to the `/app` directory. Used primarily to build and tag the `opentelemetry/opentelemetry-ruby:latest` image.
* `api` - convenience environment scoped to the `api` gem in the `/app/api` directory.
* `sdk` - convenience environment scoped to the `sdk` gem in the `/app/sdk` directory.
The README …
=> Add Docker and Docker Compose Configuration

api/lib/opentelemetry/trace/span_kind.rb
This simplifies the symbols used for `SpanKind` constants to improve API ergonomics. Users may prefer:
```ruby
span = tracer.start_span('op', kind: :client)
```
to
```ruby
span = tracer.start_span('op', kind: OpenTelemetry::Trace::SpanKind::CLIENT)
```
=> Simplify SpanKind

api/lib/opentelemetry/trace/tracer.rb, api/test/opentelemetry/trace/tracer_factory_test.rb, api/test/opentelemetry/trace/tracer_test.rb, sdk/test/opentelemetry/sdk/trace/export/batch_span_processor_test.rb, sdk/test/opentelemetry/sdk/trace/tracer_factory_test.rb
Updates `Tracer#in_span` to call `Span#finish` at the end of the block and adds API tests for `Tracer`.
While creating some examples based on the DataDog auto-instrumentation work I noticed that the `Tracer#in_span` implementation wasn't finishing the span as expected. I looked into the [Python implementation](https://github.com/open-telemetry/opentelemetry-python/blob/master/opentelemetry-sdk/src/opentelemetry/sdk/trace/__init__.py#L386) and saw the call the `end()`. This adds the call to `#finish` and adds tests to both the API and SDK.
The tests are going through some slight acrobatics to verify things are working as expected. Please let me know if there are better ways to do this given the implementation(s).
I added tests for the existing API `Tracer` implementation before updating …
=> Update Tracer#in_span to finish the Span

CODEOWNERS, README.md
This PR goes along with: https://github.com/open-telemetry/community/pull/239. It decentralizes the Ruby community members and adds @dazuma to codeowners.
=> Decentralize contributors

.circleci/config.yml, api/Rakefile, sdk/Rakefile
Implementation of #94.
Implements scripts that build and push releases of the API and SDK to Rubygems, and augments the CI config to trigger them.
The proposed release process is as follows. To release a gem:
1. The version constant must be set to the version to be released.
2. A tag called `#{gem_name}/v#{version}` must be created and pushed to Github. (e.g. `opentelemetry-api/v1.2.3`). Thus, anyone with direct write access to the repo will be able to initiate a release.
When the tag is created in Github, CircleCI will automatically (after running that gem's tests one final time) run the release script. This script:
1. Verifies that the tag's version matches the gem's version constant
2. Builds the gem and pushes to Rubygems.
The release script requires the following environment variable …
=> Create an initial release job

docker-compose.yml, examples/http/Gemfile, examples/http/Gemfile.lock, examples/http/README.md, examples/http/client.rb, examples/http/server.rb, examples/http/start_server.sh, sdk/lib/opentelemetry/sdk/trace/tracer_factory.rb
Adds a simple http client/server example using a [Sinatra](http://sinatrarb.com/) server and [Faraday](https://lostisland.github.io/faraday/) client. The example is modeled after the [Go http example](https://github.com/open-telemetry/opentelemetry-go/tree/master/example/http).
**Note: the console exporter won't be called until we merge in the `in_span` fix from #118**
* Adds the `examples` top-level directory
* Adds an `http` example directory that contains the client, server, and a small helper script
* Adds the `ex-http` docker-compose server to simplify setup/running of the example
* Adds a README to walk a person through running the example
This PR depends on #144 to function but it can be merged in any order.
#130 - Add simple HTTP client/server example
=> Add http client/server example

api/lib/opentelemetry/version.rb, exporters/jaeger/lib/opentelemetry/exporters/jaeger/version.rb, sdk/lib/opentelemetry/sdk/version.rb
This PR updates the versions of the API, SDK, and Jaeger Exporter to v0.2.0  for our release. Do these look good to everybody?
=> Update versions for v0.2.0 release

sdk/test/opentelemetry/sdk/trace/export/batch_span_processor_test.rb
Increases the timeout threshold of the "interrupt exporter" (batch span processor) test by 700ms.
This should improve the SDK test suite's robustness.
https://github.com/open-telemetry/opentelemetry-ruby/pull/133#discussion_r340676385 raised some concerns that have since been witnessed a few times
The value was determined experimentally, on a development laptop.
=> Improve test robustness under heavily loaded CI

api/lib/opentelemetry/trace/status.rb, api/lib/opentelemetry/trace/util/http_to_status.rb, api/test/opentelemetry/trace/status_test.rb
Adds a `Trace::Status.http_to_status(code)` method to facilitate mapping from http status code to `Status`.
* https://github.com/open-telemetry/opentelemetry-specification/issues/306
* [Status Canonical Code](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/api-tracing.md#statuscanonicalcode)
* [HTTP to Status Mapping Guidance](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/data-http.md#status)
* Extracted from #149 
* #149
=> API: Add HTTP to Status convenience mapper

.gitignore, api/.rubocop.yml, api/.yardopts, api/OVERVIEW.md, api/Rakefile, api/lib/opentelemetry-api.rb, api/lib/opentelemetry.rb, api/opentelemetry-api.gemspec, exporters/jaeger/.rubocop.yml, exporters/jaeger/.yardopts, exporters/jaeger/OVERVIEW.md, exporters/jaeger/Rakefile, exporters/jaeger/lib/opentelemetry-exporters-jaeger.rb, exporters/jaeger/lib/opentelemetry/exporters/jaeger.rb, exporters/jaeger/lib/opentelemetry/exporters/jaeger/exporter.rb, exporters/jaeger/opentelemetry-exporters-jaeger.gemspec, sdk/.rubocop.yml, sdk/.yardopts, sdk/OVERVIEW.md, sdk/Rakefile, sdk/lib/opentelemetry-sdk.rb, sdk/opentelemetry-sdk.gemspec
This includes a bunch of cleanup changes targeted toward making the YARD docs work well.
Specifics:
* Wrote an `OVERVIEW.md` file for each gem, to be used as the "front page" for YARD docs.
* Also included the changelog in the YARD output.
* Set a title on the YARD docs.
* Omitted private objects
* Built the docs into the default output directory (`doc`) instead of a custom directory (e.g. `docs/api`).
* Moved the pertinent arguments from the YARD rake tasks into `.yardopts` files (and added those to the gemspec) so that rubydoc.info will know how to build the docs properly.
Notes:
* `.yardopts` doesn't include Ruby code, so the hack involving reordering the list of files to avoid the copyright notice being listed as the documentation for the toplevel module doesn't work. But I was able …
=> General cleanup of yardocs

adapters/faraday/lib/opentelemetry/adapters/faraday/adapter.rb
In order to remove a hard dependency on Faraday, I had to require the TracerMiddleware during install. While testing #171 I noticed that the middleware will be referenced before it's required during usual startup. Sadly, this was not caught in tests and is hard to test since once a file has been required, it can't exactly be unrequired.
=> Fix faraday adapter

api/lib/opentelemetry/trace/span.rb, sdk/lib/opentelemetry/sdk/trace/span.rb
Just fix documentation URLs of Semantic Conventions which look old.
=> Update Semantic Conventions URLs

sdk/lib/opentelemetry/sdk.rb, sdk/lib/opentelemetry/sdk/configurator.rb, sdk/test/opentelemetry/sdk/configurator_test.rb
This PR is an implementation of SDK config for currently implemented features. It's based off of #165, but with speculative, future feature configuration removed. With this implementation you can configure logging, tracer factory, span processors and install instrumentation.
Here are some examples:
If a block is not specified it will setup defaults
* STDOUT logging
* SDK::Trace::TracerFactory
* SimpleSpanProcessor with ConsoleSpanExporter
* No instrumentation
```ruby
OpenTelemetry::SDK.configure
```
The following can be customized:
* Logger
* Tracer Factory
* Span Processors
* Instrumentation: installed individually, or all, but not both
Customize the setup and specify instrumentation individually
```ruby
OpenTelemetry::SDK.configure do |c|
c.tracer_factory = ...
c.logger = …
```
=> Preliminary sdk config

Rakefile, adapters/faraday/.rubocop.yml, adapters/faraday/Appraisals, adapters/faraday/Rakefile, adapters/faraday/example/Gemfile, adapters/faraday/example/faraday.rb, adapters/faraday/lib/opentelemetry/adapters/faraday.rb, adapters/faraday/lib/opentelemetry/adapters/faraday/adapter.rb, adapters/faraday/lib/opentelemetry/adapters/faraday/middlewares/tracer_middleware.rb, adapters/faraday/opentelemetry-adapters-faraday.gemspec, adapters/faraday/test/.rubocop.yml, adapters/sinatra/.rubocop.yml, adapters/sinatra/Appraisals, adapters/sinatra/Rakefile, adapters/sinatra/example/Gemfile, adapters/sinatra/example/server.rb, adapters/sinatra/example/sinatra.rb, adapters/sinatra/lib/opentelemetry/adapters/sinatra.rb, adapters/sinatra/lib/opentelemetry/adapters/sinatra/adapter.rb, adapters/sinatra/lib/opentelemetry/adapters/sinatra/extensions/tracer_extension.rb, adapters/sinatra/lib/opentelemetry/adapters/sinatra/middlewares/tracer_middleware.rb, adapters/sinatra/opentelemetry-adapters-sinatra.gemspec, adapters/sinatra/test/.rubocop.yml, adapters/sinatra/test/opentelemetry/adapters/sinatra_test.rb
The instrumentation adapters did not have rubocop setup and as a result had a number of violations. This PR sets up rubocop and fixes the violations for the Faraday and Sinatra instrumentation adapters. It also adds them to the top-level Rakefile so that tests are run automatically.
=> Add rubocop to adapters

sdk/lib/opentelemetry/sdk/configurator.rb, sdk/test/opentelemetry/sdk/configurator_test.rb
This PR adds SDK configuration for `http_injectors / extractors` and sets the `CorrelationContext::Manager` to the operational SDK implementation. Note, that http_injectors and extractors are empty by default in the API, making them effectively a noop. There is not consensus on what they should default to currently, so empty seems like a reasonable option for now. See: https://github.com/open-telemetry/opentelemetry-specification/issues/428. 
This PR makes W3C TraceContext and CorrelationContext the default injectors and extractors when the SDK is configured. They can also be specified by the user.
```ruby
OpenTelemetry::SDK.configure do |c|
c.use_all
end
```
```ruby
OpenTelemetry::SDK.configure do |c|
c.http_injectors = [Propagation::TraceContext.http_injector, …
```
=> Add SDK configuration for http_injectors / extractors

sdk/lib/opentelemetry/sdk/trace/tracer_provider.rb, sdk/test/opentelemetry/sdk/trace/tracer_provider_test.rb
While doing some QA earlier, I noticed that when we attempt to add a second span processor we get a FrozenError like the example below:
```
FrozenError: can't modify frozen Array
/Users/matthewwear/Repos/opentelemetry-ruby/sdk/lib/opentelemetry/sdk/trace/tracer_provider.rb:77:in `block in add_span_processor'
/Users/matthewwear/Repos/opentelemetry-ruby/sdk/lib/opentelemetry/sdk/trace/tracer_provider.rb:72:in `synchronize'
/Users/matthewwear/Repos/opentelemetry-ruby/sdk/lib/opentelemetry/sdk/trace/tracer_provider.rb:72:in `add_span_processor'
/Users/matthewwear/Repos/opentelemetry-ruby/sdk/lib/opentelemetry/sdk/configurator.rb:105:in `block in configure_span_processors'
/Users/matthewwear/Repos/opentelemetry-ruby/sdk/lib/opentelemetry/sdk/configurator.rb:105:in `each' …
```
=> Bugfix: multiple span processors

adapters/sinatra/lib/opentelemetry/adapters/sinatra/middlewares/tracer_middleware.rb
Fixes `Rack::Utils` resolution is conflicted when using rack instrumentation, since it includes Rack::Utils as well.
Problem is mentioned here: https://github.com/open-telemetry/opentelemetry-ruby/pull/166#pullrequestreview-363831738
=> Fix ::Rack::Utils namespace resolution

.circleci/config.yml, Rakefile, adapters/net_http/.rubocop.yml, adapters/net_http/Gemfile, adapters/net_http/Rakefile, adapters/net_http/example/Gemfile, adapters/net_http/example/net_http.rb, adapters/net_http/lib/opentelemetry-adapters-net-http.rb, adapters/net_http/lib/opentelemetry/adapters.rb, adapters/net_http/lib/opentelemetry/adapters/net/http.rb, adapters/net_http/lib/opentelemetry/adapters/net/http/adapter.rb, adapters/net_http/lib/opentelemetry/adapters/net/http/patches/instrumentation.rb, adapters/net_http/lib/opentelemetry/adapters/net/http/version.rb, adapters/net_http/opentelemetry-adapters-net-http.gemspec, adapters/net_http/test/.rubocop.yml, adapters/net_http/test/opentelemetry/adapters/net/http/adapter_test.rb, adapters/net_http/test/test_helper.rb, docker-compose.yml
Add `Net::HTTP` instrumentation adapter similar to the other HTTP client adapters.
* Effort toward resolving #67
=> Add `Net:HTTP` instrumentation adapter

sdk/lib/opentelemetry/sdk/trace/export/batch_span_processor.rb, sdk/lib/opentelemetry/sdk/trace/export/simple_span_processor.rb, sdk/lib/opentelemetry/sdk/trace/multi_span_processor.rb, sdk/lib/opentelemetry/sdk/trace/noop_span_processor.rb, sdk/test/opentelemetry/sdk/trace/export/simple_span_processor_test.rb, sdk/test/opentelemetry/sdk/trace/multi_span_processor_test.rb, sdk/test/opentelemetry/sdk/trace/noop_span_processor_test.rb
Fixes #195 
Conveniently, we already had this implemented as a private method `flush` in `BatchSpanProcessor`.
=> Implement force_flush

api/lib/opentelemetry/metrics/handles.rb, api/lib/opentelemetry/metrics/instruments.rb, api/lib/opentelemetry/metrics/meter.rb, api/test/opentelemetry/metrics/meter_test.rb
Implement [OTEP 90](https://github.com/open-telemetry/oteps/blob/master/text/0090-remove-labelset-from-metrics-api.md) and [OTEP 80](https://github.com/open-telemetry/oteps/blob/master/text/0080-remove-metric-gauge.md).
Observers will be added in a separate PR ([OTEP 72](https://github.com/open-telemetry/oteps/blob/master/text/0072-metric-observer.md)).
=> Remove Gauges and LabelSet

.circleci/config.yml, Rakefile, adapters/ethon/.rubocop.yml, adapters/ethon/Appraisals, adapters/ethon/Gemfile, adapters/ethon/Rakefile, adapters/ethon/example/Gemfile, adapters/ethon/example/ethon.rb, adapters/ethon/lib/opentelemetry-adapters-ethon.rb, adapters/ethon/lib/opentelemetry/adapters.rb, adapters/ethon/lib/opentelemetry/adapters/ethon.rb, adapters/ethon/lib/opentelemetry/adapters/ethon/adapter.rb, adapters/ethon/lib/opentelemetry/adapters/ethon/patches/easy.rb, adapters/ethon/lib/opentelemetry/adapters/ethon/patches/multi.rb, adapters/ethon/lib/opentelemetry/adapters/ethon/version.rb, adapters/ethon/opentelemetry-adapters-ethon.gemspec, adapters/ethon/test/.rubocop.yml, adapters/ethon/test/opentelemetry/adapters/ethon/adapter_test.rb, adapters/ethon/test/test_helper.rb, docker-compose.yml
Add `ethon` instrumentation adapter based on the adapter for `rest-client` and `ddtrace` code for `ethon`.
While the purpose of this adapter is to instrument HTTP requests in particular, it is my understanding that the protocol could be something else without being able to detect and there are also times where the HTTP method/verb is unknowable.
`ddtrace` also had a parent span for `Ethon::Multi`, but that is currently not provided here because I do not think the those spans could be compliant with the specification.
Related to #67
=> Add `ethon` instrumentation adapter

README.md, Rakefile, adapters/all/.rubocop.yml, adapters/all/Gemfile, adapters/all/LICENSE, adapters/all/README.md, adapters/all/Rakefile, adapters/all/lib/opentelemetry-adapters-all.rb, adapters/all/lib/opentelemetry/adapters/all.rb, adapters/all/lib/opentelemetry/adapters/all/version.rb, adapters/all/opentelemetry-adapters-all.gemspec, adapters/all/opentelemetry-adapters-faraday.gemspec, adapters/all/test/.rubocop.yml, adapters/all/test/test_helper.rb
This gem is an all-in-one distribution of all of the officially supported instrumentation adapters. This will likely be the go-to method that users will use to add instrumentation dependencies to their application. With this package users will only need the following to get off the ground with opentelemetry.
Gemfile
```ruby
source `https://rubygems.org`
gem `opentelemetry-sdk`
gem `opentelemetry-adapters-all`
```
App
```ruby
OpenTelemetry::SDK.configure do |c|
c.use_all
end
```
=> opentelemetry-adapters-all gem

.circleci/config.yml, adapters/concurrent_ruby/.rubocop.yml, adapters/concurrent_ruby/opentelemetry-adapters-concurrent_ruby.gemspec, adapters/ethon/.rubocop.yml, adapters/ethon/opentelemetry-adapters-ethon.gemspec, adapters/excon/.rubocop.yml, adapters/excon/opentelemetry-adapters-excon.gemspec, adapters/faraday/.rubocop.yml, adapters/faraday/opentelemetry-adapters-faraday.gemspec, adapters/net_http/.rubocop.yml, adapters/net_http/opentelemetry-adapters-net_http.gemspec, adapters/rack/.rubocop.yml, adapters/rack/opentelemetry-adapters-rack.gemspec, adapters/redis/.rubocop.yml, adapters/redis/opentelemetry-adapters-redis.gemspec, adapters/restclient/.rubocop.yml, adapters/restclient/opentelemetry-adapters-restclient.gemspec, adapters/sinatra/.rubocop.yml, adapters/sinatra/opentelemetry-adapters-sinatra.gemspec, api/.rubocop.yml, api/lib/opentelemetry/context/propagation/composite_propagator.rb, api/opentelemetry-api.gemspec, exporters/jaeger/.rubocop.yml, exporters/jaeger/opentelemetry-exporters-jaeger.gemspec, sdk/.rubocop.yml, sdk/lib/opentelemetry/sdk/trace/export/multi_span_exporter.rb, sdk/opentelemetry-sdk.gemspec, sdk/test/opentelemetry/sdk/trace/span_test.rb
Ruby 2.4 has reached EOL and is no longer supported. See https://www.ruby-lang.org/en/news/2020/04/05/support-of-ruby-2-4-has-ended/
=> Remove Ruby 2.4 support (EOL)

docker-compose.yml
This commit fixes the Sinatra example so that it runs out of the box
like the standard `ex-http` example when called with
`docker-compose run ex-adapter-sinatra`.
=> Fix Sinatra example in docker-compose.yml

exporters/jaeger/test/opentelemetry/exporters/jaeger/exporter/span_encoder_test.rb, exporters/jaeger/test/opentelemetry/exporters/jaeger/exporter_test.rb, sdk/lib/opentelemetry/sdk.rb, sdk/lib/opentelemetry/sdk/instrumentation_library.rb, sdk/lib/opentelemetry/sdk/trace/span.rb, sdk/lib/opentelemetry/sdk/trace/span_data.rb, sdk/lib/opentelemetry/sdk/trace/tracer.rb, sdk/test/opentelemetry/sdk/trace/span_test.rb, sdk/test/opentelemetry/sdk/trace/tracer_test.rb
Following @mwear's comment in #261, this is a proposal to implement the instrumentation library pattern, as I understand it from open-telemetry/oteps/pull/84.
=> Setup instrumentation library

adapters/ethon/lib/opentelemetry/adapters/ethon/patches/easy.rb, adapters/ethon/test/opentelemetry/adapters/ethon/adapter_test.rb, adapters/excon/lib/opentelemetry/adapters/excon/middlewares/tracer_middleware.rb, adapters/excon/test/opentelemetry/adapters/excon/adapter_test.rb, adapters/faraday/lib/opentelemetry/adapters/faraday/middlewares/tracer_middleware.rb, adapters/faraday/test/opentelemetry/adapters/faraday/middlewares/tracer_middleware_test.rb, adapters/net_http/lib/opentelemetry/adapters/net/http/patches/instrumentation.rb, adapters/net_http/test/opentelemetry/adapters/net/http/adapter_test.rb, adapters/rack/lib/opentelemetry/adapters/rack/middlewares/tracer_middleware.rb, adapters/rack/test/opentelemetry/adapters/rack/middlewares/tracer_middleware_test.rb, adapters/redis/lib/opentelemetry/adapters/redis/patches/client.rb, adapters/redis/test/opentelemetry/adapters/redis/adapter_test.rb, adapters/restclient/lib/opentelemetry/adapters/restclient/patches/request.rb, adapters/restclient/test/opentelemetry/adapters/restclient/adapter_test.rb, adapters/sinatra/lib/opentelemetry/adapters/sinatra/middlewares/tracer_middleware.rb, adapters/sinatra/test/opentelemetry/adapters/sinatra_test.rb
See https://github.com/open-telemetry/opentelemetry-specification/pull/447
Adapters will later be able to specify what instrumentation library they are, and the exporters can then log this however they want: https://github.com/open-telemetry/opentelemetry-ruby/pull/264
=> Remove component attribute from all adapters

sdk/lib/opentelemetry/sdk/trace/samplers.rb, sdk/lib/opentelemetry/sdk/trace/samplers/constant_sampler.rb, sdk/lib/opentelemetry/sdk/trace/samplers/parent_or_else.rb, sdk/lib/opentelemetry/sdk/trace/samplers/probability_sampler.rb, sdk/lib/opentelemetry/sdk/trace/tracer.rb, sdk/test/opentelemetry/sdk/trace/samplers_test.rb, sdk/test/opentelemetry/sdk/trace/tracer_test.rb
Fixes #269 
Fixes #267 
This also changes the `Sampler` interface to match the spec. Specifically, we did not provide a `description` method, and the requirement to add it removes much of the value of providing a `Callable` interface, so this also renames the `call` method to `should_sample?` to match the spec.
=> Remove span_id from samplers

exporters/jaeger/.rubocop.yml, exporters/jaeger/test/opentelemetry/exporters/jaeger/exporter/span_encoder_test.rb, exporters/jaeger/test/opentelemetry/exporters/jaeger/exporter_test.rb, sdk/.rubocop.yml, sdk/lib/opentelemetry/sdk/trace/span.rb, sdk/lib/opentelemetry/sdk/trace/span_data.rb, sdk/test/integration/global_tracer_configurations_test.rb
This PR adds a span's `context.tracestate` to the SpanData Struct which gets created by `to_span_data` and is used in conjunction with trace processors and exporters.  
The reasoning behind this is that there may be some vendor specific arbitrary metadata which is generally passed via distributed tracing headers and, as far as I understand, would live on the `context.tracestate` when extracted. 
Examples of this could be: 
- baggage items from open tracing, which can be [extracted/injected via http headers](https://opentracing.io/docs/overview/inject-extract/). although this isn't particularly popular, [it's implemented](https://github.com/lightstep/lightstep-tracer-objc/blob/e7e0b6fd68d05f032970ff0cc548c27b877854ba/Pod/Classes/LSTracer.m#L151) in some different vendors. 
- For vendor …
=> add tracestate to span data

adapters/all/lib/opentelemetry/adapters/all/version.rb, adapters/all/opentelemetry-adapters-all.gemspec, adapters/sinatra/lib/opentelemetry/adapters/sinatra/version.rb
This PR bumps the versions of the sinatra adapter and the adapters-all gem. The bugfix release will include the changes introduced in #275.
cc: @mat-rumian
=> prepare adapter bugfix release

adapters/ethon/test/opentelemetry/adapters/ethon/adapter_test.rb, adapters/excon/test/opentelemetry/adapters/excon/adapter_test.rb, adapters/faraday/test/opentelemetry/adapters/faraday/middlewares/tracer_middleware_test.rb, adapters/net_http/test/opentelemetry/adapters/net/http/adapter_test.rb, adapters/rack/test/opentelemetry/adapters/rack/middlewares/tracer_middleware_test.rb, adapters/restclient/test/opentelemetry/adapters/restclient/adapter_test.rb, adapters/sidekiq/test/opentelemetry/adapters/sidekiq/adapter_test.rb, api/lib/opentelemetry/trace.rb, api/lib/opentelemetry/trace/propagation/trace_context/trace_parent.rb, api/test/opentelemetry/trace/propagation/trace_context/text_extractor_test.rb, api/test/opentelemetry/trace/propagation/trace_context/text_injector_test.rb, api/test/opentelemetry/trace/propagation/trace_context/trace_parent_test.rb, exporters/jaeger/lib/opentelemetry/exporters/jaeger/exporter/span_encoder.rb
=> Spec compliance for span and trace IDs

README.md
`bundle install opentelemetry-api` doesn't work and produces this error:
```sh
>> bundle install opentelemetry-api
ERROR: "bundle install" was called with arguments ["opentelemetry-api"]
Usage: "bundle install [OPTIONS]"
```
This PR fixes the instructions for installing via `gem` and with `Bundler`
=> fixed note on how to install opentelemetry-api and opentelemetry-sdk

api/lib/opentelemetry/correlation_context/propagation.rb, api/lib/opentelemetry/correlation_context/propagation/text_extractor.rb, api/lib/opentelemetry/correlation_context/propagation/text_injector.rb, api/test/opentelemetry/correlation_context/text_extractor_test.rb, api/test/opentelemetry/correlation_context/text_injector_test.rb
Fixes #289. OpenTelemetry has decided to use a custom header for propagating correlation context (see: https://github.com/open-telemetry/opentelemetry-specification/pull/517). This PR changes the header name from `Correlation-Context` to `otcorrelations`.
=> Use otcorrelations for correlation context header

CHANGELOG.md, api/lib/opentelemetry/version.rb, sdk/lib/opentelemetry/sdk/version.rb
This PR bumps the API and SDK versions and adds changelog entires in preparation for a patch release that will address #298 and #300. After this merges I can cut a new gem versions for opentelemetry-api and opentelemetry-sdk.
=> prepare for 0.5.1 release

resource_detectors/lib/opentelemetry-resource_detectors.rb, resource_detectors/opentelemetry-resource_detectors.gemspec
Missing conventional ruby file matching gem name in the `/lib` folder.
=> Fix gemspec name for resource detector

api/lib/opentelemetry/trace.rb, api/lib/opentelemetry/trace/propagation/trace_context/trace_parent.rb, api/lib/opentelemetry/trace/span_context.rb, instrumentation/ethon/test/opentelemetry/instrumentation/ethon/instrumentation_test.rb, instrumentation/excon/test/opentelemetry/instrumentation/excon/instrumentation_test.rb, instrumentation/faraday/test/opentelemetry/instrumentation/faraday/middlewares/tracer_middleware_test.rb, instrumentation/net_http/test/opentelemetry/instrumentation/net/http/instrumentation_test.rb, instrumentation/restclient/test/opentelemetry/instrumentation/restclient/instrumentation_test.rb, sdk/lib/opentelemetry/sdk/trace/span_data.rb
Implements https://github.com/open-telemetry/opentelemetry-specification/pull/836.
Rather than rename `trace_id` and `span_id` to `binary_trace_id` and `binary_span_id`, I've left them as is and added documentation describing their format.
=> Add hex_trace_id and hex_span_id helpers

CODEOWNERS
This adds @robertlaurin to the list of Approvers for OpenTelemetry Ruby. Robert contributed the Resource auto-detectors. He also maintains Shopify's wrapper gem for OpenTelemetry.
This also proposes removing @bai, @luvtechno and @elskwid from the Approvers list. They have not been active in this project for many months, at least. We're very grateful for @elskwid's early contributions, in particular, however Approver status requires continued active involvement in the project.
=> Refactor approvers

exporters/jaeger/lib/opentelemetry/exporters/jaeger/exporter/span_encoder.rb, exporters/jaeger/test/opentelemetry/exporters/jaeger/exporter/span_encoder_test.rb
Fixes #344. This PR properly exports the instrumentation library by merging the name and version into span tags. See: https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/sdk_exporters/jaeger.md#instrumentationlibrary
=> export instrumentation library for jaeger

README.md
This PR updates the readme to reflect the current approvers. I also took the opportunity to change the casing of the S in Lightstep (we rebranded).
=> update readme with current approvers

exporters/jaeger/lib/opentelemetry/exporters/jaeger/exporter.rb, exporters/jaeger/lib/opentelemetry/exporters/jaeger/exporter/encoding_utils.rb, exporters/jaeger/lib/opentelemetry/exporters/jaeger/exporter/span_encoder.rb, exporters/jaeger/test/opentelemetry/exporters/jaeger/exporter_test.rb, sdk/lib/opentelemetry/sdk/trace/span.rb, sdk/lib/opentelemetry/sdk/trace/span_data.rb
Fixes #312 and #314.
This PR updates the Jaeger exporter to export resources as process tags. It properly accounts for multiple resources in the same process, by grouping by resource and sending associated spans in batches.
cc: @genebean
=> Export resources from Jaeger

instrumentation/rack/opentelemetry-instrumentation-rack.gemspec
The rack instrumentation references `bundler ~> 2.0.2` which is atypical and leads to the following error:
```
**** Entering instrumentation/rack
bundle install
Fetching gem metadata from https://rubygems.org/.........
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Bundler could not find compatible versions for gem "bundler":
In Gemfile:
bundler (~> 2.0.2)
Current Bundler version:
bundler (2.1.4)
This Gemfile requires a different version of Bundler.
Perhaps you need to update Bundler by running `gem install bundler`?
Could not find gem 'bundler (~> 2.0.2)' in any of the relevant sources:
the local ruby installation
rake aborted!
Command failed with status (6): [bundle install...]
/Users/mlang/projects/otel/mwlang/opentelemetry-ruby/Rakefile:147:in `block (3 …
```
=> updates rack's bundler dependency to match the rest of instrumentations

exporter/jaeger/lib/opentelemetry/exporter/jaeger/encoder.rb, exporter/otlp/lib/opentelemetry/exporter/otlp/exporter.rb, resource_detectors/lib/opentelemetry/resource/detectors/google_cloud_platform.rb, resource_detectors/test/opentelemetry/detectors/auto_detector_test.rb, resource_detectors/test/opentelemetry/detectors/google_cloud_platform_test.rb, sdk/lib/opentelemetry/sdk/resources/resource.rb, sdk/test/opentelemetry/sdk/configurator_test.rb, sdk/test/opentelemetry/sdk/resources/resource_test.rb
=> fix!: Rename Resource labels to attributes

.toys/release/.lib/release_requester.rb, .toys/release/create-labels.rb, .toys/release/request.rb, CONTRIBUTING.md
Changes to release scripts:
* Relax the version constant regex so it recognizes single quotes and different spacing
* Fail fast if the version constant cannot be found
* Issue a warning if the version constant was already set to the new version
* If a changelog entry for the new version already exists, issue a warning and do not add another
* Display a more helpful error if no changes were made and the PR would be empty
* Support for force-releasing all gems by using the gem name "all".
* Remove spurious escaping when updating labels
=> chore: Better error and edge case checking when modifying version and changelog

instrumentation/concurrent_ruby/README.md
This PR adds documentation for Concurrent Ruby, closing [#234.](https://github.com/open-telemetry/opentelemetry-ruby/issues/234)
I have added a README document describing the Concurrent ruby gem, installation methods and its license.
=> Added README for concurrent ruby 

sdk/lib/opentelemetry/sdk/trace/tracer.rb
We generate a span ID in the SDK's `Tracer#start_span` that we never use. I think it used to be required for sampling, but that requirement was removed. This removes the extraneous work.
=> fix: Don't generate a span ID unnecessarily

instrumentation/rack/README.md
This PR adds documentation for OpenTelemetry-Ruby's Rack Instrumentation, which closes [#239](https://github.com/open-telemetry/opentelemetry-ruby/issues/239). 
The README describes the Rack gem, installation methods and its license, following the pattern set in instrumentation/sinatra for consistency.
=> Added README for Rack Instrumentation

instrumentation/ethon/README.md
This PR adds documentation for OpenTelemetry's Ethon Instrumentation, closing open-telemetry#235.
The README follows the examples for instrumentation/ethon/README.md and instrumentation/sidekiq/README.md.
=> Add README for Ethon

instrumentation/sidekiq/README.md
This PR adds documentation for OpenTelemetry's Sidekiq Instrumentation, closing #241 . The README describes the Sidekiq gem, installation methods and its license, following the pattern set in [instrumentation/sinatra](https://github.com/open-telemetry/opentelemetry-ruby/blob/master/instrumentation/sinatra/README.md) and [instrumentation/concurrent_ruby](https://github.com/open-telemetry/opentelemetry-ruby/blob/master/instrumentation/concurrent_ruby/README.md) for consistency.
=> Adding README for Sidekiq instrumentation

README.md
The release schedule is horribly out of date. Some other repos have chosen to post a feature status instead, but most have nothing at all. I've opted here for no information rather than bad information.
=> docs: Remove release schedule

instrumentation/net_http/README.md
Documentation for Net HTTP Instrumentation. Should be similar to other recent documentation prs such as PR #386 . This hopefully resolves issue #238 .
=> Added documentation for net_http gem in instrumentation

exporter/jaeger/test/opentelemetry/exporters/jaeger/encoder_test.rb, exporter/jaeger/test/test_helper.rb, exporter/otlp/test/opentelemetry/exporter/otlp/exporter_test.rb, sdk/lib/opentelemetry/sdk/trace/span.rb, sdk/lib/opentelemetry/sdk/trace/span_data.rb
`child_count` is not required or supported by OTLP, so we don't need to
record it anymore in `SpanData` or track it in `Span` (we weren't, but we
had an unnecessary instance variable).
This is a breaking change for `SpanExporter`s that may have used
`SpanData`'s child_count. None of the exporters in this repo used it,
and I doubt anyone else did either.
=> fix! remove child_count

exporter/otlp/README.md
The named parameter was replaced with a positional parameter.
Reported in #380
=> docs: fix use of add_event in OTLP doc

sdk/lib/opentelemetry/sdk/trace/samplers.rb, sdk/lib/opentelemetry/sdk/trace/samplers/decision.rb, sdk/lib/opentelemetry/sdk/trace/samplers/result.rb, sdk/lib/opentelemetry/sdk/trace/samplers/trace_id_ratio_based.rb, sdk/test/opentelemetry/sdk/trace/samplers/result_test.rb, sdk/test/opentelemetry/sdk/trace/samplers_test.rb, sdk/test/opentelemetry/sdk/trace/tracer_test.rb
Implements https://github.com/open-telemetry/opentelemetry-specification/pull/938
This is a breaking change.
=> fix! consistent naming for sampling results

api/lib/opentelemetry/trace/propagation/trace_context/text_map_extractor.rb, api/lib/opentelemetry/trace/propagation/trace_context/text_map_injector.rb, api/lib/opentelemetry/trace/tracer.rb, api/test/opentelemetry/trace/propagation/trace_context/text_extractor_test.rb, api/test/opentelemetry/trace/tracer_test.rb, sdk/lib/opentelemetry/sdk/trace/tracer.rb, sdk/test/integration/global_tracer_configurations_test.rb, sdk/test/opentelemetry/sdk/trace/tracer_test.rb
Before this PR a context could contain an extracted span context, a current span, no span context, or both an extracted span context and a current span. This PR removes the special case handling needed for managing an extracted span context by wrapping it in a noop API span. With this simplification we only need to manage the current span.
Related to: https://github.com/open-telemetry/opentelemetry-specification/issues/949
=> refactor: remove extracted span context special case

sdk/lib/opentelemetry/sdk/trace/export.rb, sdk/lib/opentelemetry/sdk/trace/export/batch_span_processor.rb, sdk/lib/opentelemetry/sdk/trace/export/console_span_exporter.rb, sdk/lib/opentelemetry/sdk/trace/export/in_memory_span_exporter.rb, sdk/lib/opentelemetry/sdk/trace/export/multi_span_exporter.rb, sdk/lib/opentelemetry/sdk/trace/export/noop_span_exporter.rb, sdk/lib/opentelemetry/sdk/trace/export/simple_span_processor.rb, sdk/lib/opentelemetry/sdk/trace/multi_span_processor.rb, sdk/lib/opentelemetry/sdk/trace/noop_span_processor.rb
Fixes #405 
This adds return codes for `SpanProcessor#force_flush` and `SpanProcessor#shutdown`. They don't necessarily make sense on their own at the moment, but once #341 lands, this will allow callers to check for success/failure/timeout.
Since most of the processors live in the `Export` module, I overloaded the result codes we've already defined there, and added `TIMEOUT`.
=> fix! Return results from force_flush and shutdown

sdk/lib/opentelemetry/sdk/configurator.rb, sdk/test/opentelemetry/sdk/configurator_test.rb
Adds a convenience method so setter the service.name resource attribute.
Closes #379
=> feat: Add service_name setter to configurator

api/lib/opentelemetry/trace/status.rb, api/lib/opentelemetry/trace/tracer.rb, api/lib/opentelemetry/trace/util/http_to_status.rb, api/test/opentelemetry/trace/status_test.rb, exporter/jaeger/lib/opentelemetry/exporter/jaeger/encoder.rb, exporter/jaeger/test/opentelemetry/exporters/jaeger/encoder_test.rb, exporter/otlp/lib/opentelemetry/exporter/otlp/exporter.rb, exporter/otlp/test/opentelemetry/exporter/otlp/exporter_test.rb, instrumentation/ethon/lib/opentelemetry/instrumentation/ethon/patches/easy.rb, instrumentation/ethon/test/opentelemetry/instrumentation/ethon/instrumentation_test.rb, instrumentation/excon/lib/opentelemetry/instrumentation/excon/middlewares/tracer_middleware.rb, instrumentation/excon/test/opentelemetry/instrumentation/excon/instrumentation_test.rb, instrumentation/mysql2/test/opentelemetry/instrumentation/mysql2/instrumentation_test.rb, instrumentation/net_http/test/opentelemetry/instrumentation/net/http/instrumentation_test.rb, instrumentation/rack/test/opentelemetry/instrumentation/rack/middlewares/tracer_middleware_test.rb, instrumentation/redis/test/opentelemetry/instrumentation/redis/instrumentation_test.rb, instrumentation/sinatra/test/opentelemetry/instrumentation/sinatra_test.rb, sdk/lib/opentelemetry/sdk/trace/span.rb, sdk/test/opentelemetry/sdk/trace/span_test.rb, sdk/test/opentelemetry/sdk/trace/tracer_test.rb
This implements the new Span.Status spec: https://github.com/open-telemetry/opentelemetry-specification/pull/966
We need the mapping to OTLP to be specified in order to complete this, however that is strictly additive and this implements the proposal for OK & Unset -> OK and Error -> UnknownError.
=> fix! implement new Span.Status spec

.toys/.data/releases.yml, .toys/yardoc.rb
This should enable building reference documentation during the release process and pushing it to https://open-telemetry.github.io/opentelemetry-ruby
=> chore: Tool for building yardoc during release

exporter/jaeger/README.md, exporter/otlp/README.md
All real-world usage should avoid the `SimpleSpanProcessor` so it is not what we should be recommending by way of our example code. This updates the two places it was being recommended to instead use the `BatchSpanProcessor`. 
This relates to #397 but does not resolve it.
This update also includes correcting the Jaeger collector endpoint for #378
=> docs: Use BatchSpanProcessor in examples

exporter/jaeger/README.md, sdk/lib/opentelemetry/sdk/configurator.rb, sdk/test/opentelemetry/sdk/configurator_test.rb
PR #417 added a setter to the configurator for service.name - this follows suite by adding the same for service.version to simplify the setting of the other attribute requested by many tracing backends.
Prior to this change, setting the pair of these would have looked like this:
```ruby
c.service_name = 'Otel Demo App'
c.resource = OpenTelemetry::SDK::Resources::Resource.create(
OpenTelemetry::SDK::Resources::Constants::SERVICE_RESOURCE[:version] => '0.6.0'
)
```
After this change, the same is accomplished with this:
```ruby
c.service_name = 'Otel Demo App'
c.service_version = '0.6.0'
```
=> feat: Add service_version setter to configurator

exporter/jaeger/lib/opentelemetry/exporter/jaeger/encoder.rb, exporter/jaeger/test/opentelemetry/exporters/jaeger/encoder_test.rb
This PR addresses https://github.com/open-telemetry/opentelemetry-ruby/issues/423
=> fix: update IL attribute naming convention to match spec

exporter/otlp/lib/opentelemetry/exporter/otlp/exporter.rb, exporter/otlp/lib/opentelemetry/exporter/otlp/version.rb, exporter/otlp/test/opentelemetry/exporter/otlp/exporter_test.rb
The OTLP proto spec requires root spans to have an empty `parent_span_id` rather than an invalid span ID (all zero): https://github.com/open-telemetry/opentelemetry-proto/blob/30d237e1ff3ab7aa50e0922b5bebdd93505090af/opentelemetry/proto/trace/v1/trace.proto#L82-L84
=> fix: OTLP parent_span_id should be nil for root

README.md
Clarify beta status of tracing functionality. Shopify is starting to roll this out in production, and we think it is production-ready.
=> docs: beta

instrumentation/sinatra/lib/opentelemetry/instrumentation/sinatra/middlewares/tracer_middleware.rb, instrumentation/sinatra/test/opentelemetry/instrumentation/sinatra_test.rb
The previous attempt at this failed due to sinatra.route not having been set yet. This moves the logic for using sinatra.route to later in the process and only updates the span name if sinatra.route exists.
=> fix: set span name to sinatra.route

resource_detectors/lib/opentelemetry/resource/detectors/google_cloud_platform.rb, resource_detectors/test/opentelemetry/detectors/google_cloud_platform_test.rb, sdk/lib/opentelemetry/sdk/resources/constants.rb
I noticed this in JS, so I thought I'd fix it here also. There were two host name attributes: `host.name` and `host.hostname`. This PR removes the latter as per: https://github.com/open-telemetry/opentelemetry-specification/pull/838. The spec is pretty loose about the precedence to use when determining the `host.name` value. I chose the sequence: environment variable, gcp metadata hostname, Socket.gethostname. We can change that if there's a better ordering.
=> chore!: remove duplicate hostname resource attribute

.github/workflows/release-hook-on-open.yml, .toys/release/.data/templates/release-hook-on-open.yml.erb
Sync with upstream release script fixes.
This patch fixes the conventional commit linter. Previously, when a PR was opened from a fork and the commit message failed linting, the checker could not post details of the problem in a PR comment as intended, because the action's token didn't have sufficient permissions. Now we use a different trigger that runs in the base repo's context, thus giving the token enough permissions to write to the PR.
=> chore: Fix reporting of conventional commit lint issues

api/opentelemetry-api.gemspec, exporter/jaeger/opentelemetry-exporter-jaeger.gemspec, exporter/otlp/opentelemetry-exporter-otlp.gemspec, instrumentation/all/opentelemetry-instrumentation-all.gemspec, instrumentation/concurrent_ruby/opentelemetry-instrumentation-concurrent_ruby.gemspec, instrumentation/dalli/opentelemetry-instrumentation-dalli.gemspec, instrumentation/ethon/opentelemetry-instrumentation-ethon.gemspec, instrumentation/excon/opentelemetry-instrumentation-excon.gemspec, instrumentation/faraday/opentelemetry-instrumentation-faraday.gemspec, instrumentation/mysql2/opentelemetry-instrumentation-mysql2.gemspec, instrumentation/net_http/opentelemetry-instrumentation-net_http.gemspec, instrumentation/rack/opentelemetry-instrumentation-rack.gemspec, instrumentation/redis/opentelemetry-instrumentation-redis.gemspec, instrumentation/restclient/opentelemetry-instrumentation-restclient.gemspec, instrumentation/sidekiq/opentelemetry-instrumentation-sidekiq.gemspec, instrumentation/sinatra/opentelemetry-instrumentation-sinatra.gemspec, resource_detectors/opentelemetry-resource_detectors.gemspec, sdk/opentelemetry-sdk.gemspec
Adds several links to the gem pages on rubygems.org. Note: the documentation and changelog links point to the yardocs that are now being built to github pages.
=> chore: Add documentation, changelog, source, and issue links to gemspec metadata

api/lib/opentelemetry/trace/link.rb, api/lib/opentelemetry/trace/propagation/trace_context/text_map_injector.rb, api/lib/opentelemetry/trace/propagation/trace_context/trace_parent.rb, api/test/opentelemetry/trace/link_test.rb, api/test/opentelemetry/trace/propagation/trace_context/trace_parent_test.rb, exporter/jaeger/lib/opentelemetry/exporter/jaeger/encoder.rb, exporter/otlp/lib/opentelemetry/exporter/otlp/exporter.rb, sdk/lib/opentelemetry/sdk/trace/span.rb, sdk/lib/opentelemetry/sdk/trace/tracer.rb, sdk/test/opentelemetry/sdk/trace/tracer_test.rb
Assorted small changes from #440.
There is a single breaking change: `Link#context` -> `Link#span_context`.
=> fix!: assorted SpanContext fixes

sdk/lib/opentelemetry/sdk/trace/export/batch_span_processor.rb
... instead of half max queue size. This makes the trigger independent of the queue size. We're running with this in production and it has helped significantly reduce dropped spans.
=> fix: signal at batch_size

sdk/lib/opentelemetry/sdk/trace/export/batch_span_processor.rb, sdk/lib/opentelemetry/sdk/trace/export/simple_span_processor.rb
Addresses #397. As noted in that issue, there wasn't anything in the spec about the different scenarios in which to use simple vs. batch span processors, so I ended up making a spec PR for this as well: https://github.com/open-telemetry/opentelemetry-specification/pull/1135.
As of this writing, my spec PR has received one approval and there are no open questions or requested changes related to the differences between the two types of span processors. The documentation I'm submitting here is extracted from that PR.
=> Add documentation on usage scenarios for span processors

sdk/lib/opentelemetry/sdk/trace/span.rb, sdk/test/opentelemetry/sdk/trace/span_test.rb
[The spec states](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/api.md#isrecording)
> After a `Span` is ended, it usually becomes non-recording and thus `IsRecording` SHOULD consequently return false for ended Spans.
=> fix: SDK Span.recording? after finish

sdk/lib/opentelemetry/sdk/trace/samplers.rb, sdk/lib/opentelemetry/sdk/trace/samplers/parent_based.rb, sdk/lib/opentelemetry/sdk/trace/tracer.rb, sdk/test/opentelemetry/sdk/trace/samplers_test.rb, sdk/test/opentelemetry/sdk/trace/tracer_test.rb
Fixes #468 
I marked this as a breaking change for the SDK because we're changing the type expected by the samplers.
=> fix!: pass full Context to samplers

.toys/.data/releases.yml, common/.rubocop.yml, common/.yardopts, common/Gemfile, common/LICENSE, common/README.md, common/Rakefile, common/lib/opentelemetry-common.rb, common/lib/opentelemetry/common.rb, common/lib/opentelemetry/common/http.rb, common/lib/opentelemetry/common/http/client_context.rb, common/lib/opentelemetry/common/version.rb, common/opentelemetry-common.gemspec, common/test/opentelemetry/common/http_client_context_test.rb, common/test/test_helper.rb, instrumentation/all/Gemfile, instrumentation/net_http/lib/opentelemetry/instrumentation/net/http.rb, instrumentation/net_http/lib/opentelemetry/instrumentation/net/http/patches/instrumentation.rb, instrumentation/net_http/opentelemetry-instrumentation-net_http.gemspec, instrumentation/net_http/test/opentelemetry/instrumentation/net/http/instrumentation_test.rb
Partly addresses #443 and #284.
This adds an `opentelemetry-common` gem intended as a collection of helpers for common context propagation scenarios and for semantic conventions. To start, it includes HTTP client context helpers modelled on the Trace context helpers. It also uses these helpers in the Net::HTTP instrumentation.
I have not yet used the helpers in the Ethon, Excon, Faraday or RestClient instrumentation. I lack context (ha ha) for those gems.
=> feat: add common helpers

instrumentation/redis/README.md, instrumentation/redis/lib/opentelemetry/instrumentation/redis.rb, instrumentation/redis/lib/opentelemetry/instrumentation/redis/patches/client.rb, instrumentation/redis/test/opentelemetry/instrumentation/redis/instrumentation_test.rb, instrumentation/redis/test/opentelemetry/instrumentation/redis_test.rb
Fixes https://github.com/open-telemetry/opentelemetry-ruby/issues/443 by adding the requested Redis context propagation support.
Unlike the HTTP client context implementation, there is only one supported Redis client gem, so I've implemented the Redis context propagation support in the Redis instrumentation gem rather than in the common gem. There is clearly a lot of duplication - the code is identical to the HTTP context propagation. The next time we implement this pattern, we should extract the common functionality to reduce duplication.
Possible follow-ups for context propagation:
* MySQL
* Dalli
=> feat: Redis attribute propagation

exporter/otlp/lib/opentelemetry/exporter/otlp/exporter.rb, exporter/otlp/test/opentelemetry/exporter/otlp/exporter_test.rb
The OTLP exporter was raising on backoffs, this corrects the error and adds a test coverage.
=> fix: Remove unused kwarg from otlp exporter retry

sdk/lib/opentelemetry/sdk/trace/samplers.rb, sdk/lib/opentelemetry/sdk/trace/samplers/constant_sampler.rb, sdk/lib/opentelemetry/sdk/trace/samplers/result.rb, sdk/lib/opentelemetry/sdk/trace/samplers/trace_id_ratio_based.rb, sdk/lib/opentelemetry/sdk/trace/tracer.rb, sdk/test/opentelemetry/sdk/trace/samplers/result_test.rb, sdk/test/opentelemetry/sdk/trace/samplers_test.rb, sdk/test/opentelemetry/sdk/trace/tracer_test.rb
Fixes: #469 
A few notes:
- We now have to allocate an object for the `Result` on every call to `should_sample?`. This is unavoidable because the result has to wrap the tracestate from the parent context.
- I'll implement `Tracestate` in the API in a separate PR.
- This is a breaking change because it adds an extra required argument to `Result#initialize`.
=> fix!: allow samplers to modify tracestate

instrumentation/rack/Gemfile, instrumentation/rack/lib/opentelemetry/instrumentation/rack.rb, instrumentation/rack/test/opentelemetry/instrumentation/rack_test.rb, instrumentation/rack/test/test_helper.rb
Fixes namespacing on `Span::INVALID`
=> fix: rack current_span

instrumentation/mysql2/lib/opentelemetry/instrumentation/mysql2/patches/client.rb, instrumentation/mysql2/test/opentelemetry/instrumentation/mysql2/instrumentation_test.rb, instrumentation/redis/lib/opentelemetry/instrumentation/redis/patches/client.rb, instrumentation/redis/test/opentelemetry/instrumentation/redis/instrumentation_test.rb
See https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/semantic_conventions/database.md#connection-level-attributes
=> fix: semantic conventions db.type -> db.system

instrumentation/rails/Appraisals, instrumentation/rails/gemfiles/rails_5.2.gemfile, instrumentation/rails/gemfiles/rails_6.0.gemfile, instrumentation/rails/gemfiles/rails_6.1.gemfile, instrumentation/rails/test/opentelemetry/instrumentation/rails/patches/action_controller/metal_test.rb, instrumentation/rails/test/test_helpers/app_config.rb
Fixes appraisals to use the versions originally intended to be tested, also adds rails `6.1` to the appraisals.
=> fix: rails tests

api/lib/opentelemetry/instrumentation/registry.rb
Small fix to the output message from when instrumentation explodes on install.
=> fix: missing white space from install messages

.instrumentation_generator/instrumentation_generator.rb, .instrumentation_generator/templates/Appraisals, .instrumentation_generator/templates/CHANGELOG.md.tt, .instrumentation_generator/templates/Gemfile, .instrumentation_generator/templates/LICENSE, .instrumentation_generator/templates/Rakefile, .instrumentation_generator/templates/Readme.md.tt, .instrumentation_generator/templates/gemspec.tt, .instrumentation_generator/templates/lib/entrypoint.rb, .instrumentation_generator/templates/lib/instrumentation.rb.tt, .instrumentation_generator/templates/lib/instrumentation/instrumentation_name.rb.tt, .instrumentation_generator/templates/lib/instrumentation/instrumentation_name/instrumentation.rb.tt, .instrumentation_generator/templates/lib/instrumentation/instrumentation_name/version.rb.tt, .instrumentation_generator/templates/rubocop.yml.tt, .instrumentation_generator/templates/test/instrumentation.rb.tt, .instrumentation_generator/templates/test/test_helper.rb, .instrumentation_generator/templates/yardopts.tt, bin/instrumentation_generator
Usage `bin/instrumentation_generator amazing_gem`
```
MacBook-Pro ~/s/f/opentelemetry-ruby> bin/instrumentation_generator amazing_gem
create  instrumentation/amazing_gem/.rubocop.yml
create  instrumentation/amazing_gem/.yardopts
create  instrumentation/amazing_gem/Appraisal
create  instrumentation/amazing_gem/CHANGELOG.md
create  instrumentation/amazing_gem/Gemfile
create  instrumentation/amazing_gem/LICENSE
create  instrumentation/amazing_gem/opentelemetry-instrumentation-amazing_gem.gemspec
create  instrumentation/amazing_gem/Rakefile
create  instrumentation/amazing_gem/README.md
create  instrumentation/amazing_gem/lib/opentelemetry-instrumentation-amazing_gem.rb
create  instrumentation/amazing_gem/lib/opentelemetry/instrumentation.rb
create …
```
=> feat: Add instrumentation boilerplate generator

.instrumentation_generator/instrumentation_generator.rb
Missing `s`
```
~/s/f/o/i/http_client> be appraisal
Unable to locate 'Appraisals' file in the current directory.
```
=> fix: instrumentation gen type for appraisals

sdk/lib/opentelemetry/sdk/trace/export/batch_span_processor.rb
We're reporting negative dropped spans even when there is none.
=> fix: BSP dropped span buffer full reporting

api/lib/opentelemetry.rb, api/lib/opentelemetry/instrumentation/registry.rb, api/test/opentelemetry_test.rb, exporter/jaeger/lib/opentelemetry/exporter/jaeger/collector_exporter.rb, sdk/lib/opentelemetry/sdk.rb, sdk/lib/opentelemetry/sdk/configurator.rb, sdk/lib/opentelemetry/sdk/internal.rb, sdk/lib/opentelemetry/sdk/resources/resource.rb, sdk/lib/opentelemetry/sdk/trace/export/batch_span_processor.rb, sdk/lib/opentelemetry/sdk/trace/export/simple_span_processor.rb, sdk/lib/opentelemetry/sdk/trace/span.rb
Replaces #207 
Replaces #465 
Fixes #464 
Fixes #203 (maybe?)
This introduces a configurable error handling mechanism to the API, handles configuration errors by wrapping them in a `ConfigurationError` and passing it to the error handler, and validates attribute types when finishing an SDK span.
=> feat: Structured error handling

sdk/lib/opentelemetry/sdk/trace/config/trace_config.rb, sdk/lib/opentelemetry/sdk/trace/samplers/constant_sampler.rb, sdk/lib/opentelemetry/sdk/trace/samplers/parent_based.rb, sdk/lib/opentelemetry/sdk/trace/samplers/trace_id_ratio_based.rb, sdk/test/opentelemetry/sdk/trace/config/trace_config_test.rb
Fixes #525 and also implements `OTEL_SPAN_*_COUNT_LIMIT` environment variables.
Depends on #521.
Also needs tests.
=> fix: Implement SDK environment variables

sdk/lib/opentelemetry/sdk/trace/span.rb
This fixes a TODO in the codebase for a perf improvement that only works on Ruby 2.5 and above. We removed support for Ruby 2.4 awhile back, so we can use this enhancement now.
=> fix: remove incorrect TODO

api/lib/opentelemetry/trace.rb
Fix a warning reported in #533 by choosing a random number provider based on the implemented methods.
=> fix(api): Eliminate warning about Random::DEFAULT on Ruby 3.0

.github/workflows/ci.yml, common/test/opentelemetry/common/http_client_context_test.rb, instrumentation/excon/Appraisals, instrumentation/faraday/Appraisals, instrumentation/graphql/Appraisals, instrumentation/rails/Appraisals, instrumentation/redis/test/opentelemetry/instrumentation/redis_test.rb, instrumentation/ruby_kafka/Appraisals, instrumentation/ruby_kafka/test/opentelemetry/instrumentation/ruby-kafka/patches/producer_test.rb, instrumentation/sinatra/Appraisals, instrumentation/sinatra/gemfiles/sinatra_2.1.gemfile
Closes #533 
Caveats:
* Currently, the Ruby 3.0 test omits the otlp exporter, because google-protobuf is not yet compatible with Ruby 3.
* The Ruby 3.0 test also omits versions of ruby-kafka older than 1.3 because of an unexplained test failure. It's possible the libraries are incompatible with Ruby 3, but I'd like to get a separate opinion on that since I'm not familiar with ruby-kafka.
Notes:
* Updated Appraisals of excon, faraday, and graphql instrumentation to omit versions that run afoul of what appears to be a Ruby 3 regression (https://bugs.ruby-lang.org/issues/10499)
* Updated the Appraisal for instrumentation-rails to omit Rails 5.2 under Ruby 3 because of keyword argument compatibility.
* Updated the Appraisal of sinatra to use 2.1 instead of 2.0.7 because of Ruby 3 keyword …
=> chore: Add Ruby 3.0 to CI

instrumentation/all/Gemfile, instrumentation/all/lib/opentelemetry/instrumentation/all.rb, instrumentation/all/opentelemetry-instrumentation-all.gemspec
It would be nice if the release process could automatically update the `all` instrumentation gem so that this is not missed in the future.
Please cut a release (0.12.1?) after merging.
=> "all" gem is missing ruby_kafka

exporter/otlp/opentelemetry-exporter-otlp.gemspec
Some of the compiled *_pb.rb files included for OTLP exporter is having `add_file` method and its definition is available only from [google-protobuf >= 3.7.0](https://github.com/protocolbuffers/protobuf/blob/v3.7.0/ruby/ext/google/protobuf_c/defs.c#L2124)
```ruby
Google::Protobuf::DescriptorPool.generated_pool.build do
add_file("{path_to_proto_file}", :syntax => :proto3) do
...
end
end
```
`add_file` is currently used in the below files:
- https://github.com/open-telemetry/opentelemetry-ruby/blob/master/exporter/otlp/lib/opentelemetry/proto/collector/trace/v1/trace_service_pb.rb#L8
- https://github.com/open-telemetry/opentelemetry-ruby/blob/master/exporter/otlp/lib/opentelemetry/proto/common/v1/common_pb.rb#L7
- https://github.com/open-telemetry/opentelemetry-ruby/blob/master/exporter/otlp …
=> Fix protobuf version dependency

sdk/lib/opentelemetry/sdk/trace/export/batch_span_processor.rb, sdk/test/opentelemetry/sdk/trace/export/batch_span_processor_test.rb
This fixes several issues that I noticed when running Ruby 3.0 tests.
This call is redundant because worker threads go away in a forked child process. In fact, the presence of the call is causing the fork safety test to flake (https://github.com/open-telemetry/opentelemetry-ruby/runs/1642237548). AFAICT the sequence of events is this:
* BatchSpanProcessor initializes, and the worker thread starts up.
* The test stubs `Process.pid` (simulating a fork)
* If we're unlucky in the timing, the worker thread runs `reset_on_fork(restart_thread: false)` _at this point_. This causes `@pid` to update, but _not_ `@thread`. (Note that this would never happen in a real system because the forked child process would not run the worker thread, but it can happen in the test simulation.)
* Now, back in the …
=> fix(sdk): Fix several BatchSpanProcessor errors related to fork safety

instrumentation/rack/lib/opentelemetry/instrumentation/rack/middlewares/tracer_middleware.rb
I noticed this when testing an application with the rack instrumentation.
I'm not sure how prevalent a missing user agent would be, but this becomes noisy quickly in the event that it is omitted.
=> fix: Only include user agent when present

exporter/otlp/README.md, exporter/otlp/lib/opentelemetry/exporter/otlp/exporter.rb, exporter/otlp/test/opentelemetry/exporter/otlp/exporter_test.rb
This improves spec compliance for the OTLP exporter, based on recent changes to https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/protocol/exporter.md
This is a breaking change in several ways:
1. The `insecure:` argument to the initializer and the `OTEL_EXPORTER_OTLP_SPAN_INSECURE` and `OTEL_EXPORTER_OTLP_INSECURE ` environment variables are no longer supported.
2. The `endpoint:` argument and the `OTEL_EXPORTER_OTLP_SPAN_ENDPOINT` and `OTEL_EXPORTER_OTLP_ENDPOINT` environment variables used to expect a full URL without the scheme. They now expect a URL with the scheme but without the path.
3. The exporter implicitly and unconditionally appends `/v1/traces` to the URL.
4. The format of additional headers provided via the `OTEL_EXPORTER_OTLP_HEADERS` …
=> fix!: spec compliance for OTLP exporter

instrumentation/delayed_job/lib/opentelemetry/instrumentation/delayed_job/plugins/tracer_plugin.rb, instrumentation/delayed_job/test/opentelemetry/instrumentation/delayed_job/plugins/tracer_plugin_test.rb
When using DelayedJob with Mongo, the ID used in `messaging.message_id` is are not `Integer` type but `BSON::ObjectId`. This is not an allowed wire type for OTEL. To remedy this (and for potentially other DBs) I'm coercing message_id to string.
```
ERROR -- : OpenTelemetry error: invalid attribute value type BSON::ObjectId
```
=> fix: Delayed Job Instrumenter: coerce message ID to string

instrumentation/mongo/lib/opentelemetry/instrumentation/mongo/subscriber.rb, instrumentation/mongo/test/opentelemetry/instrumentation/mongo/subscriber_test.rb
In current Mongo Instrumenter, there are cases `db.statement` and `db.mongodb.collection` can be nil. Nil is not an allowed wire value type for OTEL, so it must be removed.
```
ERROR -- : OpenTelemetry error: invalid attribute value type NilClass
```
=> fix: Mongo Instrumenter: Do not send nil attributes

exporter/otlp/lib/opentelemetry/exporter/otlp/exporter.rb, exporter/otlp/test/opentelemetry/exporter/otlp/exporter_test.rb
A recent change to the otlp exporter unconditionally appends `/v1/trace` to the provided endpoint. This prevents the possibility of exporting spans to any other path using in-code configuration. This was likely due to a recent change in the spec that reads:
> Target to which the exporter is going to send spans or metrics. The endpoint MUST be a valid URL with scheme (http or https) and host, and MAY contain a port and path. A scheme of https indicates a secure connection. When using OTEL_EXPORTER_OTLP_ENDPOINT with OTLP/HTTP, exporters SHOULD follow the collector convention of appending the version and signal to the path (e.g. v1/traces or v1/metrics). The per-signal endpoint configuration options take precedence and can be used to override this behavior.
There is a general …
=> fix: conditionally append path to collector endpoint

exporter/otlp/lib/opentelemetry/exporter/otlp/exporter.rb, exporter/otlp/test/opentelemetry/exporter/otlp/exporter_test.rb
See https://github.com/open-telemetry/opentelemetry-ruby/pull/568#issuecomment-765101858
=> fix: OTLP path should be /v1/traces

sdk/lib/opentelemetry/sdk/trace/export/batch_span_processor.rb, sdk/test/opentelemetry/sdk/trace/export/batch_span_processor_test.rb
See https://github.com/open-telemetry/opentelemetry-specification/pull/1325
This is a breaking change because the named arguments to the OTLP initializer have changed, along with the environment variables for configuration.
=> fix!: Remove MILLIS from BatchSpanProcessor vars

exporter/jaeger/lib/opentelemetry/exporter/jaeger/encoder.rb, sdk/lib/opentelemetry/sdk/configurator.rb, sdk/lib/opentelemetry/sdk/resources/resource.rb, sdk/test/opentelemetry/sdk/configurator_test.rb, sdk/test/opentelemetry/sdk/resources/resource_test.rb
Fixes #518 and implements changes from https://github.com/open-telemetry/opentelemetry-specification/pull/1294.
Specifically, this exposes `OpenTelemetry::SDK::Resources::Resource.default` as a default resource to be attached to the tracer provider and ensures that this resource contains the default `service.name` attributes with the value `unknown_service`. The Jaeger exporter has been updated to use the service name from this default resource if the resource attached to spans does not contain the `service.name` attribute.
=> feat: provide default resource in SDK

common/lib/opentelemetry/common/utilities.rb, exporter/jaeger/lib/opentelemetry/exporter/jaeger/collector_exporter.rb, exporter/otlp/lib/opentelemetry/exporter/otlp/exporter.rb
Makes the `untraced` method available as part of common utils.
=> feat: add untraced wrapper to common utils

api/lib/opentelemetry/trace/span.rb, api/test/opentelemetry/trace/span_test.rb, sdk/lib/opentelemetry/sdk/trace/span.rb, sdk/test/opentelemetry/sdk/trace/span_test.rb
This implements the [optional attributes to `record_exception`](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md#record-exception) required by the spec.
=> feat: add optional attributes to record_exception

sdk/test/opentelemetry/sdk/configurator_test.rb
This has been annoying for some time. The caching in `OpenTelemetry::SDK::Resources::Resource.default` means that the attributes from the environment variable can stick around between tests.
=> fix: leaky test

sdk/lib/opentelemetry/sdk/resources/resource.rb, sdk/test/opentelemetry/sdk/resources/resource_test.rb
Bug reported in Gitter by @mat-rumian:
> Looks like setting service name by environment variable `export OTEL_RESOURCE_ATTRIBUTES=service.name=test` doesn't work - I'm getting `unknown_service`. (BatchSpanProcessor)
=> fix: allow env var override of service.name

resource_detectors/README.md
Reading the docs I caught an error in the README, so I did a fix to match the published gem.
=> docs: updated gem name to match gemspec

exporter/jaeger/README.md, exporter/jaeger/test/opentelemetry/exporters/jaeger/agent_exporter_test.rb, exporter/jaeger/test/opentelemetry/exporters/jaeger/collector_exporter_test.rb, exporter/otlp/README.md, exporter/otlp/test/opentelemetry/exporter/otlp/exporter_test.rb, sdk/lib/opentelemetry/sdk/trace/export/batch_span_processor.rb, sdk/lib/opentelemetry/sdk/trace/tracer_provider.rb, sdk/test/integration/global_tracer_configurations_test.rb, sdk/test/opentelemetry/sdk/configurator_test.rb, sdk/test/opentelemetry/sdk/trace/export/batch_span_processor_test.rb
This streamlines the SpanProcessor pipeline in the common case (a single non-noop processor), removing the (double) indirection through MultiSpanProcessor when only a single span processor is registered.
It also replaces the required `exporter:` keyword parameter to the BatchSpanProcessor initializer with a positional parameter. This aligns it with the SimpleSpanProcessor initializer and avoids a (probably common) mistake when switching between the BatchSpanProcessor and SimpleSpanProcessor. (e.g. #595).
=> fix!: streamline processor pipeline

api/lib/opentelemetry/instrumentation/base.rb, api/test/opentelemetry/instrumentation/base_test.rb, api/test/opentelemetry/instrumentation/registry_test.rb, instrumentation/dalli/lib/opentelemetry/instrumentation/dalli/instrumentation.rb, instrumentation/graphql/lib/opentelemetry/instrumentation/graphql/instrumentation.rb, instrumentation/mysql2/lib/opentelemetry/instrumentation/mysql2/instrumentation.rb, instrumentation/rack/lib/opentelemetry/instrumentation/rack/instrumentation.rb, instrumentation/rack/lib/opentelemetry/instrumentation/rack/middlewares/tracer_middleware.rb, instrumentation/redis/lib/opentelemetry/instrumentation/redis/instrumentation.rb, instrumentation/sidekiq/lib/opentelemetry/instrumentation/sidekiq/instrumentation.rb, sdk/test/opentelemetry/sdk/configurator_test.rb
During this weeks SIG I proposed adding a validation step of sorts to create a more structured interface for our instrumentation configuration.
This idea sparked from this comment chain https://github.com/open-telemetry/opentelemetry-ruby/pull/594#discussion_r568753846
=> feat: Add instrumentation config validation

sdk/Gemfile, sdk/lib/opentelemetry/sdk/configurator.rb, sdk/opentelemetry-sdk.gemspec, sdk/test/opentelemetry/sdk/configurator_test.rb
Fixes #412 and #403
Many of the supported propagators and exporters are required to be implemented external to the SDK, so this requires making assumptions about the structure of the external gems.
The `OTEL_TRACES_EXPORTER` env var is not especially useful for a couple of reasons:
1. The default span processor is not specified and there is no specified environment variable to select it. We defaulted to the `SimpleSpanProcessor` previously, and I've kept that default here, but that is rarely useful with any of the defined exporters.
2. We previously defaulted to `ConsoleSpanExporter`, but the specified default is OTLP, so we instead fall back to `ConsoleSpanExporter` if either an unsupported exporter is requested or a supported but unavailable exporter is requested. In either case, we log …
=> fix: OTEL_TRACES_EXPORTER and OTEL_PROPAGATORS

exporter/otlp/lib/opentelemetry/exporter/otlp/exporter.rb
The intention of this method is to allow users of the exporter to either
prepend or inherit from the class so that the exporter send_bytes
method can be traced, or wrapped with any other customer methods.
Two example use cases:
- Tracing the trace pipeline itself, this would allow for the an end to end tracing of the exporter/tracing pipeline
- In some applications we have a requirement of explicitly permitting URLs that are allowed to be communicated via HTTP.  In those applications we will need this hook to wrap the `send_byes` http call with an allow method that permits the network call.
=> feat: add otlp exporter hooks

instrumentation/net_http/lib/opentelemetry/instrumentation/net/http/patches/instrumentation.rb, instrumentation/net_http/opentelemetry-instrumentation-net_http.gemspec, instrumentation/net_http/test/opentelemetry/instrumentation/net/http/instrumentation_test.rb
Followup to a discussion regarding connect spans https://github.com/open-telemetry/opentelemetry-ruby/pull/508#issuecomment-777152748
=> feat: add Net::HTTP#connect tracing

instrumentation/faraday/lib/opentelemetry/instrumentation/faraday/middlewares/tracer_middleware.rb, instrumentation/faraday/test/opentelemetry/instrumentation/faraday/middlewares/tracer_middleware_test.rb
We noticed the error OpenTelemetry error: invalid attribute value type NilClass appearing frequently in our logs after the addition of Faraday instrumentation to our project. This fix will skip the addition of attribute if it is nil in the response.
=> fix: Include http.status_text only if reason_phrase is in the response

sdk/lib/opentelemetry/sdk/trace/export/batch_span_processor.rb, sdk/test/opentelemetry/sdk/trace/export/batch_span_processor_test.rb
This adds graceful handling for when creating a new thread raises.  We observed this scenario with an application that was improperly terminating sidekiq which resulted in a `ThreadError`.
mperham/sidekiq#4029
mperham/sidekiq#4738
=> fix: add thread error handling to the BSP

.toys/.data/releases.yml
https://github.com/open-telemetry/opentelemetry-ruby/runs/1931000292
```
Error: Version file /home/runner/work/opentelemetry-ruby/opentelemetry-ruby/instrumentation/http/lib/opentelemetry/instrumentation/http/version.rb for gem opentelemetry-instrumentation-http didn't define OpenTelemetry::Instrumentation::Http::VERSION
```
=> fix: http release yml entry

.instrumentation_generator/templates/Readme.md.tt, README.md, api/README.md, common/README.md, exporter/jaeger/README.md, exporter/otlp/README.md, instrumentation/active_model_serializers/README.md, instrumentation/all/README.md, instrumentation/concurrent_ruby/README.md, instrumentation/dalli/README.md, instrumentation/delayed_job/README.md, instrumentation/ethon/README.md, instrumentation/excon/README.md, instrumentation/faraday/README.md, instrumentation/graphql/README.md, instrumentation/http/README.md, instrumentation/http_client/README.md, instrumentation/mongo/README.md, instrumentation/net_http/README.md, instrumentation/rack/README.md, instrumentation/rails/README.md, instrumentation/redis/README.md, instrumentation/restclient/README.md, instrumentation/ruby_kafka/README.md, instrumentation/sidekiq/README.md, instrumentation/sinatra/README.md, propagator/b3/README.md, resource_detectors/README.md, sdk/README.md
I've created a Slack channel in the CNCF Slack and added a badge here. I've also enabled GitHub Discussions for this repo and directed folks there for discussions. Once this merges, I'll post in Gitter and delete the channel there after a week.
=> docs: Replace Gitter with GitHub Discussions

README.md, instrumentation/README.md
Not sure if this is the final state of this but it seemed like a good start. After thinking about it I opted against listing all the instrumentation libraries in any READMEs: This seems brittle and I'd imagine most users should be able to navigate Github and/or the repository on their own with a quick pointer. But I'm definitely open to other thoughts if we think there are ways this documentation can be clearer.
=> docs: Add more documentation around instrumentation libraries.

rakelib/update_registry_instrumentation.rake
Here's a quick draft of a Rake task to make it easy to keep our registry entries up-to-date. This is sort of quick-and-dirty code -- one large Rake task, no tests -- but I'm not sure how much this matters given that this is just a dev script. I can clean that up if we think it's worth it right now.
There's a bit of relying on common patterns in our instrumentation gems, hence the string parsing. Obviously that can be brittle too, but none of these errors would ever affect an end user's system, and the presence of this Rake task does not preclude the current option of falling back to just submitting a PR to opentelemetry.io by hand.
To see what this Rake task produces, you can compare the results here: https://github.com/open-telemetry/opentelemetry.io/compare/main...fhwang:update-ruby-inst …
=> docs: Add Rake task for updating instrumentations in opentelemetry.io.

instrumentation/rails/opentelemetry-instrumentation-rails.gemspec, rakelib/update_registry_instrumentation.rake
I burned a few cycles because our Rails instrumentation gemspec was missing a repo link, which meant that my PR to opentelemetry.io had some fairly opaque error messages. This PR tightens the feedback loop on this by having the Rake task raise a clear error if that happens in the future.
=> Improve registry rake task.

exporter/otlp/lib/opentelemetry/exporter/otlp/exporter.rb
We saw errors when the OTel endpoint was invalid or unreachable causing our deployments to fail. This PR simply adds the rescuing of SocketError.
=> fix: rescue socket err in otlp exporter to prevent failures when unable to connect

resource_detectors/lib/opentelemetry/resource/detectors/google_cloud_platform.rb, resource_detectors/test/opentelemetry/detectors/google_cloud_platform_test.rb, sdk/lib/opentelemetry/sdk/resources/constants.rb
We observed in production that we were no longer capturing the node name in a k8s deployment, this adds it back under the proper key.
Also updated the k8s constants to line up with the spec https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/resource/semantic_conventions/k8s.md
=> feat: add k8s node to gcp resource detector

common/lib/opentelemetry/common/utilities.rb, instrumentation/dalli/lib/opentelemetry/instrumentation/dalli/utils.rb, instrumentation/redis/lib/opentelemetry/instrumentation/redis/utils.rb
Moves duplicate truncate method definitions into the common gem.
=> refactor: Extract duplicate truncate definitions

instrumentation/lmdb/lib/opentelemetry/instrumentation/lmdb/instrumentation.rb, instrumentation/lmdb/lib/opentelemetry/instrumentation/lmdb/patches/database.rb, instrumentation/lmdb/lib/opentelemetry/instrumentation/lmdb/patches/environment.rb, instrumentation/lmdb/test/instrumentation/lmdb/instrumentation_test.rb, instrumentation/lmdb/test/instrumentation/lmdb/patches/database_test.rb
Add a config option to set a `peer.service` attribute to LMDB in the same way we do redis, dalli, mysql, etc..
=> feat: Add peer_service config to lmdb

api/lib/opentelemetry/context/propagation/rack_env_getter.rb, api/test/opentelemetry/context/propagation/rack_env_getter_test.rb
While looking over #564 I found an issue with the RackEnvGetter where the `keys` method was returning a handful of nil entries, which caused breakage while processing baggage. This is because `String#downcase!` and `String#upcase!` only return a value if the string was modified. This PR fixes that issue. It also updates the `get` method to look for the original key if it wasn't transformed. This wasn't a bug that I ran into, but as I was writing tests it occurred to me that it is a fallback that we'd want.
=> fix: handle rack env getter edge cases

sdk/lib/opentelemetry/sdk/baggage/manager.rb, sdk/test/opentelemetry/sdk/baggage/manager_test.rb
The API defines a `build` helper method that was named `build_context` in the SDK implementation.
This change renames the SDK to make it consistent with the API.
=> fix: Update SDK BaggageManager to match API

instrumentation/mysql2/lib/opentelemetry/instrumentation/mysql2/patches/client.rb, instrumentation/mysql2/test/opentelemetry/instrumentation/mysql2/instrumentation_test.rb, instrumentation/redis/lib/opentelemetry/instrumentation/redis/patches/client.rb, instrumentation/redis/test/opentelemetry/instrumentation/redis/instrumentation_test.rb
The [database semantic conventions](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/database.md) have evolved slightly. This PR tries to catch up. Specifically:
- `db.url` has been removed - its information was redundant anyway
- `db.instance` -> `db.name` for MySQL
- `db.instance` -> `db.redis.database_index` for Redis
=> fix: update DB semantic conventions

sdk/lib/opentelemetry/sdk/configurator.rb, sdk/test/opentelemetry/sdk/configurator_test.rb
The console span exporter can be useful for development and quick debug sessions. This PR adds a `console` option for the `OTEL_TRACES_EXPORTER` environment variable that will wire up a `SimpleSpanProcessor` with a `ConsoleSpanExporter`.
=> feat: add console option for OTEL_TRACES_EXPORTER

instrumentation/rack/lib/opentelemetry/instrumentation/rack/middlewares/tracer_middleware.rb, instrumentation/rack/test/opentelemetry/instrumentation/rack/middlewares/tracer_middleware_test.rb
This arose from needing a way to more flexibly quantize URLs that have params in the path. This change passes env to the configured `url_quantization` callable, allowing for access to things like `REQUEST_METHOD` that can be used to lower cardinality in these cases.
=> feat!: pass env to url quantization rack config to allow more flexibility

.instrumentation_generator/instrumentation_generator.rb, .instrumentation_generator/templates/test/.rubocop.yml, .instrumentation_generator/templates/test/instrumentation.rb.tt
The generator was not adding a rubocop config file to the test directory.
=> fix: Add missing rubocop file to test directory

instrumentation/rack/lib/opentelemetry/instrumentation/rack/instrumentation.rb, instrumentation/rack/lib/opentelemetry/instrumentation/rack/middlewares/tracer_middleware.rb, instrumentation/rack/test/opentelemetry/instrumentation/rack/middlewares/tracer_middleware_test.rb
This PR adds a configuration option to Rack instrumentation that allows you to configure with a callable that accepts `env` and does not trace any requests in which the callable returns true.  This allows more flexibility in filtering out requests to be untraced than the existing config option of `untraced_endpoints`.
=> feat: add rack instrumentation config option to accept callable to filter requests to trace

api/lib/opentelemetry/trace/span.rb, api/test/opentelemetry/trace/span_test.rb, sdk/lib/opentelemetry/sdk/trace/span.rb, sdk/test/opentelemetry/sdk/trace/span_test.rb
See: https://github.com/open-telemetry/opentelemetry-specification/pull/1473
This is optional, however I think it is useful both for convenience and for performance reasons (adding multiple attributes only requires taking the lock and trimming attributes once vs N times).
=> feat: Span#add_attributes

instrumentation/rails/README.md, instrumentation/rails/lib/opentelemetry/instrumentation/rails/instrumentation.rb, instrumentation/rails/lib/opentelemetry/instrumentation/rails/patches/action_controller/metal.rb, instrumentation/rails/test/opentelemetry/instrumentation/rails/patches/action_controller/metal_test.rb
The [spec](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/http.md#http-server-semantic-conventions) says:
> Given an inbound request for a route (e.g. "/users/:userID?") the name attribute of the span SHOULD be set to this route. If the route does not include the application root, it SHOULD be prepended to the span name.
> 
> If the route cannot be determined, the name attribute MUST be set as defined in the general semantic conventions for HTTP.
Some exporters need more information to provide useful insights to the user,
so add `http.route` could make more easily convert traces to the final destination.
My current case is using Datadog: The [exporter](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/ma …
=> feat: added http.route in rails instrumentation to match the spec

docker-compose.yml, examples/http/Gemfile.lock
Leaving OTEL_TRACES_EXPORTER unspecified was making the sample
application look for the default OTLP exporter instead of the console exporter.
=> fix: HTTP example uses the console exporter.

.toys/release/.lib/release_utils.rb, .toys/release/retry.rb, .toys/yardoc.rb
This is an attempt to fix release #662.
The theory is that something changed in recent bundler 2.2 releases that is breaking the Toys-Bundler integration. We'll try to work around that by invoking Bundler directly. And we'll also need a way to retry a release from a specific SHA, since currently `toys release retry` works from the original release PR's merge point.
=> chore: Attempt to fix bundler integration in releases, and allow retries from arbitrary SHAs

.toys/release/retry.rb
Need this to allow the `--skip-checks` hack to work properly in release retry. (I'm doing the release retry off a branch from the 0.16.0 release point so that we don't pick up subsequent commits, but non-main branches don't have github checks right now, and we don't have a mechanism yet to support release branches, so we need to be able to disable the check.)
=> chore: Omit github checks when passing --skip-checks to release retry

.toys/release/retry.rb
Hating git today.
If releasing from a different SHA than the merge commit for the release PR, we still need to make sure that two commits are fetched from the merge commit (because we need the diff). So we actually have to fetch twice: the merge SHA and the release SHA.
=> chore: Ensure the merge commit, the previous commit, and the release commit are fetched

.toys/release/retry.rb
Now git is just being mean to me.
Apparently, if you git fetch with a depth, and then fetch again with depth that partially overlaps the first, you'll lose history edges between the overlap region and the non-overlap region. Since we care about history from merge_sha, make sure that fetch happens last. And since we don't care about history from release_sha, reduce its depth to 1. (And if release_sha and merge_sha are the same, then the second fetch will overwrite the first, which is fine; we just need to make sure we end up with depth=2 from merge_sha.)
=> chore: Prevent release fetch from clobbering the merge fetch

api/lib/opentelemetry/instrumentation/base.rb, api/test/opentelemetry/instrumentation/base_test.rb
To improve the ergonomics of adding first party instrumentation we should
return a noop tracer when the instrumentation has not been installed.
This PR has come up now that I've started adding first party instrumentation directly into gems.  As discussed at a prior SIG there is value that comes with using the base instrumentation class to gain access to a named tracer, as well as add the instrumented library to the registry.
In the case where the instrumentation is never installed you would having to conditionally check for the presence of a tracer.  This change allows those who are instrumenting their library to simply add the trace points using the `Instrumention.instance.tracer` handle indifferently.
=> feat: default noop tracer for instrumentation

instrumentation/http/lib/opentelemetry/instrumentation/http/instrumentation.rb
Unfortunate error here, the install hook makes a lot of noise as a result and will raise errors as the gem is partially patched with no tracer available.  We require the patches as part of the test setup so this one slipped by.
=> Fix: HTTP instrumentation missing require

docker-compose.yml, instrumentation/mongo/README.md, instrumentation/mongo/example/Gemfile, instrumentation/mongo/example/mongo.rb
Fixed a bad gem name, and removed the docker-compose container for the
example, which was adding little value.
=> fix: Fix Mongo instrumentation example.

instrumentation/http/lib/opentelemetry/instrumentation/http/instrumentation.rb, instrumentation/http/opentelemetry-instrumentation-http.gemspec, instrumentation/http/test/instrumentation/http/instrumentation_test.rb, instrumentation/http/test/test_helper.rb
My app apparently defines `::HTTP` without using the HTTP gem, so I see this error:
```
OpenTelemetry error: Instrumentation: OpenTelemetry::Instrumentation::HTTP unhandled exception during install:
...
uninitialized constant HTTP::Client
```
=> HTTP instrumenter should check for gem presence

instrumentation/rails/example/trace_request_demonstration.ru
The example works just fine with the version of rails released to
rubygems (currently 6.1.3.1) - there's no explicit need to use a git
dependency here. At present, this example is actually broken because the
rails repo changed their `master` branch to `main` - see #700.
=> Fix rails example by not using `rails` from git

instrumentation/rails/lib/opentelemetry/instrumentation/rails/railtie.rb
The current insertion point is after some important middlewares
like the ActionDispatch::Static.
That is making us missing some traces,
so I changed the insert to the first position
We are starting to test the OTel in production to remove Datadog. After the deployment, we saw a big difference in requests:
Datadog version:
OTel version:
After some research, I found the problem in the current position of the ` TracerMiddleware`. The stack looks like that:
```
[0] = {Class} Datadog::Contrib::Rack::TraceMiddleware
[1] = {Class} Rack::Cors
[2] = {Class} SecureHeaders::Middleware
[3] = {Class} Rack::Sendfile
[4] = {Class} ActionDispatch::Static
[5] = {Class} ActionDispatch::Executor
[6] = {ActiveSupport::Cache::Strategy::LocalCache::Middleware} …
```
=> fix: updated rack middleware position to zero

sdk/lib/opentelemetry/sdk/trace/config/trace_config.rb, sdk/lib/opentelemetry/sdk/trace/span.rb, sdk/test/opentelemetry/sdk/trace/config/trace_config_test.rb, sdk/test/opentelemetry/sdk/trace/span_test.rb
We were noticing some exceptionally large spans failing to be exported due to nginx error:
`client intended to send too large body`
It turned out to be due to a case in which large event attributes were being added to spans when exceptions occured.  This PR adds support for configurable truncation of span attribute values (via `OTEL_RUBY_SPAN_ATTRIBUTE_VALUE_LENGTH_LIMIT ` env variable). The default is to not truncate attribute values and the minimum is 32, following the discussion in [this open spec PR](https://github.com/open-telemetry/opentelemetry-specification/pull/1130).
=> feat: Add configurable truncation of span and event attribute values 

instrumentation/base/lib/opentelemetry/instrumentation/registry.rb, instrumentation/base/test/instrumentation/registry_test.rb
When auto-instrumention classes are declared but cannot be loaded, the registry will report an error to logger
and then proceed with the installation.
Before:
```
Could not install OpenTelemetry::Instrumentation::Faraday because it was not found
OpenTelemetry error: unexpected configuration error due to undefined method `name' for nil:NilClass - OpenTelemetry::SDK::ConfigurationError
```
After:
```
Could not install OpenTelemetry::Instrumentation::Faraday because it was not found
```
=> fix: missing instrumentation classes during configuration

exporter/jaeger/lib/opentelemetry/exporter/jaeger/encoder.rb, exporter/jaeger/test/opentelemetry/exporters/jaeger/encoder_test.rb
A link's trace_id was being indexed at the end of the string rather than the
middle which was causing it to return nil and the exporter to throw an
undefined method exception when trying to convert nil into a int64:
```
undefined method '<' for nil:NilClass
```
=> fix: index a link trace_id in middle rather than end

instrumentation/redis/example/redis.rb, instrumentation/redis/lib/opentelemetry/instrumentation/redis/patches/client.rb, instrumentation/redis/lib/opentelemetry/instrumentation/redis/utils.rb, instrumentation/redis/test/opentelemetry/instrumentation/redis/instrumentation_test.rb, instrumentation/sidekiq/test/opentelemetry/instrumentation/sidekiq/patches/launcher_test.rb
Fixes #197.
I've opted to change the span names for pipeline requests to a concatenation of the Redis commands, i.e. `GET SET INCR`. This seems like it's more inline with [what the spec recommends](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md#span) than simply `pipeline`:
> The span name SHOULD be the most general string that identifies a (statistically) interesting class of Spans, rather than individual Span instances while still being human-readable.
=> fix: Instrument Redis more thoroughly by patching Client#process.

exporter/otlp/lib/opentelemetry/exporter/otlp/exporter.rb
The Net::HTTP client has a few more errors that need to be caught by the OTLP exporter or it will crash if the upstream agent/collector is temporarily unavailable.
You can simulate one of the SystemCallErrors, Errno::ECONNREFUSED by restarting a local OpenTelemetry collector while an app is trying to export spans to it. Without this change the exporter will crash, but with this change the exporter should recover when the collector becomes available again.
=> fix: rescue missed otlp exporter network errors

instrumentation/redis/README.md, instrumentation/redis/lib/opentelemetry/instrumentation/redis/instrumentation.rb, instrumentation/redis/lib/opentelemetry/instrumentation/redis/utils.rb, instrumentation/redis/test/opentelemetry/instrumentation/redis/instrumentation_test.rb, instrumentation/redis/test/opentelemetry/instrumentation/redis/utils_test.rb
This change introduces an option for the Redis instrumentation that will obfuscate all arguments in the db.statement attribute.
The purpose of this change is to give clients the option to hide potentially sensitive information such as personally identifiable
information. This is similar to changes that have already been made to the mysql and pg instrumentation.
=> feat: option to obfuscate redis arguments

instrumentation/mysql2/CHANGELOG.md, instrumentation/mysql2/lib/opentelemetry/instrumentation/mysql2/patches/client.rb
One of our users reported some log spam during migrations on their application.
It looks like we're expecting a `db.name` to be present when there might not be one available.
```
E, [2021-05-05T15:02:17.437321 #55630] ERROR -- : OpenTelemetry error: invalid span attribute value type NilClass for key 'db.name' on span 'set names'
E, [2021-05-05T15:02:17.440246 #55630] ERROR -- : OpenTelemetry error: invalid span attribute value type NilClass for key 'db.name' on span 'create database'
```
=> Fix: Nil value for db.name attribute

instrumentation/mongo/CHANGELOG.md, instrumentation/mongo/test/opentelemetry/instrumentation/mongo/subscriber_test.rb
>  1) Failure:
OpenTelemetry::Instrumentation::Mongo::Subscriber::with LDAP/SASL authentication::which fails#test_0001_produces spans for command and authentication [/__w/opentelemetry-ruby/opentelemetry-ruby/instrumentation/mongo/test/opentelemetry/instrumentation/mongo/subscriber_test.rb:360]:
Expected /mechanism.+PLAIN.+\(2\)/ to match "Received authentication for mechanism PLAIN which is unknown or not enabled (334)".
>
>37 runs, 136 assertions, 1 failures, 0 errors, 0 skips
W, [2021-05-11T02:20:55.694142 #3731]  WARN -- : MONGODB | Failed to authenticate to mongodb:27017: Mongo::Auth::Unauthorized: User plain_user (mechanism: plain) is not authorized to access otel_test (auth source: otel_test, used mechanism: PLAIN, used server: mongodb:27017 (STANDALONE)): Received authentication …
=> fix: Mongodb test asserting error message

examples/http/client.rb, instrumentation/excon/CHANGELOG.md, instrumentation/excon/lib/opentelemetry/instrumentation/excon/middlewares/tracer_middleware.rb, instrumentation/faraday/CHANGELOG.md, instrumentation/faraday/lib/opentelemetry/instrumentation/faraday/middlewares/tracer_middleware.rb, instrumentation/faraday/test/opentelemetry/instrumentation/faraday/middlewares/tracer_middleware_test.rb, instrumentation/rack/CHANGELOG.md, instrumentation/rack/lib/opentelemetry/instrumentation/rack/middlewares/tracer_middleware.rb, instrumentation/rack/test/opentelemetry/instrumentation/rack/middlewares/tracer_middleware_test.rb, instrumentation/restclient/CHANGELOG.md, instrumentation/restclient/lib/opentelemetry/instrumentation/restclient/patches/request.rb, instrumentation/sinatra/CHANGELOG.md, instrumentation/sinatra/lib/opentelemetry/instrumentation/sinatra/middlewares/tracer_middleware.rb, instrumentation/sinatra/test/opentelemetry/instrumentation/sinatra_test.rb
The `http.status_text` attribute was removed from the spec and so we should too https://github.com/open-telemetry/opentelemetry-specification/pull/972
Closes: https://github.com/open-telemetry/opentelemetry-ruby/issues/748
=> Remove http status text attribute

exporter/jaeger/README.md, exporter/jaeger/lib/opentelemetry/exporter/jaeger/collector_exporter.rb, exporter/jaeger/test/opentelemetry/exporters/jaeger/collector_exporter_test.rb
This change covers adding configuration to the Jaeger `CollectorExporter` to support exporting to Collectors that use self-signed certificates or any certificate chain that can't be verified by Ruby's openssl implementation.
It works by passing the configuration parameter onto the `Jaeger::HTTPClientTransport` class.
A similar implementation could be added for the other HTTP based exporters.
I'm a bit unsure about passing the verify mode in as an envvar in its current form, so I'm keen for feedback on this. I believe this is the most correct approach as the flag are meant to be combined together using union operations (e.g. `VERIFY_PEER | VERIFY_FAIL_IF_NO_PEER_CERT`). However, this might not be obvious and I've not been able to find a reliable reference for this.
=> feat: export to jaeger collectors w/ self-signed certs

README.md
https://github.com/open-telemetry/community/blob/main/community-membership.md#community-membership
Todo:
=> chore: make Robert a maintainer

instrumentation/redis/CHANGELOG.md, instrumentation/redis/lib/opentelemetry/instrumentation/redis/patches/client.rb
Splitting out a small cleanup PR prior to pushing up a refactor of the utils code for redis.
=> refactor: simplify redis attribute assignment

exporter/otlp/README.md
**Description:**
The legacy gRPC port(55680) in OTLP Receiver will be disabled in OTel Collector before the collector GA.
This CR replaced all gRPC port occurrences from `55680` to `4317` in this repo.
**Link to tracking Issue:** 
https://github.com/open-telemetry/opentelemetry-collector/issues/2565
=> Remove the OTLP receiver legacy gRPC port(55680) references

exporter/otlp/README.md, exporter/otlp/lib/opentelemetry/exporter/otlp/exporter.rb, exporter/otlp/test/opentelemetry/exporter/otlp/exporter_test.rb
This change covers adding configuration to the OTLP Exporter
to support exporting to Collectors that have certificates that can't be
verified by OpenSSL.
This approach is copied from the similar change for the Jaeger
CollectorExporter:
https://github.com/open-telemetry/opentelemetry-ruby/pull/743
=> feat: add a SSL verify mode option for the OTLP exporter

instrumentation/rails/lib/opentelemetry/instrumentation/rails/railtie.rb
PR #699 was opened to place the rack middleware at the very first position. However, it is using `app.middleware.insert_after(0` which has the effect of inserting at the second spot in the chain instead of the first. This updates it to `app.middleware.insert_before(0` to have the originally intended effect
=> Updated rack middleware position to zero

instrumentation/redis/CHANGELOG.md, instrumentation/redis/lib/opentelemetry/instrumentation/redis/instrumentation.rb, instrumentation/redis/lib/opentelemetry/instrumentation/redis/patches/client.rb, instrumentation/redis/test/opentelemetry/instrumentation/redis/patches/client_test.rb
Allows users to configure this instrumentation library to not trace root redis spans.  
We have observed quite a few applications with various background processes generating large volumes of single span traces for redis calls.  These traces provide no context into the work being done.  While the better goal would be to identify the sources of these spans and add context to them, this provides a less whack-a-mole style approach.
=> feat: Allow disabling of redis root spans

.instrumentation_generator/instrumentation_generator.rb, .instrumentation_generator/templates/gemspec.tt, .instrumentation_generator/templates/lib/instrumentation/instrumentation_name.rb.tt, .instrumentation_generator/templates/lib/instrumentation/instrumentation_name/instrumentation.rb.tt, .instrumentation_generator/templates/rubocop.yml.tt, .instrumentation_generator/templates/test/instrumentation.rb.tt
The instrumentation generator was getting a little out of date, so this just a few small updates.
=> fix: update instrumentation gen for base extraction

propagator/ottrace/lib/opentelemetry/propagator/ottrace/text_map_propagator.rb, propagator/ottrace/test/opentelemetry/propagator/ottrace/text_map_propagator_test.rb
This change allows systems that generate uppercase hexadecimal values to properly propagate OTTrace context.
=> fix: Support Case Insensitive Trace and Span IDs

exporter/otlp/lib/opentelemetry/exporter/otlp/exporter.rb, exporter/otlp/test/opentelemetry/exporter/otlp/exporter_test.rb
```
gems/opentelemetry-exporter-otlp-0.18.0/lib/opentelemetry/exporter/otlp/exporter.rb:338:in `method_missing': "\xC3" from ASCII-8BIT to UTF-8 (Encoding::UndefinedConversionError)
from gems/opentelemetry-exporter-otlp-0.18.0/lib/opentelemetry/exporter/otlp/exporter.rb:338:in `as_otlp_any_value'
from gems/opentelemetry-exporter-otlp-0.18.0/lib/opentelemetry/exporter/otlp/exporter.rb:331:in `as_otlp_key_value'
from gems/opentelemetry-exporter-otlp-0.18.0/lib/opentelemetry/exporter/otlp/exporter.rb:294:in `block (2 levels) in as_otlp_span'
from gems/opentelemetry-exporter-otlp-0.18.0/lib/opentelemetry/exporter/otlp/exporter.rb:294:in `each'
from gems/opentelemetry-exporter-otlp-0.18.0/lib/opentelemetry/exporter/otlp/exporter.rb:294:in `map'
from …
```
=> fix: handle OTLP exporter encoding exceptions

.gitignore
Twice now I have committed a `.ruby-version` in my PRs, and so I have decided "never again". The `.ruby-version` file is only needed if you're using some kind of ruby version manager like `rbenv`, and is otherwise unneeded in this project.
=> chore: Add .ruby-version to .gitignore

instrumentation/base/lib/opentelemetry/instrumentation/registry.rb, sdk/lib/opentelemetry/sdk.rb, sdk/lib/opentelemetry/sdk/configurator.rb, sdk/lib/opentelemetry/sdk/forwarding_logger.rb, sdk/test/opentelemetry/sdk/configurator_test.rb
Allows controlling the severity of the opentelemetry log messages emitted independently of the logger supplied.
This still allows for a user to override the `OpenTelemetry.logger` entirely via the accessor `OpenTelemetry.logger =`, if you wish to supply a logger and still respect the `OTEL_LOG_LEVEL` supplied environment variable this is done through the configuration.
```rb
OpenTelemetry::SDK.configure { |c| c.logger = Logger.new(....) }
```
=> feat: allow disabling of install messages

sdk/test/opentelemetry/sdk/trace/tracer_provider_test.rb
The logger was sometimes receiving a debug message from the tracer provider
when it was being upgraded.  Setting the log level to warn remedies that
as the test is concerned with not receiving a warning log.
=> fix: flakey tracer provider test

api/lib/opentelemetry/baggage/propagation/text_map_propagator.rb
Received reports from users getting log messages indicating that the text map propagator was raising when trying to extract.
`Error extracting W3C baggage: undefined method `gsub' for nil:NilClass`
=> fix: return early if carrier is nil

api/lib/opentelemetry/context.rb, api/test/opentelemetry/context_test.rb
Moves the `attach` and `detach` methods from private instance methods to public global methods
https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/context/context.md
Related: https://github.com/open-telemetry/opentelemetry-ruby/pull/796/files#r647055849
=> fix: update context to match spec

propagator/xray/lib/opentelemetry/propagator/xray/text_map_propagator.rb, propagator/xray/test/text_map_propagator_test.rb
This is in reference to: 
https://github.com/open-telemetry/opentelemetry-ruby/issues/832
=> Fix: XRay propagator null exception

instrumentation/all/CHANGELOG.md, instrumentation/all/lib/opentelemetry/instrumentation/all/version.rb
Just dancing around the release tools here.  Rolling back the version file, and remove the changelog entry so I can create a release for 0.19.0
https://github.com/open-telemetry/opentelemetry-ruby/pull/836#issuecomment-867870454
```
Failed to release opentelemetry-instrumentation-all 0.19.0:
The first changelog entry in instrumentation/all/CHANGELOG.md isn't for version 0.19.0.
It should start with:
v0.19.0 / 2021-06-24
But it actually starts with:
Unreleased
```
https://github.com/open-telemetry/opentelemetry-ruby/actions/runs/969317633
=> fix: broken instrumentation all release

instrumentation/active_job/lib/opentelemetry/instrumentation/active_job/patches/active_job_callbacks.rb, instrumentation/active_job/opentelemetry-instrumentation-active_job.gemspec, instrumentation/active_job/test/instrumentation/active_job/patches/active_job_callbacks_test.rb, instrumentation/active_job/test/test_helper.rb
#805 removed the ability to call `OpenTelemetry::Trace::Status.new` in favor of class level helper methods like `OpenTelemetry::Trace::Status.error`
This PR updates the usage of `OpenTelemetry::Trace::Status` within active_job instrumentation to conform with the new API as well as writes tests for the exception handling codepaths
=> Update active-job gem for rc2 Trace::Status syntax

exporter/otlp/lib/opentelemetry/exporter/otlp/exporter.rb, exporter/otlp/test/opentelemetry/exporter/otlp/exporter_test.rb
Let's be kind to different error handlers and encode the value before passing it in, instead of assuming it can handle it.
=> fix: otlp encoding exceptions again

instrumentation/active_job/lib/opentelemetry/instrumentation/active_job/patches/base.rb, instrumentation/active_job/test/instrumentation/active_job/patches/active_job_callbacks_test.rb, instrumentation/active_job/test/test_helper.rb
Ruby 2.7 / 3.0 changes the way that keyword args work: see [Separation of positional and keyword arguments in Ruby 3.0](https://www.ruby-lang.org/en/news/2019/12/12/separation-of-positional-and-keyword-arguments-in-ruby-3-0/) for full details.
In order to support passing keyword args in ruby versions both prior to and after this change, we need to make use of the `ruby2_keywords` method in ruby versions where it is defined. [ActiveJob base](https://github.com/rails/rails/blob/6-0-stable/activejob/lib/active_job/core.rb#L90) (Starting in Rails 6) does this as well, so we're also following their lead
Running the new test without the code change produces the following error on ruby 3
```ArgumentError: wrong number of arguments (given 1, expected 0; required keyword: keyword)```
=> Support Active Jobs with keyword args across ruby versions 

.toys/.data/releases.yml, semantic_conventions/.rubocop.yml, semantic_conventions/.yardopts, semantic_conventions/CHANGELOG.md, semantic_conventions/Gemfile, semantic_conventions/LICENSE, semantic_conventions/README.md, semantic_conventions/Rakefile, semantic_conventions/lib/opentelemetry-semantic_conventions.rb, semantic_conventions/lib/opentelemetry/semantic_conventions.rb, semantic_conventions/lib/opentelemetry/semantic_conventions/resource.rb, semantic_conventions/lib/opentelemetry/semantic_conventions/trace.rb, semantic_conventions/lib/opentelemetry/semantic_conventions/version.rb, semantic_conventions/opentelemetry-semantic_conventions.gemspec, semantic_conventions/templates/semantic_conventions.j2
Generated from the YAML, complete with Rake task to build it.
Fixes #733
=> feat: Add auto-generated semantic conventions gem

sdk/lib/opentelemetry/sdk/trace/tracer_provider.rb, sdk/test/opentelemetry/sdk/trace/tracer_provider_test.rb
TracerProvider can deadlock trying to create a Tracer instance during shutdown. This happens because a single Mutex is used to protect all internal state. The Tracer registry is only accessed in the `#tracer` method, however, (and no other state is accessed in that method) and can be safely protected with its own Mutex.
=> fix: split lock in TracerProvider

semantic_conventions/Rakefile, semantic_conventions/lib/opentelemetry/semantic_conventions/resource.rb, semantic_conventions/lib/opentelemetry/semantic_conventions/trace.rb, semantic_conventions/lib/opentelemetry/semantic_conventions/version.rb
This is a small update. Other than updating the documentation, the spec release:
- Adds the `aws.lambda.invoked_arn` attribute (`OpenTelemetry::SemanticConventions::Trace::AWS_LAMBDA_INVOKED_ARN`)
- Removes the `rpc.jsonrpc.method` attribute (`OpenTelemetry::SemanticConventions::Trace::RPC_JSONRPC_METHOD`)
These do not seem in-use in our repo.
=> feat!: Update opentelemetry-semantic_conventions to the 1.5.0 spec release

api/README.md, exporter/jaeger/README.md, exporter/otlp/README.md, exporter/zipkin/README.md, instrumentation/bunny/example/bunny.rb, instrumentation/concurrent_ruby/example/concurrent_ruby.rb, instrumentation/dalli/example/dalli.rb, instrumentation/delayed_job/example/delayed_job.rb, instrumentation/ethon/example/ethon.rb, instrumentation/excon/example/excon.rb, instrumentation/faraday/example/faraday.rb, instrumentation/graphql/example/graphql.rb, instrumentation/http_client/example/trace_demonstration.rb, instrumentation/koala/example/trace_demonstration.rb, instrumentation/lmdb/README.md, instrumentation/mysql2/example/mysql2.rb, instrumentation/net_http/example/net_http.rb, instrumentation/pg/example/pg.rb, instrumentation/rack/example/trace_demonstration.rb, instrumentation/rack/example/trace_demonstration2.rb, instrumentation/rails/example/trace_request_demonstration.ru, instrumentation/restclient/example/restclient.rb, instrumentation/ruby_kafka/example/ruby_kafka.rb, instrumentation/sinatra/example/server.rb, sdk/README.md
This PR updates our documentation in a few ways:
- Replaces some outdated configuration examples referencing a tracer factory
- Cleans up a reference to a non-existent LMDB example
- Sets the console span exporter for all current instrumentation examples
- Updates docs to reflect how to configure things via the environment whenever possible or reasonable.
Note that this means our examples may not flush to the console since the
BatchSpanProcessor is selected by default. I think this is okay,
honestly, but if it comes up we could figure out a way to select the
SimpleSpanProcessor (as some examples were doing) via the environment.
Fixes #872
=> Update docs to rely more on environment variable configuration

api/lib/opentelemetry/baggage/propagation/text_map_propagator.rb, api/test/opentelemetry/baggage/propagation/text_map_propagator_test.rb
We don't test for a zero-length string, because I can really only think
of two ways to do it: regular expressions (can be slow) and
`.strip.empty?` (which `dup`s the string and therefore allocates, I
believe). And slowing down or allocating defeats the purpose of what
this change is trying to achieve: *not* slowing down or allocating in
the relatively common case of "there's no baggage to extract."
Note: https://github.com/rails/rails/blob/83217025a171593547d1268651b446d3533e2019/activesupport/lib/active_support/core_ext/object/blank.rb#L122-L124
Fixes #811
=> fix: Return the original context if the baggage header value is empty

sdk/lib/opentelemetry/sdk/trace/span.rb, sdk/lib/opentelemetry/sdk/trace/span_limits.rb, sdk/test/opentelemetry/sdk/trace/span_limits_test.rb, sdk/test/opentelemetry/sdk/trace/span_test.rb, sdk/test/opentelemetry/sdk/trace/tracer_test.rb
This renames the `attribute_per_event_count_limit` to `event_attribute_count_limit` and `attribute_per_link_count_limit` to `link_attribute_count_limit` in `SpanLimits` to better align with the [environment variable names in the spec](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/sdk-environment-variables.md#span-collection-limits). It also adds the required environment variables (previously those values inherited their default from the `OTEL_SPAN_ATTRIBUTE_COUNT_LIMIT` env var).
=> fix!: span limits env vars

instrumentation/action_view/lib/opentelemetry/instrumentation/action_view/fanout.rb, instrumentation/action_view/lib/opentelemetry/instrumentation/action_view/instrumentation.rb, instrumentation/action_view/lib/opentelemetry/instrumentation/action_view/railtie.rb, instrumentation/action_view/lib/opentelemetry/instrumentation/action_view/span_subscriber.rb, instrumentation/action_view/opentelemetry-instrumentation-action_view.gemspec, instrumentation/action_view/test/opentelemetry/instrumentation/action_view/fanout_test.rb, instrumentation/action_view/test/opentelemetry/instrumentation/action_view/span_subscriber_test.rb, instrumentation/rails/lib/opentelemetry/instrumentation/rails/instrumentation.rb, instrumentation/rails/lib/opentelemetry/instrumentation/rails/railtie.rb
Splitting apart the rails component instrumentation dependencies from the rails instrumentation gem itself.
Similar to https://github.com/open-telemetry/opentelemetry-ruby/pull/878
=> refactor: split out active support from rails gem

exporter/jaeger/lib/opentelemetry/exporter/jaeger/agent_exporter.rb, exporter/jaeger/lib/opentelemetry/exporter/jaeger/collector_exporter.rb, exporter/jaeger/test/opentelemetry/exporters/jaeger/agent_exporter_test.rb
Fixes #752
The Zipkin collector already supports the required env var.
Note that the timeout is ignored for the CollectorExporter because we don't have control over timeouts at this layer. We could use `Timeout::timeout` but I'm not confident that will work as designed, and not screw up some internal state in the Thrift gem.
=> feat: OTEL_EXPORTER_JAEGER_TIMEOUT env var

semantic_conventions/Rakefile, semantic_conventions/lib/opentelemetry/semantic_conventions/resource.rb, semantic_conventions/lib/opentelemetry/semantic_conventions/trace.rb, semantic_conventions/lib/opentelemetry/semantic_conventions/version.rb
Other than documentation updates which reference the Alibaba cloud, this
release adds support for a few new network conventions:
- `net.host.connection.type`
- `net.host.connection.subtype`
- `net.host.carrier.name`
- `net.host.carrier.mcc`
- `net.host.carrier.mnc`
- `net.host.carrier.icc`
=> feat: Update to semantic conventions v1.6.0

README.md
This inserts a reference to the OpenTelemetry client library stability document. #507 laid out an alternate proposal from last year, but our gems have not evolved in quite the way described and it didn't seem to provide much aside from what the upstream document already contains. Moreover, I think we're expected to adhere to the upstream stability document, so I'm not sure we really need a separate one.
This is not to say that we should never adopt additional policies or guarantees within this repo, but it is to say "none seem to be needed right now, and so it doesn't feel necessary to block 1.0 any longer." Anything we adopt in the future will necessarily be somehow compatibile with (or a superset of) the OpenTelemetry stability guarantees, so this feels like a good baseline to me.
Fixes …
=> docs: Add reference to otel versioning / stability doc

instrumentation/action_pack/README.md, instrumentation/rails/README.md, instrumentation/rails/lib/opentelemetry/instrumentation/rails/instrumentation.rb, instrumentation/rails/test/opentelemetry/instrumentation/rails/instrumentation_test.rb, instrumentation/rails/test/test_helper.rb
> Add config options for opting out of any sub gem instrumentation.
Follow up from https://github.com/open-telemetry/opentelemetry-ruby/pull/878
=> fix: rails instrumentation to not explicitly install sub gems

.github/workflows/release-retry.yml
Testing a suspect ci issue by pinning toys to 0.11.5
https://github.com/open-telemetry/opentelemetry-ruby/runs/3343455325?check_suite_focus=true#step:5:429
https://github.com/dazuma/toys/commit/474cf17a0f2b6c37c5add20168d4914ffb118bd5#diff-5a2aea7ff7ffb53950632cc40ab93b62a922e4d24cb67c81656ce63d3109073aR30
=> fix: test ci error, pin toys

.github/workflows/release-retry.yml
Toys 0.12.1 is released, which should fix #912.
attn: @robertlaurin
=> chore: Revert pin of toys

instrumentation/rack/lib/opentelemetry/instrumentation/rack/middlewares/tracer_middleware.rb, instrumentation/rack/test/opentelemetry/instrumentation/rack/middlewares/tracer_middleware_test.rb
```
Minitest::UnexpectedError: NoMethodError: undefined method `+' for nil:NilClass
--
  | /app/vendor/bundle/ruby/2.7.0/gems/opentelemetry-instrumentation-rack-0.19.0/lib/opentelemetry/instrumentation/rack/middlewares/tracer_middleware.rb:133:in `fullpath'
```
It seems it is not safe to assume that `SCRIPT_NAME` will always be present.
>SCRIPT_NAME
>The initial portion of the request URL's “path” that corresponds to the application object, so that the application knows its >virtual “location”. This may be an empty string, if the application corresponds to the “root” of the server.
https://github.com/rack/rack/blob/master/SPEC.rdoc
=> fix: rack middleware assuming script_name presence

instrumentation/all/opentelemetry-instrumentation-all.gemspec
https://github.com/open-telemetry/opentelemetry-ruby/issues/922
```
opentelemetry-instrumentation-all: bundle
Fetching gem metadata from https://rubygems.org/.........
Resolving dependencies...
Bundler could not find compatible versions for gem
"opentelemetry-instrumentation-sidekiq":
In Gemfile:
opentelemetry-instrumentation-sidekiq
opentelemetry-instrumentation-all was resolved to 0.20.0, which depends on
opentelemetry-instrumentation-sidekiq (~> 0.19.0)
Could not find gem 'opentelemetry-instrumentation-sidekiq (~> 0.19.0)', which is
required by gem 'opentelemetry-instrumentation-all', in source at `../sidekiq`.
FAILURE
opentelemetry-instrumentation-all: test
```
=> fix: instrumentation all sidekiq

instrumentation/active_record/lib/opentelemetry/instrumentation/active_record/instrumentation.rb, instrumentation/active_record/lib/opentelemetry/instrumentation/active_record/patches/relation_persistence.rb, instrumentation/active_record/test/instrumentation/active_record/patches/relation_persistence_test.rb, instrumentation/active_record/test/test_helper.rb
We often use code like:
```
Product
.where(...)
.where(...)
.update_all(attributes)
```
This allows doing atomic updates and avoid N+1 queries. `update_all` and
`delete_all` however were not traced.
I initially thought about putting these to `PersistenceClassMethods`
module but that doesn't work when scopes are used. These calls create
`ActiveRecord::Relation` instance which seemed a better place to patch.
I also added tests to ensure these calls are also traced when scopes are
not used.
=> feat: trace update_all and delete_all calls in ActiveRecord

README.md
=> chore: update approver corp affiliation

instrumentation/action_view/lib/opentelemetry/instrumentation/action_view/fanout.rb, instrumentation/action_view/lib/opentelemetry/instrumentation/action_view/railtie.rb, instrumentation/action_view/test/opentelemetry/instrumentation/action_view/fanout_test.rb
Recently encountered an issue where subscriptions that happen earlier get dropped when we override `notifier`. Here is my attempt at keeping the subscriptions by using `DelegateClass`
I confirmed by running the added test on main branch
=> fix: keep Active Support subscriptions intact when patching

instrumentation/active_record/lib/opentelemetry/instrumentation/active_record/patches/persistence_class_methods.rb, instrumentation/active_record/test/instrumentation/active_record/patches/persistence_class_methods_test.rb
The instantiation method has proven to be overly verbose and as a result we
have opted to remove it entirely from the Active Record instrumentation.
https://github.com/open-telemetry/opentelemetry-ruby/issues/950
=> fix: Remove Active Record instantiation patch

docker-compose.yml, instrumentation/ruby_kafka/README.md, instrumentation/ruby_kafka/docker-compose.yml, instrumentation/ruby_kafka/lib/opentelemetry/instrumentation/ruby_kafka/instrumentation.rb, instrumentation/ruby_kafka/test/opentelemetry/instrumentation/ruby-kafka/instrumentation_test.rb
Some applications bypass Ruby Gems when loading dependencies,
which results in a `nil` variable being returned by `Gem.loaded_specs`.
This change adds a fallback to use `Kafka::VERSION` constant to check
the minimum version when one is not available in Ruby Gems.
See https://github.com/open-telemetry/opentelemetry-ruby/issues/947
=> fix: Use Kafka::VERSION fallback for compatibility

api/test/opentelemetry/context_test.rb, sdk/CHANGELOG.md, sdk/lib/opentelemetry/sdk/trace/export/batch_span_processor.rb, sdk/test/opentelemetry/sdk/trace/export/batch_span_processor_test.rb
Addresses regression as mentioned in https://github.com/open-telemetry/opentelemetry-ruby/issues/959
Tests are pretty basic but should be enough to help prevent a similar regression.
=> Update bsp .shutdown return value

instrumentation/concurrent_ruby/example/concurrent_ruby.rb, instrumentation/concurrent_ruby/test/opentelemetry/instrumentation/concurrent-ruby/instrumentation_test.rb
The recent changes to the concurrent-ruby instrumentation also added context propagation support to classes that mixin `Concurrent::Async` so I've added an example and test to demonstrate this behaviour.
It's possible that other features of `concurrent-ruby` will also behave similarly but I haven't explored this.
=> Add example and tests for Concurrent::Async

common/README.md, exporter/zipkin/lib/opentelemetry/exporter/zipkin/transformer.rb, instrumentation/http/lib/opentelemetry/instrumentation/http/patches/client.rb, instrumentation/http/lib/opentelemetry/instrumentation/http/patches/connection.rb, instrumentation/http/test/instrumentation/http/patches/client_test.rb, instrumentation/http/test/instrumentation/http/patches/connection_test.rb, instrumentation/http_client/lib/opentelemetry/instrumentation/http_client/patches/client.rb, instrumentation/http_client/test/instrumentation/http_client/patches/client_test.rb, instrumentation/net_http/lib/opentelemetry/instrumentation/net/http/patches/instrumentation.rb, instrumentation/net_http/test/opentelemetry/instrumentation/net/http/instrumentation_test.rb
=> fix: change net attribute names to match the semantic conventions spec for http

instrumentation/ethon/lib/opentelemetry/instrumentation/ethon/patches/easy.rb, instrumentation/ethon/lib/opentelemetry/instrumentation/ethon/patches/multi.rb, instrumentation/ethon/test/opentelemetry/instrumentation/ethon/instrumentation_test.rb
As probably you already now Typhoeus relay on Ethon and this repository is adding automatic instrumentation for it.
But the issue is that we found an issue when using Typhoeus::Hydra which is kind of difficult to explain but kind of easy to reproduce.
The main idea is that Typhoeus::Hydra stores on memory requests to be done but only pass to ethon in batches of `max_concurrency` and in only one call to `Ethon::Multi#perform` the batches after the first max_concurrency batch only call to `Ethon::Multi.#add` methods so we missed the `@otel_span` instance variable.
You can see a trace of the issue here
```sh
Caught a post-mortem exception: #<NoMethodError: undefined method `finish' for nil:NilClass>
versions/2.6.8/lib/ruby/gems/2.6.0/gems/opentelemetry-instrumentation-ethon-0.19.2/lib/opentel …
```
=> Fix Ethon for Typhoeus::Hydra support

instrumentation/action_pack/Appraisals, instrumentation/action_pack/gemfiles/rails_6.0.gemfile, instrumentation/action_pack/gemfiles/rails_6.1.gemfile, instrumentation/action_pack/gemfiles/rails_7.0.gemfile, instrumentation/action_pack/test/test_helpers/app_config.rb, instrumentation/action_view/Appraisals, instrumentation/action_view/gemfiles/rails_7.0.gemfile, instrumentation/action_view/lib/opentelemetry/instrumentation/action_view/span_subscriber.rb, instrumentation/rails/Appraisals, instrumentation/rails/gemfiles/rails_5.2.gemfile, instrumentation/rails/gemfiles/rails_6.0.gemfile, instrumentation/rails/gemfiles/rails_6.1.gemfile, instrumentation/rails/gemfiles/rails_7.0.gemfile, instrumentation/rails/test/test_helpers/app_config.rb
ActionView instrumentation no longer fails by having it use the same
subscriber logic as used for Rails 6.
Also add Rails 7 Appraisals to all relevant gems which has any Rails
Appraisals.
=> fix: instrumentation of Rails 7

instrumentation/http/example/trace_demonstration.rb
~~Removed _Examples_ section from HTTP readme file.~~
~~Couldn't find `./example/trace_demonstration.rb`~~
Edit: Added missing example file for HTTP instrumentation.
=> chore(http): Add missing example

instrumentation/sidekiq/Appraisals, instrumentation/sidekiq/test/opentelemetry/instrumentation/sidekiq/patches/poller_test.rb
Sidekiq cut a 6.3 release over the weekend, which has some fancy new and improved inline Lua https://github.com/mperham/sidekiq/pull/5044. While slick, it also happens to use a slightly different redis client method that ends up breaking some of our test assumptions about what gets traced in redis from our sidekiq poller instrumentation. Our CI is now failing as a result(failed run example here: https://github.com/open-telemetry/opentelemetry-ruby/runs/4144038824?check_suite_focus=true).
This PR updates the sidekiq instrumentation test suite to only expect that poller redis instrumentation when `sidekiq < 6.3x`.
Not exactly the prettiest solution but ought to work? long term i think further evidence that a canary build or some pessimistic version constraints can help us avoid this sort of …
=> chore: fix tests for sidekiq to support inline lua changes

instrumentation/dalli/lib/opentelemetry/instrumentation/dalli/instrumentation.rb, instrumentation/dalli/lib/opentelemetry/instrumentation/dalli/patches/server.rb, instrumentation/dalli/test/opentelemetry/instrumentation/dalli/instrumentation_test.rb
In an attempt to standardize options around database instrumentation `db_statement` settings, this PR adds the `:obfuscate` value to dalli ( a memcached client)'s `db_statement` configuration option. When enabled, it will obfuscate the `db.statement` span attribute. In practice this simply means dropping the arguments and only including the command, which is relatively low value (since it's already available in the span name) but, for the sake of consistency with the other database instrumentations, this allows users to still capture some level of detail in their `db.statement` attribute without potentially exposing sensitive information.
=> feat: add dalli obfuscation for db_statement

instrumentation/dalli/Appraisals, instrumentation/dalli/gemfiles/dalli_3.0.gemfile, instrumentation/dalli/lib/opentelemetry/instrumentation/dalli/instrumentation.rb, instrumentation/dalli/lib/opentelemetry/instrumentation/dalli/patches/server.rb, instrumentation/dalli/opentelemetry-instrumentation-dalli.gemspec, instrumentation/dalli/test/opentelemetry/instrumentation/dalli/instrumentation_test.rb
Dalli 3.0 has deprecated `Dalli::Server` in petergoldstein/dalli#760
I believe the fix is simply to use `Dalli::Protocol::Binary` instead, when Dalli >=3.0 is detected (while still using `Dalli::Server` in <3.0).
I've created a new Appraisal config to test this with Dalli 3.0, while still also testing 2.7.
Related: [Dalli 3.0 Upgrade Guide](https://github.com/petergoldstein/dalli/blob/master/3.0-Upgrade.md)
=> fix: resolve Dalli::Server deprecation in 3.0+

.toys/.data/releases.yml, instrumentation/rspec/.rubocop.yml, instrumentation/rspec/.yardopts, instrumentation/rspec/Appraisals, instrumentation/rspec/CHANGELOG.md, instrumentation/rspec/Gemfile, instrumentation/rspec/LICENSE, instrumentation/rspec/README.md, instrumentation/rspec/Rakefile, instrumentation/rspec/example/Gemfile, instrumentation/rspec/example/rspec_with_rspec_formatter_configuration.rb, instrumentation/rspec/example/rspec_with_sdk_configure.rb, instrumentation/rspec/lib/opentelemetry-instrumentation-rspec.rb, instrumentation/rspec/lib/opentelemetry/instrumentation.rb, instrumentation/rspec/lib/opentelemetry/instrumentation/rspec.rb, instrumentation/rspec/lib/opentelemetry/instrumentation/rspec/formatter.rb, instrumentation/rspec/lib/opentelemetry/instrumentation/rspec/instrumentation.rb, instrumentation/rspec/lib/opentelemetry/instrumentation/rspec/version.rb, instrumentation/rspec/opentelemetry-instrumentation-rspec.gemspec, instrumentation/rspec/test/.rubocop.yml, instrumentation/rspec/test/opentelemetry/instrumentation/rspec/formatter_test.rb, instrumentation/rspec/test/opentelemetry/instrumentation/rspec/instrumentation_test.rb, instrumentation/rspec/test/rspec_patches.rb, instrumentation/rspec/test/test_helper.rb
This PR covers adding instrumentation for RSpec using a RSpec formatter. It could then be used as part of a CI/CD pipeline that is configured to emit traces. At this point, parent context would need to passed manually from other processes, but I understand this being discussed as [an addition to the spec](https://github.com/open-telemetry/opentelemetry-specification/issues/740).
There are two ways to enable instrumentation either by configured Otel to use the instrumentation or by adding the formatter to RSpec. You can see examples of this in `examples/`.
Some things :
- The formatter is using `::attach` and `::detach` and a stack to add and remove span context. I think this is appropriate considering how example and example groups are currently executed, but I'm assuming this might break …
=> feat: add instrumentation for rspec

instrumentation/sidekiq/lib/opentelemetry/instrumentation/sidekiq/middlewares/client/tracer_middleware.rb, instrumentation/sidekiq/lib/opentelemetry/instrumentation/sidekiq/middlewares/server/tracer_middleware.rb, instrumentation/sidekiq/test/opentelemetry/instrumentation/sidekiq/middlewares/server/tracer_middleware_test.rb
Adding `messaging.operation` attribute to sidekiq.
The [specification](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/messaging.md#messaging-attributes) doesn't require it but it could be helpful.
The value must be either `receive` or `process`, in sidekiq case, there isn't a receive span so I have added only for `process`.
For the specification:
"The values allowed for <operation name> are defined in the section Operation names below. If the format above is used, the operation name MUST match the messaging.operation attribute defined for message consumer spans below." 
About tests, I felt it is too small of a change to add test, let me know if you think otherwise
Thanks!
(BTW, my first contribution here. My apologies in …
=> Sidekiq messaging operation

instrumentation/rack/lib/opentelemetry/instrumentation/rack/middlewares/tracer_middleware.rb, sdk/lib/opentelemetry/sdk/trace/span.rb, sdk/lib/opentelemetry/sdk/trace/tracer.rb, sdk/lib/opentelemetry/sdk/trace/tracer_provider.rb, sdk/test/opentelemetry/sdk/trace/span_test.rb
This is a followup to #717 addressing #709 (which I probably should not have closed). It uses monotonic clock offsets to compute timestamps for `Span` and `Event` unless explicit timestamps are provided.
=> fix: use monotonic clock where possible

instrumentation/active_record/gemfiles/activerecord_5.2.gemfile, instrumentation/active_record/gemfiles/activerecord_6.0.gemfile, instrumentation/active_record/gemfiles/activerecord_6.1.gemfile, instrumentation/active_record/lib/opentelemetry/instrumentation/active_record/instrumentation.rb, instrumentation/active_record/test/instrumentation/active_record/instrumentation_test.rb
We've observed serious incompatibilities between this instrumentation and AR in the rails 7.X.X alpha releases.  We're going to err to the side of caution and disable the instrumentation patches if rails 7 is detected.
CC: @SomalianIvan
=> fix: add max supported version for active record

instrumentation/rack/lib/opentelemetry/instrumentation/rack/middlewares/tracer_middleware.rb, instrumentation/rack/opentelemetry-instrumentation-rack.gemspec
Follow up from https://github.com/open-telemetry/opentelemetry-ruby/pull/1006
=> fix: rack to stop using api env getter

instrumentation/sinatra/lib/opentelemetry/instrumentation/sinatra/middlewares/tracer_middleware.rb, instrumentation/sinatra/opentelemetry-instrumentation-sinatra.gemspec
Follow up from https://github.com/open-telemetry/opentelemetry-ruby/pull/1006
=> fix: sinatra to stop using api env getter

instrumentation/dalli/test/opentelemetry/instrumentation/dalli/instrumentation_test.rb
Dalli tests are failing due to (i think?) changes upstream in `3.0.5` that change the behavior of certain errors we're raising via stubs in our specs, specifically `Dalli::DalliError`
```
opentelemetry-instrumentation-dalli: test
......E.
Finished in 0.016433s, 486.8366 runs/s, 1643.0736 assertions/s.
1) Error:
OpenTelemetry::Instrumentation::Dalli::Instrumentation::tracing#test_0006_after error:
NoMethodError: undefined method `options' for nil:NilClass
/opt/hostedtoolcache/Ruby/2.6.9/x64/lib/ruby/gems/2.6.0/gems/dalli-3.0.5/lib/dalli/client.rb:437:in `block in get_multi_yielder'
/opt/hostedtoolcache/Ruby/2.6.9/x64/lib/ruby/gems/2.6.0/gems/dalli-3.0.5/lib/dalli/ring.rb:76:in `lock'
/opt/hostedtoolcache/Ruby/2.6.9/x64/lib/ruby/gems/2.6.0/gems/dalli-3.0.5/lib/dalli/client.rb:421:in …
```
=> chore: fix dalli tests to account for upstream changes to `Dalli:DalliError` handling

instrumentation/que/lib/opentelemetry/instrumentation/que/instrumentation.rb, instrumentation/que/lib/opentelemetry/instrumentation/que/patches/poller.rb, instrumentation/que/opentelemetry-instrumentation-que.gemspec, instrumentation/que/test/opentelemetry/instrumentation/que_test.rb, instrumentation/que/test/test_helper.rb
Que polls the database every few seconds to find new jobs. This
generates postgresql spans (if pg instrumentation library is enabled)
without any parents and without much context. These can get quite noisy.
This commit by default disables these traces. It is however possible to
enable it with `trace_poller` option.
There are also many other places where Que can be noisy, but for now
just starting with the Poller.
A lot of inspiration was taken from the `sidekiq` library.
=> feat: Instrument Que poller

api/lib/opentelemetry/context/propagation.rb, api/lib/opentelemetry/context/propagation/rack_env_getter.rb, propagator/jaeger/test/text_map_propagator_test.rb
Deprecates the api rack env getter, anyone retrieving the getter will receive a warning log message that this code path has been deprecated.
=> fix: deprecate api rack env getter

instrumentation/dalli/lib/opentelemetry/instrumentation/dalli/utils.rb
Dalli v3.1 was released a few days ago (see: https://github.com/petergoldstein/dalli/releases/tag/v3.1.0) and contains some refactoring for `multi` methods, by adding a [PipelinedGetter Class to handle the multi behavior](
https://github.com/petergoldstein/dalli/blob/76acdbd841ce41c24bdb7a8c24c32d1afb8c2b03/lib/dalli/pipelined_getter.rb#L48-L55) instead of having it as part o the `Dalli::Client` code. This also means adding a new method to `Dalli::Server` which we didn't have mappings to `opcode` for. This PR updates our mapping to includes an opcode mapping for this new `Dalli::Server` method.
Long term, we would like to re-write this instrumentation to patch the Dalli::Client method, which in practice seems a bit more stable. Previously we'd looked into this but found the extra work …
=> chore: update dalli instrumentation to support v3.1 pipeline_get method

api/lib/opentelemetry/trace/propagation/trace_context/text_map_propagator.rb, api/test/opentelemetry/trace/propagation/trace_context/text_map_propagator_test.rb
For W3C text map propagator, the extraction should use the argument context and apply the current span on it.
Before this fix, when calling `context_with_span` the argument context is not used. It used the current context instead. 
From Propagators API specification:
> [Returns a new Context derived from the Context passed as argument](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/context/api-propagators.md#extract)
---- 
Thanks @blumamir for finding this issue.
=> text map propagator extraction should use argument context

exporter/otlp/lib/opentelemetry/exporter/otlp/exporter.rb, exporter/otlp/test/opentelemetry/exporter/otlp/exporter_test.rb
> [2]: If no compression value is explicitly specified, SIGs can default to the value they deem most useful among the supported options.
>      This is especially important in the presence of technical constraints,
>      e.g. directly sending telemetry data from mobile devices to backend servers.
>
> Supported values for OTEL_EXPORTER_OTLP_*COMPRESSION options:
>
> * none if compression is disabled.
> * gzip is the only specified compression method for now.
https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/protocol/exporter.md#configuration-options
=> fix: Allow OTLP Exporter compression value of `none`

instrumentation/ruby_kafka/lib/opentelemetry/instrumentation/ruby_kafka/patches/client.rb, instrumentation/ruby_kafka/lib/opentelemetry/instrumentation/ruby_kafka/patches/consumer.rb, instrumentation/ruby_kafka/lib/opentelemetry/instrumentation/ruby_kafka/utils.rb, instrumentation/ruby_kafka/test/opentelemetry/instrumentation/ruby-kafka/patches/client_test.rb, instrumentation/ruby_kafka/test/opentelemetry/instrumentation/ruby-kafka/patches/consumer_test.rb, instrumentation/ruby_kafka/test/opentelemetry/instrumentation/ruby-kafka/utils_test.rb
The instrumentation for Kafka was assuming that message keys are only
valid utf8 strings, but message keys can be any string of bytes. See:
https://cwiki.apache.org/confluence/display/KAFKA/A+Guide+To+The+Kafka+Protocol#AGuideToTheKafkaProtocol-Responses
This was causing encoding errors in the exporters, and lost spans, as they were trying to encode string into utf8 before transport. These problems were originally described here: https://github.com/open-telemetry/opentelemetry-ruby/issues/751
This fix converts keys that aren't valid utf8 strings into hex strings, which seems to be consistent with how other byte strings are encoded such as with trace ids.
This change may need to be ported onto this PR: https://github.com/open-telemetry/opentelemetry-ruby/pull/978
=> Fix: Don't error on non-string/utf8 kafka message keys

.github/workflows/ci-without-services.yml, .toys/.data/releases.yml, instrumentation/all/Gemfile, instrumentation/all/lib/opentelemetry/instrumentation/all.rb, instrumentation/all/opentelemetry-instrumentation-all.gemspec, instrumentation/trilogy/.rubocop.yml, instrumentation/trilogy/.yardopts, instrumentation/trilogy/Appraisals, instrumentation/trilogy/CHANGELOG.md, instrumentation/trilogy/Gemfile, instrumentation/trilogy/LICENSE, instrumentation/trilogy/README.md, instrumentation/trilogy/Rakefile, instrumentation/trilogy/lib/opentelemetry-instrumentation-trilogy.rb, instrumentation/trilogy/lib/opentelemetry/instrumentation.rb, instrumentation/trilogy/lib/opentelemetry/instrumentation/trilogy.rb, instrumentation/trilogy/lib/opentelemetry/instrumentation/trilogy/instrumentation.rb, instrumentation/trilogy/lib/opentelemetry/instrumentation/trilogy/patches/client.rb, instrumentation/trilogy/lib/opentelemetry/instrumentation/trilogy/version.rb, instrumentation/trilogy/opentelemetry-instrumentation-trilogy.gemspec, instrumentation/trilogy/test/.rubocop.yml, instrumentation/trilogy/test/opentelemetry/instrumentation/trilogy/instrumentation_test.rb, instrumentation/trilogy/test/test_helper.rb
Provides auto instrumentation for the [trilogy database driver](https://github.com/github/trilogy)
=> feat: Add Trilogy Auto Instrumentation

website_docs/manual_instrumentation.md
Contributes to https://github.com/open-telemetry/opentelemetry.io/issues/973
Hello again!
I felt that some wording could change in this section. It's about adding some information to the current span, but the terminology of "context to existing spans" felt kind of confusing, since context has a pretty strong meaning in OTel, and it's not just any existing span that we're adding stuff to in the example.
I'm also happy to split out getting the existing span from adding attributes to it if folks would prefer. But I actually do sort of like how they're combined like this, since this feels like the most common use case for getting the current span.
=> Be explicit about current span in manual instrumentation doc

instrumentation/koala/Gemfile
Temp workaround for https://github.com/arsduo/koala/issues/659 to unblock CI until upstream Koala itself supports Faraday 2.0
=> chore: add max faraday version to tests 

instrumentation/active_model_serializers/lib/opentelemetry/instrumentation/active_model_serializers/instrumentation.rb, instrumentation/all/Gemfile, instrumentation/all/test/opentelemetry/instrumentation/all_test.rb, instrumentation/all/test/test_helper.rb
When both `ActiveSupport` and `ActiveModelSerializers` instrumentations are loaded,
constant `ActiveSupport::Notifications` inside `ActiveModelSerializers` can be incorrectly
resolved to `OpenTelemetry::Instrumentation::ActiveSupport`.
```
ERROR -- : OpenTelemetry error: Instrumentation: OpenTelemetry::Instrumentation::ActiveModelSerializers unhandled exception during install
...
...
uninitialized constant OpenTelemetry::Instrumentation::ActiveSupport::Notifications
OR
undefined method `subscribe' for Notifications:Module
```
=> fix: `ActiveSupport` constant conflict in Active Model Serializers instrumentation

instrumentation/rack/lib/opentelemetry/instrumentation/rack/middlewares/tracer_middleware.rb, instrumentation/rack/test/opentelemetry/instrumentation/rack/middlewares/tracer_middleware_test.rb, instrumentation/sinatra/lib/opentelemetry/instrumentation/sinatra/middlewares/tracer_middleware.rb, instrumentation/sinatra/test/opentelemetry/instrumentation/sinatra_test.rb
The specification as of late October/early November 2021 has been updated for http server spans so that 400 level responses should not create a span.status of `Error` but instead should leave span status unset. Two instrumentations, rack and sinatra, were off spec and need to be updated, this PR updates them.
see:
- https://github.com/open-telemetry/opentelemetry-specification/pull/1998
- https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/http.md#status
=> chore: update server instrumentation to not reflect 400 status as error

instrumentation/trilogy/lib/opentelemetry/instrumentation/trilogy/patches/client.rb, instrumentation/trilogy/test/opentelemetry/instrumentation/trilogy/instrumentation_test.rb
The trilogy driver does not use keyword arguments in its initializer, which results in an ArgumentError to be raised when an options hash is used instead.
This change rolls back the overridden initializer to accept a hash.
=> fix: Trilogy Driver Options

website_docs/getting_started.md
Just following the getting started and discovered that this was slightly wrong.
The git repo folder is opentelemetry-ruby instead of open-telemetry-ruby
=> Fixing a minor typo in getting started.

exporter/otlp/lib/opentelemetry/exporter/otlp/exporter.rb, exporter/otlp/test/opentelemetry/exporter/otlp/exporter_test.rb
https://github.com/open-telemetry/opentelemetry-specification/pull/2014 changed the default scheme for the OTLP endpoint from `https` to `http`. This updates our default.
Fixes #1078
=> fix: Default scheme for OTLP endpoint

instrumentation/net_http/lib/opentelemetry/instrumentation/net/http/patches/instrumentation.rb
There are semantic convetnion constats exists.
Replaced attributes for `Instrumentation::Net::HTTP` to use them.
=> refactor: [instrumentation/net/http] Replace strings with constants

exporter/otlp/lib/opentelemetry/exporter/otlp/exporter.rb, exporter/otlp/test/opentelemetry/exporter/otlp/exporter_test.rb
In the effort of pushing the OTLP exporter to a 1.0, I'm going through the spec and trying to align the subtle inconsistencies. 
The TIMEOUT status is not explicitly stated, which leads me to believe it should probably be removed.
```
Returns: ExportResult:
ExportResult is one of:
* Success - The batch has been successfully exported. For protocol exporters this typically means that the data is sent over the wire and delivered to the destination server.
* Failure - exporting failed. The batch must be dropped. For example, this can happen when the batch contains bad data and cannot be serialized.
```
https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk.md#interface-definition-1
However force flush does make reference to notify the caller that the …
=> Remove TIMEOUT timeout status from OTLP exporter

instrumentation/aws_sdk/Gemfile, instrumentation/aws_sdk/lib/opentelemetry/instrumentation/aws_sdk/handler.rb, instrumentation/aws_sdk/test/opentelemetry/instrumentation_test.rb
I looked at the documentation for the AWS Ruby SDK and found that [every `response` has a `successful?` method](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Seahorse/Client/Response.html#successful%3F-instance_method). It returns a boolean.
However, better than that, [the source code for `successful?`](https://github.com/aws/aws-sdk-ruby/blob/83ac0d4903a4c3f530b5f37c3e34e61cf54a1320/gems/aws-sdk-core/lib/seahorse/client/response.rb#L57-L61) reveals something useful:
```ruby
def successful?
(200..299).cover?(@context.http_response.status_code) && @error.nil?
end
```
`@context.http_response.status_code` is appropriately populated when the `response` completes!
So I used that to set the `http.status_code` attribute on the span.
I also included the `httpclient` gem so that in the tests we …
=> Add HTTP Status Code attribute to AWS SDK span

instrumentation/aws_sdk/CHANGELOG.md
Follow up to #1099 which changed the lines breaks to be LF instead of CRLF like they were before. This breaks our regex of the CHANGELOG file that we need for the release:
https://github.com/open-telemetry/opentelemetry-ruby/blob/b7149fb72cad6c45956a6be80acfb2d062aab3a6/.toys/release/.lib/release_utils.rb#L228-L230
=> Consistent CRLF in AWS SDK Instrumentation Changelog

examples/http/server.rb
I was running the example and saw this warning. So, fixing it to use the non-deprecated module.
=> Fix deprecation warning from rack_env_getter

sdk/lib/opentelemetry/sdk/trace/span_limits.rb, sdk/test/opentelemetry/sdk/trace/span_limits_test.rb
This patch updates the attribute length limit environment variable name to match the spec: https://github.com/open-telemetry/opentelemetry-specification/blob/7b504383f53b02b10f62ef78fa008fdfd18c633e/specification/sdk-environment-variables.md#attribute-limits while also still falling back to the old environment variable since it was included in 1.0 (but only if the one that matches the specification is not set).
=> update attribute length limit env var name to match spec

examples/http/client.rb
Looks like the source was renamed. Just fixing it.
=> Fix semantic conventions link in documentation

instrumentation/net_http/lib/opentelemetry/instrumentation/net/http/patches/instrumentation.rb, instrumentation/net_http/test/opentelemetry/instrumentation/net/http/instrumentation_test.rb
Related to https://github.com/open-telemetry/opentelemetry-ruby/issues/443 and https://github.com/open-telemetry/opentelemetry-ruby/pull/474
The attributes hash was being built in a way that values coming from `OpenTelemetry::Common::HTTP::ClientContext.attributes` were being overwritten by the local ones, when it should really be the other way around.
=> Fix ClientContext attributes overwrite in Net::HTTP

instrumentation/redis/lib/opentelemetry/instrumentation/redis/patches/client.rb
The redis instrumentation has been mutating the command during the parse steps.  This appears to have no impact on redis itself as it parses the command all the same if it's `set` or `SET`.
=> fix: prevent redis instrumentation from mutating the command

instrumentation/faraday/lib/opentelemetry/instrumentation/faraday/middlewares/tracer_middleware.rb, instrumentation/faraday/test/opentelemetry/instrumentation/faraday/middlewares/tracer_middleware_test.rb
Adding `net.peer.name` attribute to Faraday instrumentation spans for parity with others similar libraries such as `Net::HTTP`.
=> Add net.peer.name to Faraday instrumentation

instrumentation/ethon/lib/opentelemetry/instrumentation/ethon/patches/easy.rb, instrumentation/excon/lib/opentelemetry/instrumentation/excon/middlewares/tracer_middleware.rb, instrumentation/faraday/lib/opentelemetry/instrumentation/faraday/middlewares/tracer_middleware.rb, instrumentation/http/lib/opentelemetry/instrumentation/http/patches/client.rb, instrumentation/http/lib/opentelemetry/instrumentation/http/patches/connection.rb, instrumentation/http_client/lib/opentelemetry/instrumentation/http_client/patches/client.rb, instrumentation/http_client/lib/opentelemetry/instrumentation/http_client/patches/session.rb, instrumentation/net_http/lib/opentelemetry/instrumentation/net/http/patches/instrumentation.rb
Fixes the ordering of attribute merging in some places, switches to using `merge!` to avoid creating an additional hash on merge.
=> fix: excessive hash creation on context attr merging

exporter/jaeger/README.md
This fixes a simple transposition typo.  The correct port number is on line 51 of the very same file and is also documented here: https://www.jaegertracing.io/docs/1.30/getting-started/#all-in-one
=> docs: fix exporter port in Jaeger exporter readme

instrumentation/action_pack/lib/opentelemetry/instrumentation/action_pack/patches/action_controller/metal.rb, instrumentation/action_pack/test/opentelemetry/instrumentation/action_pack/patches/action_controller/metal_test.rb, instrumentation/action_pack/test/test_helpers/app_config.rb
This change updates Rack spans so that their `http.target` attributes are consistent with [Rails' filter_parameter config](https://guides.rubyonrails.org/configuring.html#config-filter-parameters) when the ActionPack instrumentation is installed.
I have chosen to not make this optional as I feel it is important that the instrumentation follows the instruction set by Rails' configuration.
=> use rails request's filtered path as http.target attribute

sdk/.rubocop.yml, sdk/test/opentelemetry/sdk/trace/export/console_span_exporter_test.rb, sdk/test/opentelemetry/sdk/trace/export/in_memory_span_exporter_test.rb, sdk/test/opentelemetry/sdk/trace/export/span_exporter_test.rb
I was seeing a lot of warnings like:
```
opentelemetry-ruby/sdk/test/opentelemetry/sdk/trace/export/console_span_exporter_test.rb:14: warning: Passing only keyword arguments to Struct#initialize will behave differently from Ruby 3.2. Please use a Hash literal like .new({k: v}) instead of .new(k: v).
```
on Ruby 3.1 and this patch clears them up.
=> fix warning about Struct initialization in Ruby 3.2+

common/CHANGELOG.md, common/lib/opentelemetry/common/utilities.rb, sdk/CHANGELOG.md, sdk/lib/opentelemetry/sdk/trace/span.rb, sdk/test/opentelemetry/sdk/trace/span_test.rb
This set of patches both adds support for truncating strings in arrays but also tests that a variable is a string before checking its size and truncating. This fixes a bug that an attribute value of type float would crash if `attribute_length_limit` were configured.
=> attribute length limit: only truncate strings and strings in arrays

instrumentation/active_job/lib/opentelemetry/instrumentation/active_job/instrumentation.rb, instrumentation/base/lib/opentelemetry/instrumentation/registry.rb, instrumentation/dalli/lib/opentelemetry/instrumentation/dalli/instrumentation.rb, instrumentation/lmdb/lib/opentelemetry/instrumentation/lmdb/instrumentation.rb, instrumentation/mongo/lib/opentelemetry/instrumentation/mongo/instrumentation.rb, instrumentation/pg/lib/opentelemetry/instrumentation/pg/instrumentation.rb, instrumentation/que/lib/opentelemetry/instrumentation/que/instrumentation.rb, instrumentation/redis/lib/opentelemetry/instrumentation/redis/instrumentation.rb, instrumentation/resque/lib/opentelemetry/instrumentation/resque/instrumentation.rb, instrumentation/sidekiq/lib/opentelemetry/instrumentation/sidekiq/instrumentation.rb
Instrumentation options that use procs for validate do not support being overridden by environment variables,
which makes it difficult for operators to override default settings of many configuration options at runtime.
This change updates several instrumentation options that _should_ be using `enum` validators instead to make it possible to override settings using environment variables.
=> feat: Validate Using Enums

sdk/lib/opentelemetry/sdk/configurator.rb, sdk/test/opentelemetry/sdk/configurator_test.rb
Follow up from https://github.com/open-telemetry/opentelemetry-ruby/pull/1129
https://github.com/open-telemetry/opentelemetry-specification/blob/v1.10.0/specification/protocol/exporter.md#specify-protocol
=> fix: warn on unsupported otlp transport protocols

.toys/.data/releases.yml
Fixes toys release error https://github.com/open-telemetry/opentelemetry-ruby/runs/5854957016?check_suite_focus=true
```console
Error: Missing version file /home/runner/work/opentelemetry-ruby/opentelemetry-ruby/registry/lib/opentelemetry/registry/version.rb for gem opentelemetry-registry
64
Version file /home/runner/work/opentelemetry-ruby/opentelemetry-ruby/registry/lib/opentelemetry/registry/version.rb for gem opentelemetry-registry didn't define OpenTelemetry::Registry::VERSION
65
```
=> fix: Registry Release config

sdk/lib/opentelemetry/sdk/internal.rb, sdk/test/opentelemetry/sdk/trace/span_test.rb
We ran into a pretty odd failure mode, which this patch will hopefully help address (h/t @ericmustin for sussing this out):
In an app, we set a span attribute value to an `ActiveSupport::Duration` instance.  So imagine something like `.in_span("foobar", { "baz" => 1.minute }`. When we viewed the span in various destinations, it the attribute showed up with the value as `nil` (or `null` or what have you). We saw the symptom (null attribute value, which is not allowed per the otel spec) before we sussed out the problem.
Turns out that, when exporting, the otlp exporter checks for a whitelist of exportable value classes that are pretty basic (code [here](https://github.com/open-telemetry/opentelemetry-ruby/blob/main/exporter/otlp/lib/opentelemetry/exporter/otlp/exporter.rb#L382-L398)). As a …
=> Only allow certain types of Numeric values as attribute values.

semantic_conventions/Rakefile, semantic_conventions/lib/opentelemetry/semantic_conventions/resource.rb, semantic_conventions/lib/opentelemetry/semantic_conventions/trace.rb, semantic_conventions/lib/opentelemetry/semantic_conventions/version.rb
This PR bumps the semantic_conventions gem to the 1.10.0 semantic conventions [release](https://github.com/open-telemetry/opentelemetry-specification/releases/tag/v1.10.0).
It's fairly uninteresting overall; but the commit messages have the full details and are replayed here for your convenience.
---
feat!: update for semantic conventions @ v1.10.0
The most notable thing here is that the delta between 1.8.0 and 1.10.0
results in a few fields going away. This will be a breaking change for
anyone who happens to be depending upon these fields:
- `DB_CASSANDRA_KEYSPACE`
- `DB_HBASE_NAMESPACE`
Users should instead use `DB_NAME`, according to
[open-telemetry/opentelemetry-specification#1973](https://github.com/open-telemetry/opentelemetry-specification/pull/1973).
Otherwise, we get the standard …
=> Bump semantic_conventions gem to 1.10.0

instrumentation/mysql2/CHANGELOG.md, instrumentation/mysql2/README.md, instrumentation/mysql2/lib/opentelemetry/instrumentation/mysql2.rb, instrumentation/mysql2/lib/opentelemetry/instrumentation/mysql2/patches/client.rb, instrumentation/mysql2/test/opentelemetry/instrumentation/mysql2/instrumentation_test.rb
As in `Redis` and `HTTP::ClientContext`, I'd like to use `with_attributes` to assign arbitrary attributes to spans generated within the `mysql2` instrumentation. Test coverage is light on the `*attributes` methods in `Mysql2` because it's a lightly modified copy/paste of [the redis instrumentation's implementation](https://github.com/open-telemetry/opentelemetry-ruby/blob/b7149fb72cad6c45956a6be80acfb2d062aab3a6/instrumentation/redis/lib/opentelemetry/instrumentation/redis.rb#L14). Happy to fill in test coverage if folks would prefer.
=> Add `with_attributes` context propagation for mysql2 instrumentation

examples/otel-collector/.env
Since `examples/otel-collector` might be the first contact for ruby developers with `otel-collector`, using the `contrib` docker image version in `OTELCOL_IMG` variable makes easier to explore the example with exporters included only on `contrib` docker image version (eg: datadog). It should not conflict with https://github.com/open-telemetry/opentelemetry-ruby/pull/970 since the image version still pinned.
=> chore: Updates opentelemetry-collector docker image

common/Gemfile, exporter/jaeger/Gemfile, exporter/jaeger/opentelemetry-exporter-jaeger.gemspec, exporter/otlp/Gemfile, exporter/otlp/opentelemetry-exporter-otlp.gemspec, exporter/zipkin/Gemfile, exporter/zipkin/opentelemetry-exporter-zipkin.gemspec, metrics_api/Gemfile, propagator/b3/Gemfile, propagator/jaeger/Gemfile, propagator/ottrace/Gemfile, propagator/ottrace/opentelemetry-propagator-ottrace.gemspec, propagator/ottrace/test/test_helper.rb, propagator/xray/Gemfile, registry/Gemfile, resource_detectors/Gemfile, sdk/Gemfile, semantic_conventions/Gemfile, test_helpers/Gemfile, test_helpers/opentelemetry-test-helpers.gemspec, test_helpers/test/test_helper.rb
Additional step to decouple the contrib packages from the main repo that are outside of the instrumentation directory
See open-telemetry/opentelemetry-ruby-contrib#1
=> chore: Remove Local Path Gem Dependencies

instrumentation/delayed_job/test/test_helper.rb
It is possible that a transitive require statement was removed in this PR https://github.com/rails/rails/pull/44340/files
It is likely that in most Rails production workloads this will not be a problem since the Rails Railtie requires `kernel/reporting`.
https://github.com/rails/rails/blob/8ace32c4ccdc760d17548de777b08c13bc9e07bd/railties/lib/rails.rb#L8
Fixes: https://github.com/open-telemetry/opentelemetry-ruby/issues/1234
cc: https://github.com/collectiveidea/delayed_job/issues/1168
=> fix: Rails 7.0.3 test suite incompatibility

exporter/otlp-common/test/opentelemetry/exporter/otlp/common/common_test.rb, exporter/otlp-grpc/.rubocop.yml, exporter/otlp-grpc/.yardopts, exporter/otlp-grpc/CHANGELOG.md, exporter/otlp-grpc/Gemfile, exporter/otlp-grpc/LICENSE, exporter/otlp-grpc/README.md, exporter/otlp-grpc/Rakefile, exporter/otlp-grpc/lib/opentelemetry-exporter-otlp-grpc.rb, exporter/otlp-grpc/lib/opentelemetry/exporter/otlp/grpc.rb, exporter/otlp-grpc/lib/opentelemetry/exporter/otlp/grpc/exporter.rb, exporter/otlp-grpc/lib/opentelemetry/exporter/otlp/grpc/version.rb, exporter/otlp-grpc/opentelemetry-exporter-otlp-grpc.gemspec, exporter/otlp-grpc/test/.rubocop.yml, exporter/otlp-grpc/test/opentelemetry/exporter/otlp/grpc/exporter_test.rb, exporter/otlp-grpc/test/test_helper.rb, exporter/otlp-http/test/opentelemetry/exporter/otlp/http/exporter_test.rb, exporter/otlp/test/opentelemetry/exporter/otlp/exporter_test.rb, test_helpers/lib/opentelemetry/test_helpers.rb
Implements a starting point for a OTLP via GRPC exporter.  This implementation currently has no error handling, and must not be considered production ready.
Follow on from https://github.com/open-telemetry/opentelemetry-ruby/pull/1179
=> feat: Otlp grpc

common/lib/opentelemetry/common/utilities.rb, common/opentelemetry-common.gemspec, common/test/opentelemetry/common/utilities_test.rb, common/test/test_helper.rb
https://github.com/open-telemetry/opentelemetry-ruby/pull/1180#discussion_r874159643
- config_opt is repeated in 4 places
- invalid_url? is repeated in 5 places
=> Feat: Add url, and config_opt helpers

exporter/jaeger/lib/opentelemetry/exporter/jaeger/collector_exporter.rb, exporter/jaeger/opentelemetry-exporter-jaeger.gemspec, exporter/otlp-grpc/lib/opentelemetry/exporter/otlp/grpc/exporter.rb, exporter/otlp-grpc/opentelemetry-exporter-otlp-grpc.gemspec, exporter/otlp-http/lib/opentelemetry/exporter/otlp/http/exporter.rb, exporter/otlp-http/opentelemetry-exporter-otlp-http.gemspec, exporter/otlp/lib/opentelemetry/exporter/otlp/exporter.rb, exporter/otlp/opentelemetry-exporter-otlp.gemspec, exporter/zipkin/lib/opentelemetry/exporter/zipkin/exporter.rb, exporter/zipkin/opentelemetry-exporter-zipkin.gemspec
Follow up from https://github.com/open-telemetry/opentelemetry-ruby/pull/1263
Uses common utils for repeated methods.
=> Refactor: common exporter methods

exporter/otlp-grpc/lib/opentelemetry/exporter/otlp/grpc.rb, exporter/otlp-grpc/lib/opentelemetry/exporter/otlp/grpc/trace_exporter.rb, exporter/otlp-grpc/test/opentelemetry/exporter/otlp/grpc/trace_exporter_test.rb, exporter/otlp-http/lib/opentelemetry/exporter/otlp/http.rb, exporter/otlp-http/lib/opentelemetry/exporter/otlp/http/trace_exporter.rb, exporter/otlp-http/test/opentelemetry/exporter/otlp/http/trace_exporter_test.rb
https://github.com/open-telemetry/opentelemetry-ruby/pull/1179#issuecomment-1118988405
=> Refactor exporter naming

sdk/lib/opentelemetry/sdk/trace/tracer.rb, sdk/lib/opentelemetry/sdk/trace/tracer_provider.rb
There are 2 places in sdk, where checked mostly the same code parent_span_id and
trace_id base on parent_span's context.
Because there is no other places in gems,
that uses method `internal_start_span`, I left only logic 'internal_start_span' and removed unused attribute.
It is possible opposite: to have checking of context in `start_span`.
=> refactor: Remove duplication logic in start_span

instrumentation/sidekiq/Appraisals, instrumentation/sidekiq/lib/opentelemetry/instrumentation/sidekiq/middlewares/client/tracer_middleware.rb, instrumentation/sidekiq/lib/opentelemetry/instrumentation/sidekiq/middlewares/server/tracer_middleware.rb, instrumentation/sidekiq/lib/opentelemetry/instrumentation/sidekiq/patches/launcher.rb, instrumentation/sidekiq/lib/opentelemetry/instrumentation/sidekiq/patches/poller.rb, instrumentation/sidekiq/lib/opentelemetry/instrumentation/sidekiq/patches/processor.rb, instrumentation/sidekiq/test/helpers/mock_loader_new_launcher.rb, instrumentation/sidekiq/test/test_helper.rb
This PR:
- changes our config method to instrumentation_config. Sidekiq's new
Component module is mixed in in a lot of places, and that module
includes a config method that we very much do not want to overwrite.
- changes the MockLoader in our test suite to be compatible with Sidekiq
6.5.0. Starting in Sidekiq 6.5.0, Sidekiq accepts the Sidekiq singleton
as an argument to Launcher.new. It seems like this is an intermediate
step to making Sidekiq::Config its own class, which is planned for
Sidekiq 7.0.
- adds appraisals for sidekiq 6.4.0 and 6.5.0
=> fix: make sidekiq instrumentation compatible with sidekiq 6.5.0

README.md, website_docs/context-propagation.md
Updating docs links, as the page https://github.com/open-telemetry/opentelemetry-ruby/tree/main/instrumentation doesn't exist anymore.
=> Fix broken links

.github/workflows/ci.yml
@robertlaurin @fbogsany Merging this into #1267 will fix the CI failures for that PR.
=> ci: do not test otlp exporters on jruby

.toys/.data/releases.yml
This was missed in the great -contrib migration, and causes the "Update open releases" hook to fail on pushes to `main`.
=> fixup: remove active_model_serializers from releases.yml

exporter/otlp/lib/opentelemetry/exporter/otlp/exporter.rb, exporter/otlp/test/opentelemetry/exporter/otlp/exporter_test.rb
Addresses #1340 
>When using the OTEL_EXPORTER_OTLP_ENDPOINT env variable, if the endpoint contains a trailing /, the final URL becomes <endpoint>//v1/traces instead of <endpoint>/v1/traces and traces are not sent to the expected place. Other OTel exporter libraries (e.g. [Python](https://github.com/open-telemetry/opentelemetry-python/blob/dbcec9f3b143e4de424c16be9ecd19a16be3e630/exporter/opentelemetry-exporter-otlp-proto-http/src/opentelemetry/exporter/otlp/proto/http/trace_exporter/__init__.py#L181), [JS](https://github.com/open-telemetry/opentelemetry-js/blob/main/experimental/packages/otlp-exporter-base/src/util.ts#L59)) handle endpoints with or without a trailing / so it would be good to keep it consistent with the Ruby exporter as well.
- Added a check to see if the …
=> fix: `OTEL_EXPORTER_OTLP_ENDPOINT` appends the correct path with a trailing slash

.github/actions/test_gem/action.yml, .github/workflows/ci.yml, website_docs/getting-started.md
Does what it says on the tin. By "support" I mean "turn it on in CI and
see if everything works."
The compatibility list is actually a bit better than JRuby!
Notably, I needed to exclude the OTLP exporter to make tests pass. I'm
not certain it's a real bug; I just haven't tried to fix those test
failures yet.
---
For discussion: Do we actually even want this? I went down a rabbithole today and landed on truffleruby, and thought it might be neat to support it. It seems like it's broadly more compatible than JRuby to me. Digging through past issues and PRs, it looks like we've at least attempted to support this in the past, and then maybe accidentally dropped it over time.
=> feat: support truffleruby

exporter/otlp-http/README.md, exporter/otlp/README.md
By default the OTLP exporters use gzip for compression, as specified
with `default: 'gzip'` in the files linked below.
The `README.md` files of the exporter gems document no particular
default. This commit updates documentation of the compression env vars
to mention the default compression config value.
- Base exporter setting: https://github.com/open-telemetry/opentelemetry-ruby/blob/03e36cec755df97e08139494b85473a7ad547001/exporter/otlp/lib/opentelemetry/exporter/otlp/exporter.rb#L52
- HTTP exporter setting: https://github.com/open-telemetry/opentelemetry-ruby/blob/03e36cec755df97e08139494b85473a7ad547001/exporter/otlp-http/lib/opentelemetry/exporter/otlp/http/trace_exporter.rb#L39
=> docs: update exporter default compression setting

api/test/opentelemetry/baggage/propagation/text_map_propagator_test.rb
```
test/opentelemetry/baggage/propagation/text_map_propagator_test.rb:131:9: C: [Correctable] Style/EachForSimpleLoop: Use Integer#times for a simple loop which iterates a fixed number of times.
(0..180).each do |i|
^^^^^^^^^^^^^
test/opentelemetry/baggage/propagation/text_map_propagator_test.rb:142:7: C: [Correctable] Style/EachForSimpleLoop: Use Integer#times for a simple loop which iterates a fixed number of times.
(0...180).each do |i|
^^^^^^^^^^^^^^
```
=> chore: appease the cop

website_docs/_index.md
This PR contains changes for signal name consistency in the website doc.
Issue: https://github.com/open-telemetry/opentelemetry.io/issues/1121
=> Changed signal names for website docs

sdk/lib/opentelemetry/sdk/trace/span.rb, sdk/lib/opentelemetry/sdk/trace/span_limits.rb, sdk/test/opentelemetry/sdk/trace/span_limits_test.rb, sdk/test/opentelemetry/sdk/trace/span_test.rb
The spec allows for generic and more specific configuration of attribute length limits. https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/common/README.md#attribute-limits
However we are currently applying legacy and span specific attribute environment variables to the event attribute length limit.
`OTEL_EVENT_ATTRIBUTE_VALUE_LENGTH_LIMIT` should take priority over `OTEL_ATTRIBUTE_VALUE_LENGTH_LIMIT`.
`OTEL_SPAN_ATTRIBUTE_VALUE_LENGTH_LIMIT` and `OTEL_RUBY_SPAN_ATTRIBUTE_VALUE_LENGTH_LIMIT` should not configure the event attributes length limit.
Both span attribute length limit and event attribute length limit should use the more general `OTEL_ATTRIBUTE_VALUE_LENGTH_LIMIT` in the event a more specific configuration is not supplied.
=> fix: SpanLimits setting event attributes length limit

sdk/lib/opentelemetry/sdk/trace/export/in_memory_span_exporter.rb, sdk/lib/opentelemetry/sdk/trace/export/metrics_reporter.rb
Some usage examples I came across didn't have proper markup to allow them to be presented nicely in code blocks. This fixes that.
https://open-telemetry.github.io/opentelemetry-ruby/opentelemetry-sdk/v1.2.0/OpenTelemetry/SDK/Trace/Export/InMemorySpanExporter.html
https://open-telemetry.github.io/opentelemetry-ruby/opentelemetry-sdk/v1.2.0/OpenTelemetry/SDK/Trace/Export/MetricsReporter.html
=> docs: Improve formatting of usage examples in OpenTelemetry SDK rubydocs

.github/actions/test_gem/action.yml, .github/workflows/ci.yml
The `set-output` command is being deprecated, and so we need to migrate.
Per the guides, this looks like the easiest replacement.
See open-telemetry/opentelemetry-ruby#144 for more info.
=> ci: replace newly-deprecated commands in actions

test_helpers/.rubocop.yml, test_helpers/lib/opentelemetry/test_helpers.rb, test_helpers/opentelemetry-test-helpers.gemspec, test_helpers/test/.rubocop.yml
* enable all new cops by default
* Style/BracesAroundHashParameters was removed - see https://github.com/rubocop/rubocop/issues/7641
* LineLength changed group from Metrics to Layout
* disable Gemspec/RequireMFA
* autocorrect explicit block over yield
Partially addresses: https://github.com/open-telemetry/opentelemetry-ruby/issues/1321
=> chore: Upgrade rubocop 0.73 -> 1.3 for TestHelpers

semantic_conventions/.rubocop.yml, semantic_conventions/Rakefile, semantic_conventions/opentelemetry-semantic_conventions.gemspec
* Enable all new cops by default
* TrailingBlankLines cop was renamed to TrailingEmptyLines
* LineLength changed group from Metrics to Layout
* disable Gemspec/RequireMFA
* autocorrect slicing array from index until end
Partially addresses: https://github.com/open-telemetry/opentelemetry-ruby/issues/1321
=> chore: Upgrade rubocop 0.73 -> 1.3 for SemanticConventions

website_docs/api.md, website_docs/examples.md
This adds the Ruby version of https://github.com/open-telemetry/opentelemetry.io/issues/1808
=> Add API ref and Examples to docs sidebar

sdk_experimental/lib/opentelemetry/sdk/experimental.rb, sdk_experimental/lib/opentelemetry/sdk/trace/propagation/trace_context/response_text_map_propagator.rb, sdk_experimental/test/opentelemetry/sdk/trace/propagation/trace_context/response_text_map_propagator_test.rb
Adds a TextMapPropagator in the experimental SDK to inject `traceresponse` headers as defined in the [Trace Context][1] draft specification.
[Here is a gist][2] demonstrating the propagator, based off of the existing http server example from this repo.
[1]: https://w3c.github.io/trace-context/#traceresponse-header
[2]: https://gist.github.com/wperron/d2566b65785a5aa2b670d07ea4cbc07a
=> feat: Implement the Trace Response propagator

.toys/.data/releases.yml
To release the experimental SDK, I think we need to add to `releases.yml`.
=> Add experimental SDK to releases.yml

semantic_conventions/opentelemetry-semantic_conventions.gemspec, test_helpers/opentelemetry-test-helpers.gemspec
https://github.com/open-telemetry/opentelemetry-ruby/actions/runs/3759043711/jobs/6388124989
```
opentelemetry-semantic_conventions.gemspec:22:16: C: [Correctable] Style/RedundantConstantBase: Remove redundant ::.
spec.files = ::Dir.glob('lib/**/*.rb') +
^^
opentelemetry-semantic_conventions.gemspec:23:16: C: [Correctable] Style/RedundantConstantBase: Remove redundant ::.
::Dir.glob('*.md') +
```
```
opentelemetry-test-helpers.gemspec:22:16: C: [Correctable] Style/RedundantConstantBase: Remove redundant ::.
spec.files = ::Dir.glob('lib/**/*.rb') +
^^
opentelemetry-test-helpers.gemspec:23:16: C: [Correctable] Style/RedundantConstantBase: Remove redundant ::.
::Dir.glob('*.md') +
^^
```
=> chore: fix rubocop failures

api/lib/opentelemetry/trace/span.rb
In the SDK, this defaults to unset: https://github.com/open-telemetry/opentelemetry-ruby/blob/48eb8367c2eee15cc59d4f83ee137a9b931695fc/sdk/lib/opentelemetry/sdk/trace/span.rb#L19 In spec, it also notes that default is unset: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md#set-status.
I don't think  span status matters in the context of an API span, but this might reduce the chance of confusion.
=> Update docs about default span status

test_helpers/.rubocop.yml
```
Running RuboCop...
RuboCop failed!
Inspecting 8 files
.....C..
Offenses:
opentelemetry-test-helpers.gemspec:30:3: C: Gemspec/DevelopmentDependencies: Specify development dependencies in Gemfile.
spec.add_development_dependency 'opentelemetry-sdk'
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
opentelemetry-test-helpers.gemspec:31:3: C: Gemspec/DevelopmentDependencies: Specify development dependencies in Gemfile.
spec.add_development_dependency 'pry'
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
opentelemetry-test-helpers.gemspec:32:3: C: Gemspec/DevelopmentDependencies: Specify development dependencies in Gemfile.
spec.add_development_dependency 'pry-byebug' unless RUBY_ENGINE == 'jruby'
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
=> chore: quiet the cop

sdk_experimental/lib/opentelemetry/sdk/trace/samplers/consistent_probability_based.rb, sdk_experimental/lib/opentelemetry/sdk/trace/samplers/consistent_probability_tracestate.rb, sdk_experimental/lib/opentelemetry/sdk/trace/samplers/parent_consistent_probability_based.rb
This refactors the consistent probability sampler code to ease reuse in custom samplers that wish to interoperate with tracestate-based sampling. The primary change is to hoist pure functions from the concrete sampler classes into the included `ConsistentProbabilityTraceState` mixin. It also makes methods from that mixin `private` - they were accidentally `public` previously, although the entire module was marked `@api private`.
=> fix: Refactor consistent prob sampler for reuse

sdk_experimental/lib/opentelemetry/sdk/trace/samplers/consistent_probability_based.rb, sdk_experimental/test/opentelemetry/sdk/trace/samplers/consistent_probability_based_test.rb
In the consistent probability sampler, we cache the exponent of the next highest and next lowest negative power-of-two values, and the probability of the highest. E.g. for a probability of 0.1, the next highest negative power-of-two is 2**-3 (0.125) and the next lowest is 2**-4 (0.0625), and the probability of the higher value is the fraction of difference between the 0.0625 and 0.125 that is 0.1 - i.e. 0.1 - 0.0625 / 0.0625 = 0.6.
Unfortunately, we calculated the ceiling incorrectly in the current implementation. Because these are negative power-of-two exponents, the _smaller_ value is the _upper_ bound and the _larger_ value is the _lower_ bound. This corrects that error.
Relevant song: https://www.youtube.com/watch?v=Esdnbq4hxHo
=> fix: Consistent probability sampler init

metrics_api/opentelemetry-metrics-api.gemspec, semantic_conventions/.rubocop.yml
When running `gem build opentelemetry-metrics-api.gemspec` locally
I was getting the following warning messages:
WARNING:  description and summary are identical
WARNING:  open-ended dependency on bundler (>= 1.17, development) is not recommended
if bundler is semantically versioned, use:
add_development_dependency 'bundler', '~> 1.17'
WARNING:  open-ended dependency on opentelemetry-test-helpers (>= 0, development)
is not recommended
use a bounded requirement, such as '~> x.y'
WARNING:  See https://guides.rubygems.org/specification-reference/ for help
Successfully built RubyGem
Name: opentelemetry-metrics-api
Version: 0.0.1
File: opentelemetry-metrics-api-0.0.1.gem
This commit intends to fix them.
Also,
- Disable Gemspec/DevelopmentDependencies rubocop rule in semantic_conventions
- Sort …
=> fix: Warning messages from gem build

.github/workflows/ci.yml, api/test/opentelemetry/trace/tracestate_test.rb, sdk_experimental/lib/opentelemetry/sdk/trace/samplers/consistent_probability_tracestate.rb
=> Fix constant reference in ConsistentProbabilityTraceState

sdk_experimental/lib/opentelemetry/sdk/trace/samplers/consistent_probability_tracestate.rb, sdk_experimental/lib/opentelemetry/sdk/trace/samplers/parent_consistent_probability_based.rb, sdk_experimental/test/opentelemetry/sdk/trace/samplers/parent_consistent_probability_based_test.rb
The spec indicates that corrupt `r` values should be handled by the parent-based consistent probability sampler by setting an `r` value without a corresponding `p` value: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/tracestate-probability-sampling.md#example-handling-corrupt-r-value
The implementations in Java and Go both do this. We do not - we simply clear the `r` value. This PR fixes this behaviour.
=> fix: Set r in Parent CPS

exporter/otlp/lib/opentelemetry/exporter/otlp.rb
Potentially fixes https://github.com/open-telemetry/opentelemetry-ruby/issues/1457
`rake test` is failing for me on `main`
```
opentelemetry-ruby/exporter/otlp git/main
❯ rake test
/Users/jmorrell/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/google-protobuf-3.23.2-arm64-darwin/lib/google/protobuf/any_pb.rb:15: warning: assigned but unused variable - e
Coverage report generated for Unit Tests to /Users/jmorrell/workspace/opentelemetry-ruby/exporter/otlp/coverage. 161 / 353 LOC (45.61%) covered.
Stopped processing SimpleCov as a previous error not related to SimpleCov has been detected
/Users/jmorrell/workspace/opentelemetry-ruby/exporter/otlp/lib/opentelemetry/exporter/otlp/exporter.rb:38:in `<class:Exporter>': uninitialized constant OpenTelemetry::Exporter::OTLP::VERSION (NameError) …
```
=> Reverse the require order so that the VERSION is available to the exporter

sdk/opentelemetry-sdk.gemspec
In https://github.com/open-telemetry/opentelemetry-ruby/pull/1412, the SDK picked up a dependency on the `untraced?` method in `opentelemetry-common`, which was added in `0.19.7` (same PR) (https://github.com/open-telemetry/opentelemetry-ruby/blob/main/common/CHANGELOG.md#v0197--2023-05-30).
=> fix: SDK requires opentelemetry-common 0.19.7

exporter/otlp/Appraisals, exporter/otlp/opentelemetry-exporter-otlp.gemspec
GitHub still uses legacy versions of the protobuf gem. This makes it challenging to
upgrade to newer versions of the OTLP Exporter which only supports versions `~> 3.19`.
This change loosens the restrictions to allow GitHub to adopt newer versions of the protobuf
definitions using an older verson of the library.
~~This change explicitly skips 3.15 due to bugs like https://github.com/protocolbuffers/protobuf/issues/8337~~
=> chore(deps): Allow google-protobuf `~> 3.14`

.github/actions/test_gem/action.yml
I'm trying to use SimpleCov in #1509, but TruffleRuby raises an error about `Coverage.running?` not being implemented. There's a fix for this in TruffleRuby 22. 
TruffleRuby 22 isn't accessible with the `test_gem` action's current version of `ruby/setup-ruby`. However, TruffleRuby 23 is available on the latest `ruby/setup-ruby` version. Using `v1.152.0` fixed the problem.
Example action failure: https://github.com/open-telemetry/opentelemetry-ruby/actions/runs/5744430524/job/15570701339?pr=1509#step:7:150
=> chore: Raise test_gem ruby/setup-ruby version

exporter/otlp/test/opentelemetry/exporter/otlp/exporter_test.rb
The "OpenTelemetry::Exporter::OTLP::Exporter::#export#test_0017_translates all the things" test is failing on unrelated PRs in TruffleRuby. Issue #1507 exists to resolve the source of the flakiness.
=> test: Skip flaky truffleruby test

api/lib/opentelemetry/trace/tracer.rb
Follow up fix for https://github.com/open-telemetry/opentelemetry-ruby/pull/1492
```
ruby proc-call-vs-yield.rb
Warming up --------------------------------------
block.call     1.141M i/100ms
block + yield     1.202M i/100ms
unused block     1.495M i/100ms
yield     1.389M i/100ms
Calculating -------------------------------------
block.call     11.485M (± 1.4%) i/s -     58.175M in   5.066280s
block + yield     11.910M (± 1.6%) i/s -     60.089M in   5.046587s
unused block     14.945M (± 5.4%) i/s -     74.725M in   5.019902s
yield     14.068M (± 1.0%) i/s -     70.858M in   5.037486s
Comparison:
unused block: 14945101.0 i/s
yield: 14067574.6 i/s - same-ish: difference falls within error
block + yield: 11910103.8 i/s - 1.25x  slower
block.call: 11485071.3 i/s - 1.30x  slower
```
In the …
=> fix: in_span performance

.github/workflows/ci.yml, logs_api/lib/opentelemetry-logs-api.rb, logs_api/lib/opentelemetry/logs.rb, logs_api/lib/opentelemetry/logs/log_record.rb, logs_api/lib/opentelemetry/logs/logger.rb, logs_api/lib/opentelemetry/logs/logger_provider.rb, logs_api/opentelemetry-logs-api.gemspec, logs_api/test/.rubocop.yml, logs_api/test/opentelemetry/logs/logger_provider_test.rb, logs_api/test/opentelemetry/logs/logger_test.rb, logs_api/test/test_helper.rb
This PR provides an interface for:
* LoggerProvider
* Logger
* LogRecord
This API will be consumed by the forthcoming Logs SDK.
Follows specification version 1.23.0 
Relevant specs to this PR
* https://opentelemetry.io/docs/specs/otel/logs/bridge-api/ 
* https://opentelemetry.io/docs/specs/otel/logs/noop/
* https://opentelemetry.io/docs/specs/otel/logs/data-model/ (this is the source of the argument descriptions for Logger#create_log_record)
Closes: #1478
Closes: #1480
Closes: #1479
Closes: #1481
=> feat: Implement Logs Bridge API

api/benchmarks/id_generation_bench.rb, api/lib/opentelemetry/trace.rb
This improves the performance of span and trace ID generation by avoiding the loop overhead in the common case of `rand` returning a valid ID.
Benchmark results:
```
Comparison:
generate_trace_id_while:  8023027.6 i/s
generate_trace_id:  4328017.1 i/s - 1.85x slower
...
Comparison:
generate_span_id_while:  8364182.8 i/s
generate_span_id:  4382207.1 i/s - 1.91x slower
```
=> fix: Optimize span and trace ID generation

api/benchmarks/id_generation_bench.rb, sdk_experimental/lib/opentelemetry/sdk/trace/samplers/consistent_probability_tracestate.rb
This is a small performance improvement to the `generate_r` method for the consistent-probability sampler. This method generates a `r` value from the `trace_id`. The current implementation unnecessarily allocates a slice of the `trace_id` string. Using the `offset:` argument to `unpack1`, we can avoid this allocation.
Benchmark results:
```
Calculating -------------------------------------
generate_r      3.920M (± 0.4%) i/s -     19.654M
generate_r_in_place      4.596M (± 0.5%) i/s -     23.085M
Comparison:
generate_r_in_place:  4595613.7 i/s
generate_r:  3920215.1 i/s - 1.17x slower
```
=> fix: Small perf improvement to generate_r

registry/lib/opentelemetry/instrumentation/registry.rb
This PR resolves the following Rubocop offense:
```
lib/opentelemetry/instrumentation/registry.rb:74:20: C: [Correctable] Layout/MultilineMethodCallIndentation: Align &.instance with .detect on line 73.
&.instance
^^^^^^^^^^
```
=> chore: Rubocop alignment update

exporter/otlp-common/test/opentelemetry/exporter/otlp/common/common_test.rb, exporter/otlp-http/test/opentelemetry/exporter/otlp/http/trace_exporter_test.rb
This test is failing on unrelated PRs. Issue #1507 is created to resolve the source of the flakiness.
A test identical to the one fixed in #1512 has started failing in the `otlp-http suite. Since this test also exists in `otlp-common`, I've pre-emptively skipped it for truffleruby.
=> test: Skip flaky truffleruby tests

exporter/otlp/lib/opentelemetry/exporter/otlp/exporter.rb, exporter/otlp/test/opentelemetry/exporter/otlp/exporter_test.rb
This PR fixes the non spec compliant behavior outlined in #1505 :slightly_smiling_face: 
Fixes #1505
=> fix(exporter/otlp): align endpoint environment varaible handling with spec

sdk/lib/opentelemetry/sdk/trace/span.rb, sdk/test/opentelemetry/sdk/trace/span_test.rb
Fixes #1534
Note: this does not address Event or Link attribute limits (and, indeed, Event and Link limits), at least some of which are similarly non-compliant. I think we should refactor `trim_links` and `append_event` to use the `trim_span_attributes` method, but that needs to be changed to accept the limit as a parameter. I'd prefer to do that in a subsequent PR.
As a side-effect, trimming span attributes is faster. The old `set_attribute` is about 14% slower than the new code in simple benchmarks, and the old `trim_span_attributes` is about 28% slower than the new implementation.
=> fix: spec compliance for span attribute limit

sdk/lib/opentelemetry/sdk/internal.rb, sdk/lib/opentelemetry/sdk/trace/span.rb, sdk/lib/opentelemetry/sdk/trace/tracer_provider.rb
👋  I was investigating memory consumption from a GraphQL perspective and I found a few places I thought might be improved. In my benchmark, this improved the total memory consumption by 11% (17% of objects):
```diff 
- Total allocated: 1809805 bytes (15888 objects)
+ Total allocated: 1601789 bytes (13174 objects)
Total retained:  0 bytes (0 objects)
allocated memory by gem
-----------------------------------
-  1003824  opentelemetry-sdk-1.3.1
+   795648  opentelemetry-sdk-1.3.1
381029  graphql-2.1.6
194512  opentelemetry-api-1.2.3
189656  opentelemetry-instrumentation-graphql-0.26.7
35952  other
4288  racc-1.7.3
368  logger
136  monitor
40  set
```
<details>
<summary>otel_bench.rb</summary>
<p>
```ruby
require "bundler/inline"
gemfile(false) do
source "https://rubygems.org"
gem …
```
=> fix: Reduce allocations on GraphQL hot paths

exporter/jaeger/lib/opentelemetry/exporter/jaeger/encoder.rb
'Use reject instead of inverting select' on Encoder#encoded_process.
Discovered by a [failing job](https://github.com/open-telemetry/opentelemetry-ruby/actions/runs/7103999448/job/19337989114?pr=1548#step:5:335) in #1547 and #1548.
=> chore(rubocop): Style/InverseMethods

metrics_sdk/lib/opentelemetry/sdk/metrics/aggregation/explicit_bucket_histogram.rb, metrics_sdk/lib/opentelemetry/sdk/metrics/aggregation/sum.rb
In metrics aggregation explicit_bucket_histogram and sum, if the aggregation_temporality is delta, `@data_points` will be cleared at the end of appending time ([L39](https://github.com/open-telemetry/opentelemetry-ruby/blob/main/metrics_sdk/lib/opentelemetry/sdk/metrics/aggregation/explicit_bucket_histogram.rb#L39)), this will also clear the hdps since they are referenced (i.e. reference variables)
```ruby
h = { "a" => 1, "b" => 2, "c" => 3 }
hdps = h.each_value do |hdp|
#...
end
puts hdps # hdps => { "a" => 1, "b" => 2, "c" => 3 }
h.clear   # h => {}
puts hdps # hdps => {}
```
Changing the `hdps = @data_points.each_value do |hdp| ... end` to `hdps = @data_points.values.map do |hdp| ... end` also changes the data structure returned from collect (i.e. ExplicitBucketHistogram.collect) if …
=> fix: fix that metrics aggregation @data_points.clear will cause hdps cleared

.github/workflows/ci.yml
While reviewing some of the recent PRs related to metrics, I noticed the metrics_sdk specs aren't running on the ci.
This will not pass until #1532 is merged.
=> ci: Run metrics_sdk tests

.github/workflows/codeql.yml
CodeQL V1 has been deprecated. 
Run warnings: https://github.com/open-telemetry/opentelemetry-ruby/actions/runs/7130254094
Blog post: https://github.blog/changelog/2023-01-18-code-scanning-codeql-action-v1-is-now-deprecated/
Failing test fixed in: #1550
=> chore: Update codeql to v2

.github/actions/test_gem/action.yml, .github/workflows/release-hook-on-closed.yml, .github/workflows/release-hook-on-push.yml, .github/workflows/release-perform.yml, .github/workflows/release-request.yml, .github/workflows/release-retry.yml
This PR updates the ruby/setup-ruby action to the latest version, 1.165.1, in hopes that it'll unblock truffleruby installation issues in the CI. This also clears the path to add test runs for Ruby 3.3.
Related to #1558
=> chore: Update ruby/setup-ruby to 1.165.1

CODEOWNERS, README.md
@kaylareopelle has made a number of valuable contributions to opentelemetry-ruby and we'd like to promote her to approver. Here is a summary of her work:
- [PRs authored](https://github.com/open-telemetry/opentelemetry-ruby/pulls?q=author%3Akaylareopelle+is%3Apr)
- [PRs commented upon](https://github.com/open-telemetry/opentelemetry-ruby/issues?q=commenter%3Akaylareopelle++)
- [Issues opened](https://github.com/open-telemetry/opentelemetry-ruby/issues?q=is%3Aissue+author%3Akaylareopelle+)
- [Issues commented upon](https://github.com/open-telemetry/opentelemetry-ruby/issues?q=is%3Aissue+commenter%3Akaylareopelle+)
=> Add kaylareopelle to approvers

registry/lib/opentelemetry/instrumentation/registry.rb, registry/test/opentelemetry/instrumentation/registry_test.rb
Add new flag, `suppress_not_found`, to silence instrumentation that isn't found.
Separate out 'failed to install' from 'not found' in logs during install_all method
=> Make use_all config friendlier

exporter/otlp/lib/opentelemetry/exporter/otlp/exporter.rb, exporter/otlp/test/opentelemetry/exporter/otlp/exporter_test.rb
This PR attempts to address https://github.com/open-telemetry/opentelemetry-ruby/issues/1160.
The general idea is that:
- we can consider OTLP exporter failures to be errors worthy of handling once retries have been exhausted
- we should let the `handle_error` method decide whether or not these particular failures are important
- the uri is useful information in these failures
Not everyone has a metrics reporter installed, so some log-level visibility might be desirable.
Alternatively, we could `OpenTelemetry::Logger.warn` (or `.debug` or `info` whatever) in these scenarios. I'm happy with that outcome too. Or whatever other great ideas folks may have 😄.
=> Consider OTLP export failures handleable errors

sdk/lib/opentelemetry/sdk/trace/export/batch_span_processor.rb, sdk/test/opentelemetry/sdk/trace/export/batch_span_processor_test.rb
We report `buffer-full` dropped spans in two contexts: `on_finish` and `force_flush`. Since `force_flush` is used in specific contexts, I thought it would be useful to supply a label so that users can have visibility into that.
We could alternatively use the `reason` to disambiguate the two scenarios, rather than introducing a new tag.
=> Add context to metrics reporting of buffer-full events

logs_sdk/Gemfile, logs_sdk/lib/opentelemetry-logs-sdk.rb, logs_sdk/lib/opentelemetry/sdk/logs.rb, logs_sdk/lib/opentelemetry/sdk/logs/export.rb, logs_sdk/lib/opentelemetry/sdk/logs/log_record_processor.rb, logs_sdk/lib/opentelemetry/sdk/logs/logger.rb, logs_sdk/lib/opentelemetry/sdk/logs/logger_provider.rb, logs_sdk/opentelemetry-logs-sdk.gemspec, logs_sdk/test/.rubocop.yml, logs_sdk/test/opentelemetry/sdk/logs/logger_provider_test.rb, logs_sdk/test/test_helper.rb
Fulfills the [Logs SDK specs for Logger Provider](https://opentelemetry.io/docs/specs/otel/logs/sdk/#loggerprovider)
The Logger Provider implementation is drawn mainly from the Tracer Provider implementation, as they have very similar specs.
* [Tracer Provider specs](https://opentelemetry.io/docs/specs/otel/trace/sdk/#tracer-provider)
* [TracerProvider class](https://github.com/open-telemetry/opentelemetry-ruby/blob/main/sdk/lib/opentelemetry/sdk/trace/tracer_provider.rb) 
If merged, this PR would fulfill the following elements on the [spec-compliance-matrix for Logs](https://github.com/open-telemetry/opentelemetry-specification/blob/main/spec-compliance-matrix.md#logs)
Here are some other implementations of LoggerProvider for comparison:
* [Java …
=> feat: Create Logs SDK LoggerProvider

exporter/otlp-http/lib/opentelemetry/exporter/otlp/http/trace_exporter.rb, exporter/otlp/lib/opentelemetry/exporter/otlp/exporter.rb, exporter/zipkin/opentelemetry-exporter-zipkin.gemspec
Loading opentelemetry-exporter-otlp on ruby-3.3 now prints a warning:
.../lib/opentelemetry/exporter/otlp/exporter.rb:10: warning: csv
was loaded from the standard library, but will no longer be part
of the default gems since Ruby 3.4.0. Add csv to your Gemfile or
gemspec. Also contact author of opentelemetry-exporter-otlp-0.26.1
to add csv into its gemspec.
This commit fixes that by adding an explicit dependency from opentelemetry-exporter-otlp to the csv gem at version '~> 3.1' (ruby-3.0 bundles csv at 3.1.9).
=> fix: require csv for ruby-3.4 compatibility

Dockerfile
Current Dockerfile for building the docker container is 2.6.5-alpine3.10, which doesn't comply the requirement of new opentelemetry component that require ruby > 3.0.0. New contributor probably will have the issue of building the docker image if they run `docker compose run app`. 
```
$ docker compose run app
> [app 3/6] RUN gem update --system &&     gem install "bundler:2.0.2" &&     gem cleanup:                          
18.00 ERROR:  Error installing rubygems-update:                                                                      
18.00 	There are no versions of rubygems-update (= 3.5.5) compatible with your Ruby & RubyGems
18.00 	rubygems-update requires Ruby version >= 3.0.0. The current ruby version is 2.6.5.114.
18.00 ERROR:  While executing gem ... (NoMethodError)
18.00 …
```
=> fix: update ruby version to 3 and alpine to 3.13

sdk/lib/opentelemetry/sdk/trace/export/batch_span_processor.rb, sdk/test/opentelemetry/sdk/trace/export/batch_span_processor_test.rb
When we requeue spans for export after a timeout, we can inadvertently create a nested array in `@spans`. I believe that this behavior is unintentional, but I could be wrong.
An IRB session that sorta explains what I mean:
```irb
irb(main):001:0> x = [1,2]
=> [1, 2]
irb(main):002:0> x.unshift(*[3,4])
=> [3, 4, 1, 2]
irb(main):003:0> x.unshift([5,6])
=> [[5, 6], 3, 4, 1, 2]
```
=> Re-add spans to bsp @spans using splat operator

exporter/otlp/lib/opentelemetry/exporter/otlp/exporter.rb
Follow-on to https://github.com/open-telemetry/opentelemetry-ruby/pull/1565/files
`backoff?` is called to see if we should retry; we should not be logging a failure from here.
This PR reverts the error reporting of `backoff?` to it's pre-#1165 state.
=> don't log failure from backoff?

sdk/.rubocop.yml, sdk/lib/opentelemetry/sdk/trace/export/batch_span_processor.rb
Opentelemetry is utilized across numerous projects, and even minor performance variations can have a significant impact.
It's worth noting that the default rubocop style may not have been specifically crafted with performance considerations in mind.
According to benchmarks on my machine M1, it appears that `Numeric#positive?` is approximately 1.32 times slower than using the comparison operator (`number > 0`).
[benchmark script](https://codeberg.org/miry/samples/src/commit/7b250c2df1cc41cc588ff6ff5d2fd7765ffaddcb/ruby/positive.rb)
```
ruby 3.3.0 (2023-12-25 revision 5124f9ac75) +YJIT [arm64-darwin23]
Warming up --------------------------------------
compare with 0     1.000 i/100ms
positive?     1.000 i/100ms
Calculating -------------------------------------
compare with 0      3.153 (± …
```
=> chore: Replace positive? with comparison operator

metrics_sdk/lib/opentelemetry/sdk/metrics/export.rb, metrics_sdk/lib/opentelemetry/sdk/metrics/export/console_metric_pull_exporter.rb, metrics_sdk/test/integration/console_metric_pull_exporter.rb
Similar to the `OpenTelemetry::Trace::Export::ConsoleSpanExporter`, this PR creates a pull exporter for metrics that will output the exported data to the console. 
This export may be helpful when running an experiment in a development environment to inspect the data that would have been sent to an OTLP endpoint. This should not be used in production environments.
~~**Note:** One test will fail until #1532 is merged, but the tests will not run in the CI until #1546 is merged.~~
=> feat: Create ConsoleMetricPullExporter

.github/workflows/release-hook-on-closed.yml, .github/workflows/release-hook-on-push.yml, .github/workflows/release-perform.yml, .github/workflows/release-request.yml, .github/workflows/release-retry.yml, .toys/.toys.rb
Protects the release process from unexpected changes upstream by pinning the tools. These versions can be updated explicitly if we need future upstream updates.
=> chore: Pin toys and toys release scripts to a known good version

sdk/lib/opentelemetry/sdk/forwarding_logger.rb, sdk/test/opentelemetry/sdk/configurator_test.rb
Also added tests to verify the default forwarding logger level, and to make sure it actually forwards logs.
Fixes #1599
=> fix: ForwardingLogger should foward block param

exporter/otlp/lib/opentelemetry/exporter/otlp/exporter.rb, exporter/otlp/test/opentelemetry/exporter/otlp/exporter_test.rb
Serialization takes place during export and is a resource-intensive process; users may want to see how long it takes.
~~I had to prove to myself that the value returned from a block passed to a block-handling function will be returned from the block-handling function even when there's an `ensure` in that function (I was worried that something from the `ensure` block would be returned). For documentation, I'll reproduce that experiment here:~~
~~Given the Ruby~~
```ruby
def mymethod
"return from mymethod"
end
def wrap_mymethod
begin
yield
ensure
puts "Ensure ran within wrap_mymethod"
end
end
ret = wrap_mymethod { mymethod }
puts "Return value from `wrap_mymethod`: #{ret}"
```
~~Yields output:~~ 
```
ruby yield.rb
Ensure ran within wrap_mymethod
Return value from `wrap_mymethod`: return …
```
=> Record stats for serialization time

common/.rubocop.yml, common/lib/opentelemetry/common/utilities.rb, common/test/opentelemetry/common/utilities_test.rb
Support untraced usage in a non block structure https://github.com/open-telemetry/opentelemetry-ruby-contrib/pull/965#issuecomment-2099275533
=> feat: add untraced ctx method

README.md
This is a proposal to document the supported ruby versions in the README, so folks know what to expect.
=> docs: Add ruby compatibility documentation

.github/workflows/stale.yaml
Today, I noticed the stalebot is running regularly on my fork. I'm not sure if this is the best choice. 
Limiting it to the main repo will allow users to keep PRs they've prepped on their forks, but aren't ready to open on the main repo, free from interference. Plus, we might save some unnecessary GHA runs 🌲 🌎
=> ci: Prevent stale action runs on forks

metrics_api/README.md, metrics_sdk/README.md
During the SIG, we talked about including an issue to hold feedback related to the Metrics gems to keep the conversations in a centralized location.
This change updates the READMEs to include a link to issue #1662
=> chore: Add link to issue for feedback on Metrics gems

exporter/otlp-metrics/opentelemetry-exporter-otlp-metrics.gemspec
The OTLP metrics exporter fails to install for tests because the latest metrics SDK is newer than the previous version constraint. The rest of the gems are installed based on minor versions. Now metrics_sdk/metrics_api are in sync.
=> chore: Loosen metrics gems versions on otlp exporter

exporter/otlp-metrics/.rubocop.yml, exporter/otlp-metrics/lib/opentelemetry/exporter/otlp/metrics/metrics_exporter.rb, exporter/otlp-metrics/lib/opentelemetry/exporter/otlp/metrics/util.rb, exporter/otlp-metrics/lib/opentelemetry/exporter/otlp/metrics_exporter.rb, exporter/otlp-metrics/lib/opentelemetry/exporter/otlp/util.rb, metrics_api/lib/opentelemetry/metrics/instrument/counter.rb, metrics_api/lib/opentelemetry/metrics/instrument/histogram.rb, metrics_api/lib/opentelemetry/metrics/instrument/up_down_counter.rb, metrics_sdk/lib/opentelemetry/sdk/metrics/instrument/histogram.rb, metrics_sdk/lib/opentelemetry/sdk/metrics/instrument/up_down_counter.rb
Closes https://github.com/open-telemetry/opentelemetry-ruby/issues/1681
Closes https://github.com/open-telemetry/opentelemetry-ruby/issues/1678
=> Rubocop on metrics

logs_sdk/test/opentelemetry/sdk/logs/export/batch_log_record_processor_test.rb
Some tests in BatchLogRecordProcessor had timing issues due to the work method. Since we don't rely on that method for these tests, stub the work method to do nothing.
Co-authored-by: @tannalynn 
Closes #1701
**Note:** A few open PRs contain skips for these tests. The skips should be removed once this PR is merged.
=> test: Fix intermittent logs test failures

examples/metrics_sdk/README.md, examples/otel-collector/.env, examples/otel-collector/otel-collector-config.yaml
This exporter has been replaced by the debug exporter and will be removed soon
Related to https://github.com/open-telemetry/opentelemetry-collector/pull/11037
=> fix: update references to logging exporter

README.md
@kaylareopelle has made a number of contributions to OpenTelemetry Ruby in the form of PRs, PR reviews, issues, and backlog management. She has been doing the work of a maintainer for some time, and we'd like to make it official by promoting her to this role. Here is a summary of her work:
- [PRs authored](https://github.com/open-telemetry/opentelemetry-ruby/pulls?q=author%3Akaylareopelle+is%3Apr)
- [PRs commented upon](https://github.com/open-telemetry/opentelemetry-ruby/issues?q=commenter%3Akaylareopelle++)
- [Issues opened](https://github.com/open-telemetry/opentelemetry-ruby/issues?q=is%3Aissue+author%3Akaylareopelle+)
- [Issues commented upon](https://github.com/open-telemetry/opentelemetry-ruby/issues?q=is%3Aissue+commenter%3Akaylareopelle+)
=> chore: promote kaylareopelle to maintainer

exporter/otlp-common/test/opentelemetry/exporter/otlp/common/common_test.rb, exporter/otlp-http/test/opentelemetry/exporter/otlp/http/trace_exporter_test.rb, exporter/otlp-metrics/test/opentelemetry/exporter/otlp/metrics/metrics_exporter_test.rb, exporter/otlp/test/opentelemetry/exporter/otlp/exporter_test.rb
`Zlib.gzip` adds a timestamp, which may be different than the one in the encoded `req.body` due to the time difference between the request and the assertion. This caused intermittent an failure. 
To resolve the problem, compare the unzipped request body with the `encoded_estr` to avoid Zlib timestamp interference with the equality check.
Co-authored by @tannalynn 
Resolves #1507
=> test: Resolve Truffle ruby intermittent failures on exporters

logs_sdk/test/opentelemetry/sdk/logs/export/batch_log_record_processor_test.rb
The Logs SDK has an intermittent failure in the Windows OS for Ruby 3.2 related to the `work` method being run outside of its stub.
We have to instantiate the processor outside of the stub so that the stub can be applied to the processor, but the method we're stubbing runs on initialization, so we sometimes run out of expectations due to timing with thread generation.
If we explicitly set `OTEL_RUBY_BLRP_START_THREAD_ON_BOOT` to `false` for the `removes the older log records from the batch if full` test, the stubbed `work` method will not run outside of the stub block.
Co-authored by @tannalynn
=> test: Add workaround for Windows logs SDK test failure

exporter/otlp-metrics/lib/opentelemetry/exporter/otlp/metrics/metrics_exporter.rb, exporter/otlp-metrics/test/opentelemetry/exporter/otlp/metrics/metrics_exporter_test.rb, metrics_sdk/lib/opentelemetry/sdk/metrics/aggregation/histogram_data_point.rb, metrics_sdk/lib/opentelemetry/sdk/metrics/aggregation/number_data_point.rb
It's currently possible to have a `Counter` with a `Float` value, but this fails to export because the `NumberDataPoint` is always assumed to be an `Integer` for the purposes of ProtoBuf encoding. The `.proto` for a `NumberDataPoint` allows for a float value in the `as_double` key, so there should be no reason that we should not be able to support `Float` `Counter`s.
This commit adds support for `Float` values in `NumberDataPoint`, which in turn adds support for `Float` `Counter`s. I also updated the documentation in the structs for both `NumberDataPoint.value` and `HistogramDataPoint.sum` to match the expected type based on the `.proto`.
Adds a test to confirm that the metrics_exporter handles both `Integer` and `Float` values for a `NumberDataPoint`.
Noting the error message output …
=> fix: handle float value in NumberDataPoint

examples/http/Gemfile
The Faraday and Sinatra versions were very out of date. Dependabot noticed the Sinatra version had known vulnerabilities. This updates the Gemfile. The example has the same output.
=> chore: Update http example gems

.toys/.data/releases.yml, exporter/otlp-logs/README.md
This PR adds the following gems to the release.yml file:
* `opentelemetry-exporter-otlp-logs`
* `opentelemetry-logs-sdk`
* `opentelemetry-logs-api`
It also fixes a typo in the OTLP logs exporter README
=> chore: Prepare logs gems for release

exporter/otlp-metrics/lib/opentelemetry/exporter/otlp/metrics/metrics_exporter.rb, exporter/otlp-metrics/test/opentelemetry/exporter/otlp/metrics/metrics_exporter_test.rb, exporter/otlp-metrics/test/test_helper.rb
Support exporting gauge metrics from `OTLP::Metrics::MetricsExporter` now that support for `Gauge` instruments in `metrics_sdk` has been added (https://github.com/open-telemetry/opentelemetry-ruby/pull/1718)
=> feat: Gauge metrics exporter encoding

.toys/.data/releases.yml
This PR addresses #1792 , which was auto-opened after a "failed" release for #1791 .
Basically, our releases are controlled by the toys gem, which attempts to auto-determine which gems are candidates for release by looking at the git diff, and determining which files changed, and then associating files changed in directories to the gems associated with those directories. If a gem's directory contains a changed file, it creates a new release.
however, it's approach uses a naive `.start_with?` substring match to associate directories and file names.
https://github.com/dazuma/toys/blob/17ed449da8299f272b834470ff6b279a59e8070b/.toys/release/.lib/release_utils.rb#L436
In this case, we've made a change to files in exporter/otlp-metrics files (for the gem opentelemetry-exporter-otlp-metrics) but …
=> fix: add trailing slash to .toys releases.yml directory to prevent gem release mismatch

.toys/.data/releases.yml
Sync up with practices in contrib and link release commits to the OpenTelemetry bot
=> ci: Give credit to OTel bot

.github/workflows/fossa.yml
New FOSSA scans will run on forks and fail. This update prevents those runs.
=> ci: Run FOSSA only on main repo

exporter/otlp-metrics/README.md, exporter/otlp-metrics/lib/opentelemetry/exporter/otlp/metrics/util.rb, exporter/otlp-metrics/test/opentelemetry/exporter/otlp/metrics/metrics_exporter_test.rb
Closes: https://github.com/open-telemetry/opentelemetry-ruby/issues/1814
This issue won't cause any major breakdown since it's only for logging the error message.
If the change is valid, then it needs to be updated for all exporters.
=> fix: update out-of-date google-protobuf-any

.github/workflows/ci-markdownlint.yml
https://github.com/open-telemetry/opentelemetry-ruby-contrib/actions/runs/15105985424/job/42454773761#step:3:1 showed a warning for the markdownlint-check action:
```
Markdown Lint Check
Unexpected input(s) 'continue-on-error', valid inputs are ['config', 'fix', 'globs', 'separator']
```
According to the [docs](https://github.com/marketplace/actions/markdownlint-cli2-action) the continue-on-error configuration should be unindented.
Corresponding PR in contrib: https://github.com/open-telemetry/opentelemetry-ruby-contrib/pull/1544
=> ci: fix markdownlint-check config

exporter/otlp-metrics/lib/opentelemetry/exporter/otlp/metrics/metrics_exporter.rb, exporter/otlp-metrics/test/opentelemetry/exporter/otlp/metrics/metrics_exporter_test.rb, exporter/otlp-metrics/test/test_helper.rb
Adding support to otlp metrics exporter when recording histogram that use exponential histogram bucket.
When determining the instrument kind (e.g., via `as_otlp_metrics(metrics)`), OpenTelemetry Ruby typically uses `metrics.instrument_kind`. However, this approach doesn't work for exponential_histogram, so it needs to inspect the type of the data points instead. This is similar to how Python uses `isinstance(metric.data, ExponentialHistogramType)`. Refactoring the Ruby implementation to follow a similar pattern could be a potential improvement.
=> feat: add exponential histogram in otlp metrics exporter

logs_sdk/lib/opentelemetry/sdk/logs/configurator_patch.rb, logs_sdk/test/opentelemetry/sdk/logs/configurator_patch_test.rb
The OTLP logs exporter is available on RubyGems. This changes the default to match the other signals.
=> feat!: Set logs exporter default to OTLP

metrics_sdk/lib/opentelemetry/sdk/metrics/aggregation/exponential_bucket_histogram.rb, metrics_sdk/test/opentelemetry/sdk/metrics/aggregation/exponential_bucket_histogram_test.rb
During testing, we encountered scale values that exceeded the valid range (from 20 to -10), which led to huge bucket size when rescaling occurred during aggregation. To address this, we added explicit validation to ensure the scale remains within the allowed range. If the scale is out of bounds, an exception is raised, but it will not interrupt the application or metrics collection process.
**Sample error output:**
```
E, [2025-07-09T17:27:13.800435 #50669] ERROR -- : OpenTelemetry error: Scale 30 is larger than maximal scale 20 - /usr/local/bundle/gems/opentelemetry-metrics-sdk-0.7.3/lib/opentelemetry/sdk/metrics/aggregation/exponential_bucket_histogram.rb:217:in `validate_scale'
```
Updated the default parameter to a new constant named `DEFAULT_*` to avoid confusion that the default is …
=> fix: validate scale range and raise exception if out of bounds

metrics_api/lib/opentelemetry/metrics/meter.rb, metrics_sdk/lib/opentelemetry/sdk/metrics/meter.rb, metrics_sdk/test/opentelemetry/sdk/metrics/meter_test.rb
The current specification states that the max instrument length is 255 chars:
https://opentelemetry.io/docs/specs/otel/metrics/api/#instrument-name-syntax
This commit updates the Ruby sdk to reflect this!
=> fix: Update max instrument length from 63 to 255

logs_sdk/lib/opentelemetry/sdk/logs/log_record_limits.rb, logs_sdk/test/opentelemetry/sdk/logs/log_record_limits_test.rb
Previously, the configuration option for managing log record attributes spelled log record with an underscore, `LOG_RECORD`. However, the spec does not use an underscore, `LOGRECORD`. Now, both spellings will be checked to set the value, with `LOGRECORD` taking precedence.
**Alternatively,** since the logs work is still technically "In Development" we could remove the `LOG_RECORD_ATTRIBUTE_*` environment variables and mark this PR as a breaking change.
=> feat!: Add OTEL_LOGRECORD_ATTRIBUTE_* env vars; Remove OTEL_LOG_RECORD_ATTRIBUTE_* env vars

.github/workflows/fossa.yml
Shell script will loop through all the available Gemfiles in this repository and create Gemfile.lock files without actually installing these gems. Folder */examples/* has been vomited.
FOSSA is intelligent enough to read nested directories and generate the report based on lock files.
=> ci: Fix FOSSA scans by generating Gemfile.lock files before scanning

metrics_sdk/lib/opentelemetry/sdk/metrics/aggregation/exponential_bucket_histogram.rb, metrics_sdk/test/opentelemetry/sdk/metrics/aggregation/exponential_bucket_histogram_test.rb
This fix addresses an issue where providing a value of 0 followed by a value that doesn’t trigger rescaling kept the exponential histogram’s scale at 0, causing the data to be omitted from export (e.g. 0,10000). Following the [Python implementation](https://github.com/open-telemetry/opentelemetry-python/blob/v1.36.0/opentelemetry-sdk/src/opentelemetry/sdk/metrics/_internal/aggregation.py#L790), the scale is now set outside the downscale logic.
=> fix: use mapping scale outside rescale logic
