open-telemetry/opentelemetry-ruby

api/Rakefile
api/lib/opentelemetry.rb
api/lib/opentelemetry/distributed_context/manager.rb
api/lib/opentelemetry/metrics/meter.rb
api/lib/opentelemetry/trace/tracer.rb
api/opentelemetry.gemspec
api/test/.rubocop.yml
api/test/opentracing_test.rb
api/test/test_helper.rb

Minor test and docs improvements for main OpenTelemetry module

---

api/lib/opentelemetry/trace/span.rb
api/test/opentracing/trace/span_test.rb

Based on https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/tracing-api.md
Extracted span docs commit from #23

Add docs to Span

---

api/lib/opentelemetry/trace.rb
api/lib/opentelemetry/trace/span.rb
api/lib/opentelemetry/trace/status.rb

Implement Status

---

api/lib/opentelemetry/trace/span.rb
api/test/opentelemetry/trace/span_test.rb
sdk/lib/opentelemetry/sdk/trace/export/batch_span_processor.rb
sdk/lib/opentelemetry/sdk/trace/export/simple_span_processor.rb
sdk/lib/opentelemetry/sdk/trace/multi_span_processor.rb
sdk/lib/opentelemetry/sdk/trace/noop_span_processor.rb
sdk/lib/opentelemetry/sdk/trace/span.rb
sdk/test/opentelemetry/sdk/trace/export/batch_span_processor_test.rb
sdk/test/opentelemetry/sdk/trace/export/simple_span_processor_test.rb
sdk/test/opentelemetry/sdk/trace/span_test.rb
sdk/test/opentelemetry/sdk/trace/tracer_test.rb

See https://github.com/open-telemetry/opentelemetry-specification/pull/290

Shorten recording_events? to recording?

---

api/lib/opentelemetry/trace/tracer.rb

Fixes #123
https://github.com/open-telemetry/opentelemetry-ruby/pull/118#issuecomment-542497023

Documentation: Update with explanations of Tracer methods

---

api/test/opentelemetry/distributed_context/propagation/http_text_format_test.rb
api/test/opentelemetry/distributed_context/propagation/trace_parent_test.rb
api/test/opentelemetry/trace/event_test.rb
api/test/opentelemetry/trace/link_test.rb
api/test/opentelemetry/trace/span_context_test.rb
api/test/opentelemetry/trace/span_test.rb
api/test/opentelemetry/trace/status_test.rb
api/test/opentelemetry/trace/trace_flags_test.rb
api/test/opentelemetry_test.rb
sdk/test/opentelemetry/sdk/resources/resource_test.rb
sdk/test/opentelemetry/sdk/trace/export/batch_span_processor_test.rb
sdk/test/opentelemetry/sdk/trace/export/in_memory_span_exporter_test.rb
sdk/test/opentelemetry/sdk/trace/export/multi_span_exporter_test.rb
sdk/test/opentelemetry/sdk/trace/export/noop_span_exporter_test.rb
sdk/test/opentelemetry/sdk/trace/samplers/result_test.rb
sdk/test/opentelemetry/sdk/trace/samplers_test.rb
sdk/test/opentelemetry/sdk/trace/span_test.rb
sdk/test/opentelemetry/sdk/trace/tracer_test.rb

This PR fixes Minitest 6 deprecation warnings.

Fix minitest 6 deprecation warnings

---

README.md

Update README: installation guide

---

adapters/concurrent_ruby/opentelemetry-adapters-concurrent_ruby.gemspec
adapters/net_http/opentelemetry-adapters-net_http.gemspec
adapters/restclient/opentelemetry-adapters-restclient.gemspec

Dashes, underscores, and combinations thereof are fun.

more gemspec fixes

---

adapters/sidekiq/LICENSE

Sidekiq needs a license so we can build the gem ;)

Add license for sidekiq

---

adapters/excon/README.md
adapters/excon/opentelemetry-adapters-excon.gemspec

This adds documentation for the excon adapter, closing #236.

Add excon readme

---

adapters/sinatra/lib/opentelemetry/adapters/sinatra/middlewares/tracer_middleware.rb
adapters/sinatra/test/opentelemetry/adapters/sinatra_test.rb

Hello, this PR fixes https://github.com/open-telemetry/opentelemetry-ruby/issues/274
Please let me know if anything I've missed in regards to testing setup or code style!

account for missing sinatra route and add test

---

exporters/jaeger/lib/opentelemetry/exporters/jaeger/exporter.rb
exporters/jaeger/test/opentelemetry/exporters/jaeger/exporter_test.rb
sdk/lib/opentelemetry/sdk/trace/export.rb
sdk/lib/opentelemetry/sdk/trace/export/batch_span_processor.rb
sdk/lib/opentelemetry/sdk/trace/export/console_span_exporter.rb
sdk/lib/opentelemetry/sdk/trace/export/in_memory_span_exporter.rb
sdk/lib/opentelemetry/sdk/trace/export/multi_span_exporter.rb
sdk/lib/opentelemetry/sdk/trace/export/noop_span_exporter.rb
sdk/test/opentelemetry/sdk/trace/export/batch_span_processor_test.rb
sdk/test/opentelemetry/sdk/trace/export/console_span_exporter_test.rb
sdk/test/opentelemetry/sdk/trace/export/in_memory_span_exporter_test.rb
sdk/test/opentelemetry/sdk/trace/export/multi_span_exporter_test.rb
sdk/test/opentelemetry/sdk/trace/export/noop_span_exporter_test.rb

Remove retryable failure code

---

instrumentation/rack/lib/opentelemetry/instrumentation.rb

Just discovered that by chance.

Fix module typo in the rack instrumentation

---

sdk/lib/opentelemetry/sdk/trace/config/trace_config.rb
sdk/test/integration/api_trace_test.rb
sdk/test/integration/global_tracer_configurations_test.rb
sdk/test/opentelemetry/sdk/trace/tracer_test.rb

See open-telemetry/opentelemetry-specification#750 and associated issue open-telemetry/opentelemetry-specification#728

Change default Sampler to ParentOrElse(AlwaysOn)

---

api/lib/opentelemetry/correlation_context/propagation.rb
api/lib/opentelemetry/correlation_context/propagation/text_map_extractor.rb
api/lib/opentelemetry/correlation_context/propagation/text_map_injector.rb
api/lib/opentelemetry/trace/propagation/trace_context.rb
api/lib/opentelemetry/trace/propagation/trace_context/text_map_extractor.rb
api/lib/opentelemetry/trace/propagation/trace_context/text_map_injector.rb
api/test/opentelemetry/correlation_context/propagation_test.rb
api/test/opentelemetry/correlation_context/text_extractor_test.rb
api/test/opentelemetry/correlation_context/text_injector_test.rb
api/test/opentelemetry/trace/propagation/trace_context/text_extractor_test.rb
api/test/opentelemetry/trace/propagation/trace_context/text_injector_test.rb
api/test/opentelemetry/trace/propagation/trace_context/trace_context_test.rb
instrumentation/ethon/test/opentelemetry/instrumentation/ethon/instrumentation_test.rb
instrumentation/excon/test/opentelemetry/instrumentation/excon/instrumentation_test.rb
instrumentation/faraday/test/opentelemetry/instrumentation/faraday/middlewares/tracer_middleware_test.rb
instrumentation/net_http/test/opentelemetry/instrumentation/net/http/instrumentation_test.rb
instrumentation/restclient/test/opentelemetry/instrumentation/restclient/instrumentation_test.rb
sdk/lib/opentelemetry/sdk/configurator.rb
sdk/test/opentelemetry/sdk/configurator_test.rb

Rename Text* to TextMap* (propagators)

---

api/test/opentelemetry/trace/tracer_provider.rb
examples/http/client.rb
examples/http/server.rb
sdk/lib/opentelemetry/sdk/resources/resource.rb
sdk/test/opentelemetry/sdk/configurator_test.rb
sdk/test/opentelemetry/sdk/resources/resource_test.rb
sdk/test/opentelemetry/sdk/trace/tracer_provider_test.rb
sdk/test/opentelemetry/sdk/trace/tracer_test.rb

See https://github.com/open-telemetry/opentelemetry-specification/pull/873

Remove semver prefix

---

sdk/Gemfile
sdk/lib/opentelemetry/sdk/trace/export/batch_span_processor.rb
sdk/test/opentelemetry/sdk/trace/export/batch_span_processor_test.rb

See https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/sdk-environment-variables.md#batch-span-processor
Related: #337

BatchSpanProcessor environment variable support

---

.github/workflows/ci.yml
.toys/.data/releases.yml
docker-compose.yml
instrumentation/dalli/.rubocop.yml
instrumentation/dalli/Appraisals
instrumentation/dalli/Gemfile
instrumentation/dalli/LICENSE
instrumentation/dalli/Rakefile
instrumentation/dalli/example/Gemfile
instrumentation/dalli/example/dalli.rb
instrumentation/dalli/lib/opentelemetry-instrumentation-dalli.rb
instrumentation/dalli/lib/opentelemetry/instrumentation.rb
instrumentation/dalli/lib/opentelemetry/instrumentation/dalli.rb
instrumentation/dalli/lib/opentelemetry/instrumentation/dalli/instrumentation.rb
instrumentation/dalli/lib/opentelemetry/instrumentation/dalli/patches/server.rb
instrumentation/dalli/lib/opentelemetry/instrumentation/dalli/utils.rb
instrumentation/dalli/lib/opentelemetry/instrumentation/dalli/version.rb
instrumentation/dalli/opentelemetry-instrumentation-dalli.gemspec
instrumentation/dalli/test/.rubocop.yml
instrumentation/dalli/test/opentelemetry/instrumentation/dalli/instrumentation_test.rb
instrumentation/dalli/test/test_helper.rb

Closes https://github.com/open-telemetry/opentelemetry-ruby/issues/244

Add Dalli instrumentation gem

---

instrumentation/redis/README.md

Documentation for Redis Instrumentation. Very similar documentation as others such as PR #386 . This hopefully resolves issue #240.

added redis instrumentation documentation

---

sdk/lib/opentelemetry/sdk/configurator.rb

docs: fix Configurator#add_span_processor

---

instrumentation/sinatra/lib/opentelemetry/instrumentation/sinatra/middlewares/tracer_middleware.rb

This solves most of what is being asked for in #408

fix: default to sinatra.route for span name

---

api/lib/opentelemetry/trace/status.rb
api/test/opentelemetry/trace/status_test.rb
exporter/jaeger/lib/opentelemetry/exporter/jaeger/encoder.rb
exporter/otlp/lib/opentelemetry/exporter/otlp/exporter.rb
instrumentation/ethon/test/opentelemetry/instrumentation/ethon/instrumentation_test.rb
instrumentation/excon/test/opentelemetry/instrumentation/excon/instrumentation_test.rb
instrumentation/mysql2/test/opentelemetry/instrumentation/mysql2/instrumentation_test.rb
instrumentation/net_http/test/opentelemetry/instrumentation/net/http/instrumentation_test.rb
instrumentation/rack/test/opentelemetry/instrumentation/rack/middlewares/tracer_middleware_test.rb
instrumentation/redis/test/opentelemetry/instrumentation/redis/instrumentation_test.rb
instrumentation/sinatra/test/opentelemetry/instrumentation/sinatra_test.rb
sdk/test/opentelemetry/sdk/trace/span_test.rb
sdk/test/opentelemetry/sdk/trace/tracer_test.rb

See https://github.com/open-telemetry/opentelemetry-specification/pull/1081

fix!: remove 'canonical' from status codes

---

exporter/otlp/lib/opentelemetry/exporter/otlp/exporter.rb
exporter/otlp/test/opentelemetry/exporter/otlp/exporter_test.rb

fix: add gzip support to OTLP exporter

---

common/Gemfile
common/opentelemetry-common.gemspec

fix: common gem should depend on api gem

---

instrumentation/all/lib/opentelemetry/instrumentation/all.rb
instrumentation/rails/lib/opentelemetry-instrumentation-rails.rb

fix: otel-instrumentation-all not installing all

---

instrumentation/active_model_serializers/lib/opentelemetry/instrumentation/active_model_serializers/instrumentation.rb
instrumentation/active_model_serializers/test/opentelemetry/instrumentation/active_model_serializers_test.rb

Small fix for the `active_model_serializers` instrumentation.

fix: active_model_serializers installer

---

instrumentation/dalli/lib/opentelemetry/instrumentation/dalli/patches/server.rb
instrumentation/dalli/test/opentelemetry/instrumentation/dalli/instrumentation_test.rb

Add dalli peer service

---

instrumentation/mysql2/lib/opentelemetry/instrumentation/mysql2/patches/client.rb
instrumentation/mysql2/test/opentelemetry/instrumentation/mysql2/instrumentation_test.rb

https://github.com/open-telemetry/opentelemetry-ruby/issues/421

feat: add peer service config to mysql

---

instrumentation/redis/lib/opentelemetry/instrumentation/redis/patches/client.rb
instrumentation/redis/test/opentelemetry/instrumentation/redis/instrumentation_test.rb

https://github.com/open-telemetry/opentelemetry-ruby/issues/421

feat: accept config for redis peer service attribute

---

sdk/lib/opentelemetry/sdk/trace/config/trace_config.rb
sdk/test/opentelemetry/sdk/trace/config/trace_config_test.rb

Implements https://github.com/open-telemetry/opentelemetry-specification/pull/1322

fix: define default value for traceid ratio

---

instrumentation/active_model_serializers/lib/opentelemetry/instrumentation/active_model_serializers/instrumentation.rb
instrumentation/active_model_serializers/test/opentelemetry/instrumentation/active_model_serializers_test.rb
instrumentation/delayed_job/lib/opentelemetry/instrumentation/delayed_job/instrumentation.rb
instrumentation/delayed_job/test/opentelemetry/instrumentation/delayed_job_test.rb
instrumentation/mongo/lib/opentelemetry/instrumentation/mongo/instrumentation.rb
instrumentation/mongo/test/opentelemetry/instrumentation/mongo_test.rb

Followup from this comment https://github.com/open-telemetry/opentelemetry-ruby/pull/546#discussion_r556004413

Use compatible checks

---

sdk/lib/opentelemetry/sdk/configurator.rb
sdk/lib/opentelemetry/sdk/resources/resource.rb
sdk/test/opentelemetry/sdk/resources/resource_test.rb

See: https://github.com/open-telemetry/opentelemetry-specification/pull/1345

fix: Resource.merge consistency

---

exporter/jaeger/lib/opentelemetry/exporter/jaeger/encoder.rb

See https://github.com/open-telemetry/opentelemetry-specification/pull/1374

fix: Jaeger ref type should be FOLLOWS_FROM

---

exporter/otlp/lib/opentelemetry/exporter/otlp/exporter.rb

See https://github.com/open-telemetry/opentelemetry-specification/pull/1362

fix: rename OTLP env vars SPAN -> TRACES

---

instrumentation/delayed_job/CHANGELOG.md

Add missed CHANGELOG item for Delayed Job in v0.13.0

---

instrumentation/rack/lib/opentelemetry/instrumentation/rack/middlewares/tracer_middleware.rb
instrumentation/rack/test/opentelemetry/instrumentation/rack/middlewares/tracer_middleware_test.rb

Adds the ability to specific certain paths to be untraced.  The example used in test is a health check ping that you may not want instrumented.

feat: Add untraced endpoints config to rack middleware

---

sdk/lib/opentelemetry/sdk/trace/config/trace_config.rb
sdk/test/opentelemetry/sdk/trace/config/trace_config_test.rb

See: https://github.com/open-telemetry/opentelemetry-specification/pull/1382

fix: OTEL_TRACE -> OTEL_TRACES env vars

---

sdk/lib/opentelemetry/sdk/trace/config/trace_config.rb
sdk/test/opentelemetry/sdk/trace/config/trace_config_test.rb

See https://github.com/open-telemetry/opentelemetry-specification/pull/1429

fix: change limits from 1000 to 128

---

api/lib/opentelemetry/trace/span.rb
sdk/lib/opentelemetry/sdk/trace/span.rb

docs: clarify nil attribute values not allowed

---

sdk/lib/opentelemetry/sdk/trace/tracer_provider.rb
sdk/test/opentelemetry/sdk/trace/tracer_provider_test.rb

See https://github.com/open-telemetry/opentelemetry-specification/pull/1452

feat: add force_flush to SDK's TracerProvider

---

exporter/jaeger/lib/opentelemetry/exporter/jaeger/agent_exporter.rb
exporter/jaeger/lib/opentelemetry/exporter/jaeger/collector_exporter.rb
exporter/otlp/lib/opentelemetry/exporter/otlp/exporter.rb
sdk/lib/opentelemetry/sdk/trace/export/batch_span_processor.rb
sdk/lib/opentelemetry/sdk/trace/export/console_span_exporter.rb
sdk/lib/opentelemetry/sdk/trace/export/in_memory_span_exporter.rb
sdk/lib/opentelemetry/sdk/trace/export/multi_span_exporter.rb
sdk/lib/opentelemetry/sdk/trace/export/noop_span_exporter.rb
sdk/lib/opentelemetry/sdk/trace/export/simple_span_processor.rb
sdk/test/opentelemetry/sdk/trace/export/batch_span_processor_test.rb
sdk/test/opentelemetry/sdk/trace/export/console_span_exporter_test.rb
sdk/test/opentelemetry/sdk/trace/export/simple_span_processor_test.rb

See: https://github.com/open-telemetry/opentelemetry-specification/pull/1467

feat!: implement Exporter#force_flush

---

sdk/lib/opentelemetry/sdk.rb
sdk/test/opentelemetry/sdk_test.rb

fix: improve configuration error reporting

---

instrumentation/sidekiq/lib/opentelemetry/instrumentation/sidekiq/instrumentation.rb
instrumentation/sidekiq/lib/opentelemetry/instrumentation/sidekiq/middlewares/client/tracer_middleware.rb
instrumentation/sidekiq/lib/opentelemetry/instrumentation/sidekiq/middlewares/server/tracer_middleware.rb
instrumentation/sidekiq/lib/opentelemetry/instrumentation/sidekiq/patches/launcher.rb
instrumentation/sidekiq/lib/opentelemetry/instrumentation/sidekiq/patches/poller.rb
instrumentation/sidekiq/lib/opentelemetry/instrumentation/sidekiq/patches/processor.rb
instrumentation/sidekiq/test/opentelemetry/instrumentation/sidekiq/instrumentation_test.rb
instrumentation/sidekiq/test/opentelemetry/instrumentation/sidekiq/patches/launcher_test.rb
instrumentation/sidekiq/test/opentelemetry/instrumentation/sidekiq/patches/poller_test.rb
instrumentation/sidekiq/test/opentelemetry/instrumentation/sidekiq/patches/processor_test.rb

I added the `peer_service` option to sidekiq instrumentation
Related to #421

feat: accept config for sidekiq peer service attribute

---

docker-compose.yml
examples/http/README.md
examples/http/client.rb
examples/http/server.rb
examples/http/start_server.sh

This example now runs without docker-compose, which was adding
complexity without really adding value.

fix: Clean up HTTP example.

---

.github/workflows/ci.yml

Somehow my bad merge on my last PR made it past code review. This should fix it.

Fix broken ci.yml.

---

.toys/.data/releases.yml

Fix: broken instrumentation base version path

---

instrumentation/pg/CHANGELOG.md

Fix PG instrumentation changelog

---

api/lib/opentelemetry/trace/tracer.rb
api/test/opentelemetry/trace/tracer_test.rb
examples/http/server.rb
instrumentation/sidekiq/lib/opentelemetry/instrumentation/sidekiq/middlewares/server/tracer_middleware.rb
instrumentation/sinatra/lib/opentelemetry/instrumentation/sinatra/middlewares/tracer_middleware.rb
sdk/test/integration/api_trace_test.rb
sdk/test/integration/global_tracer_configurations_test.rb

Fixes #705. See #703 for more discussion.

fix!: remove optional parent_context from in_span

---

resource_detectors/lib/opentelemetry/resource/detectors/google_cloud_platform.rb
resource_detectors/test/opentelemetry/detectors/google_cloud_platform_test.rb
sdk/lib/opentelemetry/sdk/resources/constants.rb

See https://github.com/open-telemetry/opentelemetry-specification/pull/1495

fix: Rename cloud.zone to cloud.availability_zone

---

sdk/lib/opentelemetry/sdk/internal.rb
sdk/lib/opentelemetry/sdk/trace/span.rb
sdk/test/opentelemetry/sdk/trace/span_test.rb

fix: improve attribute error messages

---

api/lib/opentelemetry/trace/tracer.rb
api/test/opentelemetry/trace/tracer_test.rb
api/test/opentelemetry/trace_test.rb

fix: Reduce span allocation in API

---

.instrumentation_generator/instrumentation_generator.rb
.instrumentation_generator/templates/lib/instrumentation/instrumentation_name/version.rb.tt

https://github.com/open-telemetry/opentelemetry-ruby/pull/796#discussion_r647511725

Fix: instrumentation gen default version

---

sdk/lib/opentelemetry/sdk/resources/resource.rb
sdk/test/opentelemetry/sdk/resources/resource_test.rb

See https://github.com/open-telemetry/opentelemetry-specification/pull/1677

fix: support OTEL_SERVICE_NAME env var

---

sdk/lib/opentelemetry/sdk/trace/tracer.rb
sdk/test/opentelemetry/sdk/trace/tracer_provider_test.rb
sdk/test/opentelemetry/sdk/trace/tracer_test.rb

fix!: remove unnecessary readers from SDK Tracer

---

sdk/lib/opentelemetry/sdk/trace/tracer_provider.rb
sdk/test/opentelemetry/sdk/trace/tracer_provider_test.rb

Fixes https://github.com/open-telemetry/opentelemetry-ruby/issues/814

feat: add unnamed tracer warning message

---

exporter/otlp/lib/opentelemetry/exporter/otlp/exporter.rb
exporter/otlp/test/opentelemetry/exporter/otlp/exporter_test.rb

fix: rescue OpenSSL errors during export

---

sdk/lib/opentelemetry/sdk/trace/span.rb
sdk/test/opentelemetry/sdk/trace/span_test.rb
sdk/test/opentelemetry/sdk/trace/tracer_test.rb

closes https://github.com/open-telemetry/opentelemetry-ruby/issues/735

prune invalid links

---

instrumentation/dalli/lib/opentelemetry/instrumentation/dalli/instrumentation.rb
instrumentation/dalli/lib/opentelemetry/instrumentation/dalli/patches/server.rb
instrumentation/dalli/test/opentelemetry/instrumentation/dalli/instrumentation_test.rb

feat: add configuration options for dalli

---

instrumentation/lmdb/lib/opentelemetry/instrumentation/lmdb/instrumentation.rb
instrumentation/lmdb/lib/opentelemetry/instrumentation/lmdb/patches/database.rb
instrumentation/lmdb/test/instrumentation/lmdb/patches/database_test.rb

feat: configure db.statement toggle

---

instrumentation/redis/lib/opentelemetry/instrumentation/redis/instrumentation.rb
instrumentation/redis/lib/opentelemetry/instrumentation/redis/patches/client.rb
instrumentation/redis/test/opentelemetry/instrumentation/redis/patches/client_test.rb

feat: add toggle for redis db.statement attribute

---

instrumentation/mongo/test/opentelemetry/instrumentation/mongo/subscriber_test.rb
instrumentation/mongo/test/opentelemetry/instrumentation/mongo_test.rb

https://github.com/open-telemetry/opentelemetry-ruby/pull/906/checks?check_run_id=3314974013

fix: flakey mongo test

---

instrumentation/pg/README.md
instrumentation/pg/lib/opentelemetry/instrumentation/pg/instrumentation.rb
instrumentation/pg/lib/opentelemetry/instrumentation/pg/patches/connection.rb
instrumentation/pg/opentelemetry-instrumentation-pg.gemspec
instrumentation/pg/test/opentelemetry/instrumentation/pg/instrumentation_test.rb
instrumentation/pg/test/test_helper.rb

feat: add db_statement toggle for postgres

---

instrumentation/mysql2/README.md

docs: move to using new db_statement

---

exporter/otlp/lib/opentelemetry/exporter/otlp/exporter.rb

We were not capturing failures for a common failure path, we were also under
reporting failures on the final retry.

fix: OTLP exporter missing failure metrics

---

.github/workflows/codeql.yml

Second attempt!
Fixes https://github.com/open-telemetry/opentelemetry-ruby/issues/767
~The CodeQL Analysis Code scanning alerts will appear configured once it is merged into the upstream repository from the fork.~
https://github.com/open-telemetry/opentelemetry-ruby/security/code-scanning
🙇🏼 @sj

chore: Add CodeQL Actions Ruby Beta

---

instrumentation/sidekiq/opentelemetry-instrumentation-sidekiq.gemspec

Fix: Sidekiq dependabot warning

---

website_docs/getting_started.md
website_docs/manual_instrumentation.md

Contributes to https://github.com/open-telemetry/opentelemetry.io/issues/908
/cc @austinlparker

[website_docs] Link to website spec pages

---

exporter/otlp/lib/opentelemetry/exporter/otlp/exporter.rb

Extracts the connection setup into its own method to allow for overriding.

refactor: http connection setup

---

instrumentation/koala/Appraisals
instrumentation/koala/Gemfile

Followup from https://github.com/open-telemetry/opentelemetry-ruby/pull/1070#discussion_r778550898
cc @arielvalentin

chore: move faraday patch into appraisals for koala instrumentation

---

.github/workflows/ci.yml
instrumentation/active_record/test/instrumentation/active_record/patches/persistence_class_methods_test.rb
sdk/test/opentelemetry/sdk/trace/span_test.rb

* Add new ruby 3.1 into ci list

Added ruby 3.1 in ci list

---

website_docs/_index.md

Contributes to https://github.com/open-telemetry/opentelemetry.io/issues/1096
/cc @cartermp @austinlparker

[website_docs] fix page meta-links

---

resource_detectors/lib/opentelemetry/resource/detectors/google_cloud_platform.rb
resource_detectors/test/opentelemetry/detectors/google_cloud_platform_test.rb

Add resource detector for Google Cloud Function.
Closes #1124

feat: Added Google Cloud Function Resource Detection

---

.github/workflows/ci-without-services.yml

chore: Rename GH Action to disambiguate it in the UI

---

.toys/.data/releases.yml

This is a second attempt to fix the registry release.

fix: Registry Release Config

---

instrumentation/all/opentelemetry-instrumentation-all.gemspec

cc: https://github.com/open-telemetry/opentelemetry-ruby/pull/978

fix: Add rdkafka to all

---

CODEOWNERS

chore: add sam to code owners

---

common/.rubocop.yml
common/lib/opentelemetry/common/propagation/rack_env_getter.rb
common/lib/opentelemetry/common/utilities.rb
common/opentelemetry-common.gemspec
exporter/jaeger/.rubocop.yml
exporter/jaeger/lib/opentelemetry/exporter/jaeger.rb
exporter/jaeger/lib/opentelemetry/exporter/jaeger/encoder.rb
exporter/jaeger/opentelemetry-exporter-jaeger.gemspec
exporter/jaeger/test/.rubocop.yml
exporter/otlp/.rubocop.yml
exporter/otlp/lib/opentelemetry/exporter/otlp/exporter.rb
exporter/otlp/opentelemetry-exporter-otlp.gemspec
exporter/otlp/test/.rubocop.yml
registry/.rubocop.yml
registry/opentelemetry-registry.gemspec
registry/test/opentelemetry/instrumentation/registry_test.rb

Signed-off-by: Scott Hain <elejia@gmail.com>
Helps add to [opentelemetry-ruby 1321](https://github.com/open-telemetry/opentelemetry-ruby/issues/1321)

Update rubocop on multiple items to 1.3.x

---

exporter/otlp/README.md

Fix https://github.com/open-telemetry/opentelemetry-ruby/discussions/1372

fix OTLP exporter demo code

---

website_docs/_index.md

resolve https://github.com/open-telemetry/opentelemetry-ruby/issues/1380

accessibility: add alt tag to image

---

README.md

No longer at Shopify. Will update this repo along with -contrib

Update README.md remove shopify affiliation

---

sdk_experimental/lib/opentelemetry/sdk/trace/samplers/consistent_probability_based.rb
sdk_experimental/lib/opentelemetry/sdk/trace/samplers/consistent_probability_tracestate.rb
sdk_experimental/test/opentelemetry/sdk/trace/samplers/consistent_probability_based_test.rb

fix: consistently pass tracestate

---

sdk_experimental/README.md

We should have a readme for this package.

add readme to sdk-experimental

---

exporter/otlp/Rakefile
exporter/otlp/lib/opentelemetry/proto/collector/logs/v1/logs_service_pb.rb
exporter/otlp/lib/opentelemetry/proto/collector/metrics/v1/metrics_service_pb.rb
exporter/otlp/lib/opentelemetry/proto/collector/trace/v1/trace_service_pb.rb
exporter/otlp/lib/opentelemetry/proto/common/v1/common_pb.rb
exporter/otlp/lib/opentelemetry/proto/logs/v1/logs_pb.rb
exporter/otlp/lib/opentelemetry/proto/metrics/v1/metrics_pb.rb
exporter/otlp/lib/opentelemetry/proto/trace/v1/trace_pb.rb

Closes https://github.com/open-telemetry/opentelemetry-ruby/issues/1462

feat: Use OTLP 0.20.0 protos

---

logs_sdk/.rubocop.yml
logs_sdk/.yardopts
logs_sdk/CHANGELOG.md
logs_sdk/Gemfile
logs_sdk/LICENSE
logs_sdk/Rakefile
logs_sdk/lib/opentelemetry-logs-sdk.rb
logs_sdk/lib/opentelemetry/sdk/logs.rb
logs_sdk/lib/opentelemetry/sdk/logs/version.rb
logs_sdk/opentelemetry-logs-sdk.gemspec
logs_sdk/test/.rubocop.yml
logs_sdk/test/test_helper.rb

This PR creates the initial gem structure for the Logs SDK.

feat: Create opentelemetry-logs-sdk gem

---

.github/workflows/ci.yml

Adds Ruby 3.3 testing to the CI.

ci: Add tests for Ruby 3.3

---

api/lib/opentelemetry/context/propagation/composite_text_map_propagator.rb
api/test/opentelemetry/context/propagation/composite_text_map_propagator_test.rb

Hi! It looks like there's a typo here - the current implementation causes SystemStackError.

fix a typo in composite_text_map_propagator

---

.github/workflows/stale.yaml

There are quite a few PRs and issues that remain open without any activity.
This PR introduces stalebot to do some housekeeping for us.

chore: Enable stalebot

---

metrics_api/lib/opentelemetry/metrics/meter.rb

See https://github.com/open-telemetry/opentelemetry-ruby/security/code-scanning/2

Resolve code-scanning#2

---

metrics_sdk/README.md

I think #1603 made this available.

docs: Mention support for periodic exporting in README
